### ISSUE TITLE
Hide Messenger Pop Up?

### ISSUE THREAD

**Issue by wamzle** [woocommerce/facebook-for-woocommerce#1226]
Is there a way to stop the messenger window from popping up on every page? ... it's a bit annoying.

**Comment by lgfogle** [comment]
Hey @wamzle,

Thanks for reaching out! We have this feature planned for a future release - you'll be able to determine if and how the Messenger widget appears on the pages of your site. 

Thank you!
Lindsey

**Comment by kvanopde** [comment]
> Hey @wamzle,
> 
> Thanks for reaching out! We have this feature planned for a future release - you'll be able to determine if and how the Messenger widget appears on the pages of your site.
> 
> Thank you!
> Lindsey

Hi is there any progress in this issue? It would be great if it's possible to disable the auto pop-up.

Greetings

Kristof

**Comment by therishipatel** [comment]
Hi @haszari, was this feature/enhancement implemented? If so, how do I disable the popup?

Thanks in advance!

**Comment by haszari** [comment]
Hi there @therishipatel (and @wamzle!) 🙂 

You can disable or enable the Facebook Messenger popup in settings:

- `wp-admin dashboard > Marketing > Facebook > Messenger > Enable Messenger`

<img width="942" alt="Screen Shot 2021-06-08 at 7 36 47 AM" src="ht@therishipatel  //user-images.githubusercontent.com/4167300/121077869-4a900200-c82c-11eb-8146-64269a747f0a.png">

**Comment by andrzejbed** [comment]
This is not about switching off the entire intgration, but only to keep the messenger minified on startup.
There are so many popups nowodays - cookie consent, marketing, etc. Users get really annoyed when they have to close more than 3 popups to start using the page.
I managed to achieve this with this piece of CSS:

.fb_iframe_widget iframe:not(.fb_customer_chat_bounce_in_v2) {
    visibility: hidden !important;
}

**Comment by langleyik** [comment]
I agree with ndrwbdnz. The messenger needs to stay minimised when minimised. At present it keeps popping up a second after closing. I have customers that do connect with us through the chat, if they didnt i would be deleting it as the auto pop up is very annoying and harmful to our user UX

Please up date it to keep it minimised

**Comment by rawdreeg** [comment]
I could not reproduce this issue on mobile. It seems the messenger widget has been updated and the problem is no longer reproducible. I will close this. Feel free to open a new issue ticket with more details if you're still experiencing this.
