### ISSUE TITLE
Wrong variation price as default

### ISSUE THREAD

**Issue by vankampenp** [woocommerce/facebook-for-woocommerce#1242]
Hi, in my shop www.facebook.com/vogelsnederland I have product with variations. Of most of the products, the lowest price (first in the order), is selected to show the price. 
However, in some a random more expensive variation is used, showing a higher default price. For example: https://www.facebook.com/commerce/products/4387244794634507/?rid=100148965012671&rt=9&referral_code=page_cta&ref=page_shop_tab
The ordering is correct, but the first variation is not used  as the default variation.

This is not the same issue as #309.

**Comment by lgfogle** [comment]
Hey @vankampenp,

I wanted to let you know that we have a planned fix to ensure that the default variation in WooCommerce is carried over to Facebook. I'll update here once that fix is ready! 

Thank you,
Lindsey

_[Internal reference CH53687](https://app.clubhouse.io/skyverge/story/53687/)_

**Comment by haszari** [comment]
@lgfogle Do you know the status of this improvement - can you give me more details? Thank you :)

**Comment by budzanowski** [comment]
This should be fixed by #1784
