### ISSUE TITLE
is_readable(): open_basedir restriction in effect

### ISSUE THREAD

**Issue by jd4u** [woocommerce/facebook-for-woocommerce#1642]
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

PHP Warning:  is_readable(): open_basedir restriction in effect. File(/includes/fbwpml.php) is not within the allowed path(s): (D:\www\customDomain\) 

##🚶‍♀️ Steps to reproduce

Windows Server with PHP 7.3 having open_basedir setup will create the issue with logging lots of errors in debug.log

## ✔️ Expected behavior

while checking the file using is_readable() provide absolute path instead of relative path.

## WordPress (please complete the following information):
Core version: 5.5.1
Gutenberg version (if installed): --
WooCommerce version: 4.6.1
Facebook for WooCommerce version: 2.0.5
Site language: en-GB
Any other plugins installed:

## 🗃 Logs

PHP Warning:  is_readable(): open_basedir restriction in effect. File(/includes/fbwpml.php) is not within the allowed path(s): (D:\www\customDomain\) in D:\www\customDomain\public_html\wp-content\plugins\facebook-for-woocommerce\includes\Integrations\Integrations.php on line 61

PHP Warning:  is_readable(): open_basedir restriction in effect. File(/includes/Integrations/Bookings.php) is not within the allowed path(s): (D:\www\customDomain\) in D:\www\customDomain\public_html\wp-content\plugins\facebook-for-woocommerce\includes\Integrations\Integrations.php on line 61

**Comment by jd4u** [comment]
After studying the code of plugin, the issue is fixed for now, prefixing "`$this->plugin->get_plugin_path() . `" to the paths arrays. 
Below is the code lines.

```
$registered_integrations = [
            'WC_Facebook_WPML_Injector' => $this->plugin->get_plugin_path() . '/includes/fbwpml.php',
            Bookings::class             => $this->plugin->get_plugin_path() . '/includes/Integrations/Bookings.php',
];
```

**Comment by AntonyXSI** [comment]
It would be great if this could be fixed as it's adding a lot of lines to the error log.

The "! is_readable( $path )" line would need to be changed to "is_readable( $path )" just below this, once the full plugin path is added. 

I'm not sure why it checks if that file path is _not_ readable.

**Comment by maxleistner** [comment]
Same here. A higher prio would be good. Tons of MB of error logs are the result currently :/

**Comment by theabhig** [comment]
Just noting this error was reported in 4137993-zen 

Thanks!

**Comment by honlapdavid** [comment]
Same problem.

Warning: is_readable(): open_basedir restriction in effect. File(/includes/fbwpml.php) is not within the allowed path(s): (/home/wp026800:/usr/share/pear) in /home/wp026800/www_root/wp-content/plugins/facebook-for-woocommerce/includes/Integrations/Integrations.php on line 61

**Comment by pau1phi11ips** [comment]
Same problem here. Adding the fix above sorted it for me.

Pretty shocked this was highlighted 24 Oct 2020!?

**Comment by moustapha7ci** [comment]
prefixing "$this->plugin->get_plugin_path() . " solve the issue for me. thx a lot

**Comment by honlapdavid** [comment]
@moustapha7ci and how i can? beacouse im not programmer, thank you

**Comment by moustapha7ci** [comment]
Check on your hosting files this file. wp-content/plugins/facebook-for-woocommerce/includes/Integrations/Integrations.php.
You should see this:
******
$registered_integrations = [
            'WC_Facebook_WPML_Injector' =>  '/includes/fbwpml.php',
            Bookings::class             => '/includes/Integrations/Bookings.php',
];
****
Just add this code << $this->plugin->get_plugin_path() . >> before '/includes/fbwpml.php' and '/includes/Integrations/Bookings.php'

Finaly You should get this code, then save

*******
$registered_integrations = [
            'WC_Facebook_WPML_Injector' => $this->plugin->get_plugin_path() . '/includes/fbwpml.php',
            Bookings::class             => $this->plugin->get_plugin_path() . '/includes/Integrations/Bookings.php',
];
*******

**Comment by honlapdavid** [comment]
@moustapha7ci 

Thank you! its working!

**Comment by dalepgrant** [comment]
```
Warning: is_readable(): open_basedir restriction in effect. File(/includes/fbwpml.php) is not within the allowed path(s): (/srv/www/:/tmp) in /redacted/path/to/facebook-for-woocommerce/includes/Integrations/Integrations.php on line 61
```
Followed by `Cannot modify header information - headers already sent`

**Comment by jd4u** [comment]
@haszari , 

Its been long for this issue be fixed. I am requesting again as it loads logs file everyday. It a practical problem on production instances.

Moreover, I tested it on Ubuntu. The solution suggested works on Linux too, use `facebook_for_woocommerce()->get_plugin_path()`.

Secondly, I reviewed the the function `$this->plugin->get_plugin_path()` or `facebook_for_woocommerce()->get_plugin_path()' (as used in `FBCategories.php`). It has no code that created compatibility issues.

`
public function get_plugin_path() {

		if ( null === $this->plugin_path ) {
			$this->plugin_path = untrailingslashit( plugin_dir_path( $this->get_file() ) );
		}

		return $this->plugin_path;
	}
`

**Comment by WP-SpeedPlus** [comment]
Same problem with new WP and PHP 7.4
`is_readable(): open_basedir restriction in effect. File(/includes/fbwpml.php) is not within the allowed path(s): (/home/:/tmp/)`

**Comment by zeinnicholas** [comment]
+1

**Comment by ANOUAR-DA** [comment]
> @honlapdavid Vérifiez sur vos fichiers d'hébergement ce fichier. wp-content/plugins/facebook-for-woocommerce/includes/Integrations/Integrations.php.
> Vous devriez voir ceci :
> 
> $registered_integrations = [
> 'WC_Facebook_WPML_Injector' => '/includes/fbwpml.php',
> Bookings::class => '/includes/Integrations/Bookings.php',
> ];
> 
> Ajoutez simplement ce code << $this->plugin->get_plugin_path() . >> avant '/includes/fbwpml.php' et '/includes/Integrations/Bookings.php'
> 
> Enfin, vous devriez obtenir ce code, puis enregistrez
> 
> $registered_integrations = [
> 'WC_Facebook_WPML_Injector' => $this->plugin->get_plugin_path() . '/includes/fbwpml.php',
> Bookings::class => $this->plugin->get_plugin_path() . '/includes/Integrations/Bookings.php',
> ];

Bonjour 
@moustapha7ci  
je vérifier les  fichiers d'hébergement . wp-content/plugins/facebook-for-woocommerce/includes/Integrations/Integrations.php. et j'ai trouve cette code

- Avant modification
$registered_integrations = array(
			'WC_Facebook_WPML_Injector' => '/includes/fbwpml.php',
			Bookings::class             => '/includes/Integrations/Bookings.php',
		);

- Après modification
$registered_integrations = array(
			'WC_Facebook_WPML_Injector' => $this->plugin->get_plugin_path() . '/includes/fbwpml.php',
			Bookings::class             => $this->plugin->get_plugin_path() . '/includes/Integrations/Bookings.php',
		);

mais malheureusement il s'affiche toujours la même erreur :
 Warning: is_readable(): open_basedir restriction in effect. File(/includes/fbwpml.php) is not within the allowed path(s): (/home:/home2:/home3:/usr/local/lib/php:/tmp:/usr/lib/php/:/usr/share/l.v.e-manager/:/opt/alt/php74/:/usr/local/lsws/) in /home/ecoolma/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Integrations/Integrations.php on line 61

NB : Version PHP 7.4

Cordialement,

**Comment by grasengroen** [comment]
I can confirm the bug exists, and that adding `$this->plugin->get_plugin_path()` is the proper solution, also on Linux.

Please merge pull request https://github.com/woocommerce/facebook-for-woocommerce/pull/2046

**Comment by joostvanveen** [comment]
I can confirm the bug exists, and that adding $this->plugin->get_plugin_path() is the proper solution, also on Linux.

Please merge pull request https://github.com/woocommerce/facebook-for-woocommerce/pull/2046

**Comment by ANOUAR-DA** [comment]
> I can confirm the bug exists, and that adding $this->plugin->get_plugin_path() is the proper solution, also on Linux.
> 
> Please merge pull request #2046

i've this error displayed even in the wordpress administration consol 

that's being said,

I checked the hosting files. wp-content / plugins / facebook-for-woocommerce / includes / Integrations / Integrations.php. and I found this code

Before modification

```
$ registered_integrations = array (
'WC_Facebook_WPML_Injector' => '/includes/fbwpml.php',
Bookings :: class => '/includes/Integrations/Bookings.php',
);
```

**After modification**

```
$ registered_integrations = array (
'WC_Facebook_WPML_Injector' => $ this-> plugin-> get_plugin_path (). '/includes/fbwpml.php',
Bookings :: class => $ this-> plugin-> get_plugin_path (). '/includes/Integrations/Bookings.php',
);
```

but unfortunately it always shows the same error:

Warning: is_readable (): open_basedir restriction in effect. File (/includes/fbwpml.php) is not within the allowed path (s): (/ home: / home2: / home3: / usr / local / lib / php: / tmp: / usr / lib / php /: / usr / share / lve-manager /: / opt / alt / php74 /: / usr / local / lsws /) in / home / ecoolma / public_html / wp-content / plugins / facebook-for-woocommerce / includes / Integrations / Integrations .php on line 61

NB: - PHP version 7.4
      - Facebook for WooCommerce  Version 2.6.1 


Cordially,

**Comment by marcusforsberg** [comment]
This desperately needs fixing, it's filling up the PHP logs with this warning. Definitely not low priority for any website of considerable size. @haszari 

<img width="751" alt="Screen Shot 2021-07-30 at 11 23 28 AM" src="https://user-images.githubusercontent.com/1009069/127632082-027d5d61-1231-4995-8a1b-3fc4c31bd859.png">

**Comment by Tygovanommen** [comment]
+1

**Comment by orgabor** [comment]
+1 Same here

**Comment by omarNIU** [comment]
+1

**Comment by agnieszkainvolt** [comment]
I have some problem after updates with plugin.

Warning: is_readable(): open_basedir restriction in effect. File(/includes/fbwpml.php) is not within the allowed path(s): on line 62
if ( ! class_exists( $class_name ) && ! is_readable( $path ) ) {

Maybe some could help me fix it?

**Comment by melindahelt** [comment]
This issue was discussed in https://wordpress.org/support/topic/error-in-integrations-php-on-line-62/ as well

**Comment by JosKlever** [comment]
Can somebody please give a status update? There are already 3 working fixes available, but there doesn't seem to be a priority to implement it and after each update of the plugin it's promised to do it in the next update, but we still have to fix it by hand. Who can change the priority?

**Comment by pau1phi11ips** [comment]
Having to manually change the plugin code with each auto-update is getting old fast. It's just 2 lines of code guys.

**Comment by coccoinomane** [comment]
The bug is still there, clogging up all debug logs... [changing two lines of code](https://github.com/woocommerce/facebook-for-woocommerce/issues/1642#issuecomment-882469450) fixes this... please bump this issue on your priority list.

```
PHP Warning:  is_readable(): open_basedir restriction in effect. File(/includes/fbwpml.php) is not within the allowed path(s): (/home/omainowornever/:/opt/cpanel/ea-php74/root/usr:/usr/local/lib/php:/tmp:/etc/pki/tls/certs/ca-bundle.crt:/var/cpanel/php/sessions) in /home/omainowornever/public_html/cms/wp-content/plugins/facebook-for-woocommerce/includes/Integrations/Integrations.php on line 62
```

**Comment by alapiere** [comment]
almost 1 year and still no fix ? Do you have any idea how much cumulated wordwide useless logs have been generated by this bug ? save the disks, save the planet !

**Comment by zeinnicholas** [comment]
I guess these folks only do something when they are threatened or offended.

**Comment by michaeltieso** [comment]
A bit of a frustrating issue here to see this hasn't been resolved and clogging up logs.

**Comment by rashedripon** [comment]
Reported here as well 4299751-zen

**Comment by danielbitzer** [comment]
Updating to version 2.6.5 of the plugin should fix the issue.
