### ISSUE TITLE
Server side sending of pixel events blocks generating pages

### ISSUE THREAD

**Issue by tatusah** [woocommerce/facebook-for-woocommerce#1675]
## 🔎 Isolate the bug
- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Sending pixel events uses blocking PHP code which means that generating the user requested page gets paused while the event data is handled by the graph.facebook.com server. Measuring the code execution shows that the _send_api_event_ method seems to slow down the generating page between 0.5-6 seconds depending on how fast the Facebook server answers to the API requests.

##🚶‍♀️ Steps to reproduce

1. Use something like New Relic or Tideways to profile execution of pages that injects Facebook tracking (e.g. single product or product category). Alternatively use something like `curl -s -o /dev/null -w "%{time_total}\n" -H "Pragma: no-cache" https://example.com/` to measure the time for generating the selected page.
2. Measure execution of the selected pages with Facebook for Woocommerce plugin enabled
3. Measure execution of the selected pages with Facebook for Woocommerce plugin enabled or edit the facebook-commerce-events-tracker.php file to not send the API event.
4. Compare the results

## ✔️ Expected behavior
Sending pixel events should use non blocking method and/or execute sending the data to Facebook API after the page is generated and sent to user's browser.

**Comment by devonto** [comment]
Using Query Monitor within WordPress, I have also seen this slow-down.

The call is being made to the following URL:  https://graph.facebook.com/v9.0/XXX/events

And is initiated in the `woocommerce_after_single_product` hook, calling `WC_Facebookcommerce_EventsTracker->inject_view_content_event()`

```
200 OK-HTTP API Transport: curl
DNS Resolution Time: 0.0156
Connection Time: 0.0183
Transfer Start Time (TTFB): 0.8268
Response Size: 74 B
Response Content Type: application/json
IP Address: 157.240.221.18
```

This is adding an overhead of almost a whole second to each page load, which is huge!
