### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by sabrinahughes** [woocommerce/facebook-for-woocommerce#1685]
## 🔎 Isolate the bug

- [ x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
My site was just updated to PHP 7.4 after which when I edited a product, the text in the description was not visible (white text on white background), and all of the product tags were gone.

**Comment by PatoPC** [comment]
I confirmed too, that the last version facebook Versión: 2.1.4 is not compatible with WooCommerce Versión: 4.6.2, I have same issue

**Comment by simonporter007** [comment]
Hi @sabrinahughes and @PatoPC,

Thanks for reporting this! I took a quick look locally, and spun up a new site with PHP with 7.4 and WooCommerce 4.6.2, and I'm not currently seeing the issue you've described. To make sure I'm testing exactly what you're seeing, would it be possible to share a screenshot of the issue so I can see exactly which field has the problem? The main description, short description, and Facebook description fields are all behaving as normal in my test site.

Is this happening for all products when Facebook for WooCommerce is active? Does the problem resolve itself when the plugin is deactivated?

Cheers!

**Comment by PatoPC** [comment]
Hi, 
I have WooCommerce  version 4.7.0
WordPress version  5.5.3	
MySQL  5.7.23-23	
PHP  7.3.24
When the plugin is disabled, into the section edit/create product the fields for input information show correctly like you can see in the image:
![Correcto](https://user-images.githubusercontent.com/14806765/99167913-7c951780-26d4-11eb-8764-5ab5d3c84b91.png)

But after the active the plugin I have an error 
![facebookActivate](https://user-images.githubusercontent.com/14806765/99167905-7bfc8100-26d4-11eb-9fc1-85a7ab532d45.png)

I can not see the text into the input and all the buttons not working.

![errorFacebookPlugin](https://user-images.githubusercontent.com/14806765/99167919-7c951780-26d4-11eb-85c9-51b7ef0c193f.png)

**Comment by rawdreeg** [comment]
Closing as stale.
