### ISSUE TITLE
Unrecognized field: A request for item wc_post_id_xxxx contains unrecognized field additional_variant_attributes

### ISSUE THREAD

**Issue by voxoff79** [woocommerce/facebook-for-woocommerce#1686]
HI,

when i make some changes in the product in woocommerce and update the same product I’m getting this message in the logs for every product and variation created in facebook

{“warnings”:[{“message”:”Unrecognized field: A request for item wc_post_id_XXX contains unrecognized field additional_variant_attributes”}

This causes an empty dropdown box in the facebook product page with n possibility from choosing a different variation!

i already delete de plugin, delete the integration, delete de catalog in facebook, try to make all from the beggining but i still getting this messages.

Thanks in advance for your time

**Comment by voxoff79** [comment]
11-09-2020 @ 22:11:04 - Response
Response
code: 200
message: OK
headers: Array
(

)
body: {"handles":["AcxAm00BjPKRk96-GSxpwBxcL3fj8q2o_1Fhc5O5OyxiszquYRlYwjDuA5eR046YoS1cyV7bJz-EXLfwpONx08ZAuwAiS1J8NSi2-SupAbKjNA"],"validation_status":[{"warnings":[{"message":"Unrecognized field: A request for item wc_post_id_2800 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_2799 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_2801 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_2790 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_2789 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_2788 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1356 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1357 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1358 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1338 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1336 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1337 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1237 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1236 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1235 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1227 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1228 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1229 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1196 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1195 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1194 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1183 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1182 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1181 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1048 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1049 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_1050 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_809 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_810 contains unrecognized field additional_variant_attributes"},{"message":"Unrecognized field: A request for item wc_post_id_811 contains unrecognized field additional_variant_attributes"}]}]}

**Comment by rawdreeg** [comment]
Closing as stale.
