### ISSUE TITLE
PHP Warnings Spam at Cron

### ISSUE THREAD

**Issue by yward** [woocommerce/facebook-for-woocommerce#1688]
The plugin is throwing plenty of PHP warnings each cron job as follows:

`Invalid argument supplied for foreach() in /dir-to-website-root/public_html/wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php on line 673, referer: https://yourwebsite/wp-cron.php?doing_wp_cron=160502954XXXXXXXXXX2510986XXXXX50`

The culpirt code is here:
```

foreach ( $all_attributes as $attribute ) {
				$value = Products::get_enhanced_catalog_attribute( $attribute['key'], $this->woo_product );

				if ( ! empty( $value ) &&
					$category_handler->is_valid_value_for_attribute( $google_category_id, $attribute['key'], $value )
				) {
					$enhanced_data[ $attribute['key'] ] = $value;
				}
			}
```

I suspect this issue is related to the previous issue with google catalouge attributes which was fixed in the latest version:
Ref: https://github.com/facebookincubator/facebook-for-woocommerce/issues/1674

**Comment by budzanowski** [comment]
Should be fixed with https://github.com/woocommerce/facebook-for-woocommerce/pull/1820 and released soon.
