### ISSUE TITLE
Plugin bug Version 2.1.4

### ISSUE THREAD

**Issue by Aretiiiii** [woocommerce/facebook-for-woocommerce#1693]
For reference, this is the error in the logs:
[11-Nov-2020 10:58:24 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 1806336 bytes) in /wordpress/core/5.5.3/wp-includes/functions.php on line 4673
And you'll find the screenshot attached where it shows the memory usage by autoload option.

<img width="1036" alt="Screenshot 2020-11-11 at 12 12 49" src="https://user-images.githubusercontent.com/74301133/98807977-2601b200-2424-11eb-982f-c133741b6cb3.png">

**Comment by budzanowski** [comment]
This was addressed with one of the recent releases of the plugin. Closing until we have other reports about this.
