### ISSUE TITLE
Crashed my website

### ISSUE THREAD

**Issue by alanmp3** [woocommerce/facebook-for-woocommerce#1695]
The latest update of Facebook For Webcommerce plugin crashed my website and made it inaccessible. I had to have the website restored by my web host. The plugin has now been deleted from my website.

I can I safely re-add this plugin to my website without crashing the site again?

Website: stfrancisdammemorial.org

**Comment by hengsoheak** [comment]
Me too after I installed and There has been a critical error on your website. Please check your site admin email inbox for instructions.
