### ISSUE TITLE
how can I change from automattic app to my own app 

### ISSUE THREAD

**Issue by hengsoheak** [woocommerce/facebook-for-woocommerce#1696]
## Feature requests
Dear Dev,
I would like to know some configuration for change the Facebook app by any configuration 
because it related to company profile and data security so we want to use our own app (Not use automattic)
So do you have another configuration for me to set up with our own Facebook app

**Comment by budzanowski** [comment]
The plugin does not support custom application setup. This can be requested as an improvement but it is hard to tell when any development resources would be used for this.
