### ISSUE TITLE
2.1.4 - Something went wrong when connecting to facebook.

### ISSUE THREAD

**Issue by stevesweets** [woocommerce/facebook-for-woocommerce#1697]
## 🔎 Isolate the bug
- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
When making a new connection to facebook on the 2.1.4, you get the titular error.  I was able to install an earlier version (2.1.1) to make a connection, and then upgrade.

##🚶‍♀️ Steps to reproduce
1. Install 2.1.4
2. Connect to facebook, go through all the steps until the last one where it finalises the connection.

## ✔️ Expected behavior
It should connect without error.

## 🗃 Logs
I unfortunately do not have relevant logs to hand, but have found this problem twice setting up new facebook connections on two seperate sites.

**Comment by Bludelego** [comment]
Same thing happen to me

**Comment by diediepie** [comment]
**the same here** 
<img width="570" alt="Screen Shot 2020-11-13 at 3 06 54 AM" src="https://user-images.githubusercontent.com/58274751/99019796-6dd82480-255d-11eb-8b9d-7f1c8610d349.png">

**Comment by gencaysahinn** [comment]
I got the same error. Is there any news?

**Comment by gayan-ad** [comment]
I got the same issue over and over again, this is really frustrating. I tried with the older version 1.114. it worked. but again stop working after the update to the new version. Really wasting our time. try to get the help of FB team for a few days still couldn't resolve it.

**Comment by omarragi** [comment]
Up

**Comment by ad33lzia** [comment]
Facing the same issue, no success

**Comment by phillipcornwell** [comment]
Reported in 30331779-hc

**Comment by budzanowski** [comment]
The issue is coming from Facebook server and there is nothing the plugin can really do about this. If this happens constantly during connection please contact Facebook help for assistance.
