### ISSUE TITLE
Plugin Crashing my product add page

### ISSUE THREAD

**Issue by JossPer0** [woocommerce/facebook-for-woocommerce#1699]
Error Details
=============
An error of type E_ERROR was caused in line 45 of the file /home/vertprin/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Admin/Products.php. Error message: Uncaught TypeError: Argument 1 passed to SkyVerge\WooCommerce\Facebook\Admin\Products::render_google_product_category_fields_and_enhanced_attributes() must be an instance of WC_Product, bool given, called in /home/vertprin/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Admin.php on line 1205 and defined in /home/vertprin/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Admin/Products.php:45
Stack trace:
#0 /home/vertprin/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Admin.php(1205): SkyVerge\WooCommerce\Facebook\Admin\Products::render_google_product_category_fields_and_enhanced_attributes(false)
#1 /home/vertprin/public_html/wp-includes/class-wp-hook.php(287): SkyVerge\WooCommerce\Facebook\Admin->add_product_settings_tab_content('')
#2 /home/vertprin/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/vertprin/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/vertprin/public_html/wp-content/

**Comment by gudinoemiliano** [comment]
Same issue. Any fixes around?

**Comment by JossPer0** [comment]
Hey,

Nope nothing yet

**Comment by budzanowski** [comment]
This should have been fixed some time ago. Please reopen in case the problem persist.
