### ISSUE TITLE
Enabling plugin breaks Woocommerce Product edit page

### ISSUE THREAD

**Issue by simo923** [woocommerce/facebook-for-woocommerce#1700]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
When the plugin is enabled, a number of features in the Woocommerce product pages do not work;
* Product description does not show
* Screen Options button does not work
* Help button does not work
* Several plugins/widgets do not show, including Yoast SEO Premium
* Unable to edit various descriptions/attributes
Fault with Plugin Activated:
![image](https://user-images.githubusercontent.com/38377767/99117875-67de5400-25ee-11eb-8eb3-620d267aa2f5.png)

Working with Plugin Deactivated
![image](https://user-images.githubusercontent.com/38377767/99117993-a411b480-25ee-11eb-815a-3bd4757c597f.png)

##🚶‍♀️ Steps to reproduce

1. TEnable the plugin
2.  All faults occur
3.  Disable the plugin
4.  Woocommerce product pages work as they should 

## ✔️ Expected behavior
Expect to view and edit product description
Expect to see all widgets/plugins in product edit page
Expect for all dropdowns/screen options to work 

## 🗃 Logs

`
### WordPress Environment ###

WordPress address (URL): https://mobileecotuning.com
Site address (URL): https://mobileecotuning.com
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.12
PHP Post Max Size: 6 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62-log - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: notJz
Total Database Size: 106.05MB
Database Data Size: 75.95MB
Database Index Size: 30.10MB
notJzwoocommerce_sessions: Data: 0.42MB + Index: 0.02MB + Engine InnoDB
notJzwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
notJzwoocommerce_order_items: Data: 0.20MB + Index: 0.08MB + Engine InnoDB
notJzwoocommerce_order_itemmeta: Data: 1.52MB + Index: 2.00MB + Engine InnoDB
notJzwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
notJzwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzwoocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzactionscheduler_actions: Data: 6.41MB + Index: 1.73MB + Engine InnoDB
notJzactionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzactionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzactionscheduler_logs: Data: 3.41MB + Index: 2.63MB + Engine InnoDB
notJzadtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzaelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzaelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzaws_cache: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
notJzaws_index: Data: 2.28MB + Index: 1.73MB + Engine InnoDB
notJzcleantalk_ac_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzcleantalk_sessions: Data: 1.41MB + Index: 0.00MB + Engine InnoDB
notJzcleantalk_sfw: Data: 0.36MB + Index: 0.31MB + Engine InnoDB
notJzcleantalk_sfw_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzcleantalk_spamscan_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzcommentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzcomments: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
notJzcpf_custom_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzcpf_feedproducts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzcpf_resolved_product_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzcp_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzfailed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzlinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzmailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzmailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzoptions: Data: 6.33MB + Index: 0.20MB + Engine InnoDB
notJzpostmeta: Data: 10.52MB + Index: 8.03MB + Engine InnoDB
notJzposts: Data: 3.52MB + Index: 0.47MB + Engine InnoDB
notJzqueue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzsbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzsbi_instagram_posts: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
notJzsmush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzspbc_auth_logs: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
notJzspbc_backuped_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzspbc_backups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzspbc_firewall_data: Data: 9.55MB + Index: 6.55MB + Engine InnoDB
notJzspbc_firewall_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzspbc_firewall__personal_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzspbc_firewall__personal_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzspbc_scan_frontend: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzspbc_scan_links_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
notJzspbc_scan_results: Data: 5.52MB + Index: 1.39MB + Engine InnoDB
notJzspbc_scan_signatures: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzspbc_traffic_control_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJztermmeta: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
notJzterms: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
notJzterm_relationships: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
notJzterm_taxonomy: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
notJzusermeta: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
notJzusers: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
notJzvw_vprooms: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
notJzvw_vpsessions: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
notJzwc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwc_customer_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
notJzwc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzwc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzwc_order_product_lookup: Data: 0.19MB + Index: 0.19MB + Engine InnoDB
notJzwc_order_stats: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
notJzwc_order_tax_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
notJzwc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
notJzwc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
notJzwfconfig: Data: 2.44MB + Index: 0.00MB + Engine InnoDB
notJzwfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwffilemods: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
notJzwfhits: Data: 0.27MB + Index: 0.05MB + Engine InnoDB
notJzwfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
notJzwfknownfilelist: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
notJzwflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwflogins: Data: 0.36MB + Index: 0.13MB + Engine InnoDB
notJzwfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwfpendingissues: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
notJzwfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
notJzwfstatus: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
notJzwftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwoobe_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
notJzwoobe_history_bulk: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzwpfb_badges: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpfb_floats: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpfb_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpfb_getapps_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpfb_gettwitter_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpfb_nofitifcation_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpfb_post_templates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpfb_reviewfunnel: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpfb_reviews: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
notJzwpfb_total_averages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_category_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzwpgmza_datasets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_maps_has_custom_fields_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_markers_has_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_markers_has_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_nominatim_geocode_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpsc_email_notification: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpsc_ticket: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzwpsc_ticketmeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzyith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzyith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzyoast_indexable: Data: 1.50MB + Index: 0.61MB + Engine InnoDB
notJzyoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
notJzyoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
notJzyoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
notJzyoast_prominent_words: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
notJzyoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
notJzyoast_seo_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
notJzza_categories_to_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzza_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzza_headers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzza_products_to_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzza_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
notJzza_values: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 810
carousels: 2
custom_css: 2
customize_changeset: 24
is_search_form: 1
nav_menu_item: 123
oembed_cache: 38
page: 25
post: 3
product: 122
product_variation: 34
revision: 136
sa_slider: 2
shop_coupon: 9
shop_order: 766
shop_order_refund: 1
trusted_theme_mod: 4
vg_gateway_condition: 1
woo_slide_pro_post: 3
wpforms: 2
wpsc_ticket_thread: 32

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (44) ###

Query Monitor: by John Blackbourn – 3.6.5
Advanced Woo Search: by ILLID – 2.14 – Installed version not tested with active version of WooCommerce 4.7.0
AMP: by AMP project contributors – 2.0.5
BackWPup: by Inpsyde GmbH – 3.8.0
Anti-Spam by CleanTalk: by СleanTalk  – 5.148
GDPR Cookie Consent: by WebToffee – 1.9.3
Join.chat: by Creame – 4.1.1
Facebook for WooCommerce: by Facebook – 2.1.4 – Installed version not tested with active version of WooCommerce 4.7.0
The Official Facebook Chat Plugin: by Facebook – 1.9
GazChap's WooCommerce getAddress.io Postcode Lookup: by Gareth 'GazChap' Griffiths – 1.5.1 – Installed version not tested with active version of WooCommerce 4.7.0
Site Kit by Google: by Google – 1.20.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Smash Balloon Instagram Feed: by Smash Balloon – 2.5.4
Limit log in attempts reloaded: by WPChef – 2.15.2
Custom Login Page Customizer: by Hardeep Asrani – 2.0.1
Login No Captcha reCAPTCHA (Google): by Robert Peake – 1.6.10
PayL8r Gateway for WooCommerce: by  – 1.4.3 – Installed version not tested with active version of WooCommerce 4.7.0
Product Add-Ons WooCommerce: by BizSwoop a CPF Concepts
LLC Brand – 2.0.26

Rearrange Woocommerce Products: by Aslam Doctor – 2.3.1 – Installed version not tested with active version of WooCommerce 4.7.0
Regenerate Thumbnails Advanced: by ShortPixel – 2.3.2
Security by CleanTalk: by CleanTalk Security – 2.57.2
Shortcode in Menus: by Gagan Deep Singh – 3.5
Slide Anything - Responsive Content / HTML Slider and Carousel: by Simon Edge – 2.3.27
Stackable - Gutenberg Blocks: by Gambit Technologies
Inc – 2.11.4

Woo Align Buttons: by 320up – 3.6.5 – Installed version not tested with active version of WooCommerce 4.7.0
WOOBE - WooCommerce Bulk Editor and Products Manager: by realmag777 – 1.0.6.2
WooCommerce Conditional Payment Methods: by WP Super Admins – 1.9.0
WooCommerce Admin: by WooCommerce – 1.6.3 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce EU VAT Assistant: by Aelia – 1.14.13.201103
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.24 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Product SKU Generator: by SkyVerge – 2.4.5 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Shipping & Tax: by Automattic – 1.25.2 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Table Rate Shipping Pro: by PluginHive – 3.2.4 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce: by Automattic – 4.7.0
Wordfence Security: by Wordfence – 7.4.12
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO Premium: by Team Yoast – 15.2.1 – Installed version not tested with active version of WooCommerce 4.7.0
WP Google Maps - Pro Add-on: by WP Google Maps – 7.11.69
WP Google Maps: by WP Google Maps – 8.0.26
WP Review Slider Pro (Premium): by LJ Apps – 11.0.9.2
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.3
WPForms Lite: by WPForms – 1.6.3.1
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.5.7

Yoast SEO: WooCommerce: by Team Yoast – 13.7 – Installed version not tested with active version of WooCommerce 4.7.0

### Inactive Plugins (1) ###

takepayments WooCommerce Integration: by takepayments – 2.2.5 – Installed version not tested with active version of WooCommerce 4.7.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Must Use Plugins (3) ###

1&1 Product Subdomain: by 1&1 – 1.1.0
Health Check Troubleshooting Mode: by  – 1.7.2
Security by CleanTalk: Must-Use Module: by CleanTalk Security – 2.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7 - /shop
Basket: #10280 - /basket
Checkout: #9 - /checkout
My account: #10 - /my-account
Terms and conditions: #2438 - /legal

### Theme ###

Name: Trusted Pro
Version: 1.7.2
Author URL: https://uxlthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: trusted-pro/woocommerce/loop/loop-start.php

### Action Scheduler ###

Complete: 6,695
Oldest: 2020-10-14 11:40:27 +0000
Newest: 2020-11-13 20:15:01 +0000

Failed: 1
Oldest: –
Newest: –

Pending: 5
Oldest: 2020-11-13 20:21:42 +0000
Newest: 2020-11-14 14:59:22 +0000

`

11-13-2020 @ 20:17:10 - Response
Response
code: 400
message: Bad Request
headers: Array
(
    [x-app-usage] => {"call_count":7,"total_cputime":0,"total_time":1}
    [content-type] => application/json; charset=UTF-8
    [facebook-api-version] => v6.0
    [x-fb-request-id] => A-1bESwXmeEug77oWywAeey
    [strict-transport-security] => max-age=15552000; preload
    [x-fb-trace-id] => EYmOuESh3pN
    [x-fb-rev] => 1002975895
    [cache-control] => no-store
    [pragma] => no-cache
    [access-control-allow-origin] => *
    [expires] => Sat, 01 Jan 2000 00:00:00 GMT
    [www-authenticate] => OAuth "Facebook Platform" "invalid_request" "(#33) This object does not exist or does not support this action"
    [x-fb-debug] => WmLvYBFgJZJdSlZ5uWNao0Vu42YrLo3oHdBdTOuS2aEmlgweZziuEB0k1XXI6MpS1QA5TmoLVgPun8hKJMrOhw==
    [date] => Fri, 13 Nov 2020 20:17:10 GMT
    [alt-svc] => h3-29=":443"; ma=3600,h3-27=":443"; ma=3600
    [content-length] => 161
)
body: {"error":{"message":"(#33) This object does not exist or does not support this action","type":"OAuthException","code":33,"fbtrace_id":"A-1bESwXmeEug77oWywAeey"}}

11-13-2020 @ 20:17:10 - Request
Request
uri: https://graph.facebook.com/v2.9/697459017672695/log_events
body: Array
(
    [message] => {"message":"Failed to get AYMT tip info via API.","object":{"response":{"headers":{},"body":"{\"error\":{\"message\":\"(#33) This object does not exist or does not support this action\",\"type\":\"OAuthException\",\"code\":33,\"fbtrace_id\":\"A-1bESwXmeEug77oWywAeey\"}}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}},"error_type":"Non-200 error code from FB","plugin_version":"2.1.4","php_version":"7.4.12"}}
    [error] => 1
)
headers: Array
(
    [Authorization] => *****************************************************************************************************************************************************************************************************************************
)
timeout: 500
method: POST

11-13-2020 @ 20:17:10 - Response
Response
code: 400
message: Bad Request
headers: Array
(
    [access-control-allow-origin] => *
    [x-app-usage] => {"call_count":7,"total_cputime":0,"total_time":1}
    [x-fb-request-id] => AvH5hzkN8sWidLv2QORAzDj
    [strict-transport-security] => max-age=15552000; preload
    [x-fb-trace-id] => AIU92cV/AjK
    [facebook-api-version] => v6.0
    [content-type] => application/json; charset=UTF-8
    [x-fb-rev] => 1002975895
    [cache-control] => no-store
    [pragma] => no-cache
    [expires] => Sat, 01 Jan 2000 00:00:00 GMT
    [www-authenticate] => OAuth "Facebook Platform" "invalid_request" "(#33) This object does not exist or does not support this action"
    [x-fb-debug] => +91OG47KbHrFwxeXRy1uBHOP9k621kgOJwRnfEthXwC8DmNawc/tmarIgwec/CcjmS5xpJ5O+4Adqpu2GA215g==
    [date] => Fri, 13 Nov 2020 20:17:10 GMT
    [alt-svc] => h3-29=":443"; ma=3600,h3-27=":443"; ma=3600
    [content-length] => 161
)
body: {"error":{"message":"(#33) This object does not exist or does not support this action","type":"OAuthException","code":33,"fbtrace_id":"AvH5hzkN8sWidLv2QORAzDj"}}

**Comment by pettreegnat** [comment]
I have the same issue when certain plugins are enabled with the facebook-for woocommerce plugin.  Yoast, Rankmath, Paypal for woocommerce and multipayments by angelleye as an example of ones I noticed issues with.  This has been going on for a while now.

**Comment by PatoPC** [comment]
Hi I have the same issue:
I have WooCommerce version 4.7.0
WordPress version 5.5.3
MySQL 5.7.23-23
PHP 7.3.24
When the plugin is disabled, into the section edit/create product the fields for input information show correctly like you can see in the image:


![facebookActivate](https://user-images.githubusercontent.com/14806765/99906833-4264e080-2ca7-11eb-8ba7-55c1b077a4eb.png)
![errorFacebookPlugin](https://user-images.githubusercontent.com/14806765/99906835-42fd7700-2ca7-11eb-9951-3661aafa760f.png)

**Comment by PatoPC** [comment]
And the error continues in new version
![NuevaVersion](https://user-images.githubusercontent.com/14806765/99906870-7cce7d80-2ca7-11eb-92de-eda5f369344e.png)

**Comment by sydneytheartist** [comment]
I have this problem too, has anyone found any resolve to this?

**Comment by pettreegnat** [comment]
Just to disable it...

**Comment by basselenab** [comment]
Same issue as well. When can we expect a fix to this ??

**Comment by sayantandas** [comment]
+1

**Comment by basselenab** [comment]
Any news ?

**Comment by ggortan** [comment]
I'm having the same problem

**Comment by danielbitzer** [comment]
It looks like this issue is very similar to a memory exhaustion problem we fixed in #1853 and released in 2.4.0.

Please let us know if the issue persists after updating to 2.4.0. Closing for now.
