### ISSUE TITLE
 Variable products 

### ISSUE THREAD

**Issue by badgesonboard** [woocommerce/facebook-for-woocommerce#1702]
My variable products seem to be split on my facebook shop - I would rather have them as one product with the lowest price showing -how can I do this please ?

**Comment by haszari** [comment]
Thanks for reporting @badgesonboard. Can you give us more details of exactly how your product & variations are set up, and what you see in Facebook catalogue? 

Here's an example product from my test store - a shirt with two size variations, and the same products synced to Facebook. The screenshot shows the details for the large variation. 

<img width="1570" alt="Screen Shot 2021-03-23 at 8 10 38 PM" src="https://user-images.githubusercontent.com/4167300/112107503-e342b880-8c13-11eb-92b6-55866ffd4147.png">
<img width="1593" alt="Screen Shot 2021-03-23 at 8 11 42 PM" src="https://user-images.githubusercontent.com/4167300/112107571-feadc380-8c13-11eb-8ee8-39a5892ec7bb.png">

**Comment by budzanowski** [comment]
Closing as we have not heard back from the Issue creator.
