### ISSUE TITLE
Roles problem

### ISSUE THREAD

**Issue by patrickadam** [woocommerce/facebook-for-woocommerce#1714]
After the last update, we can't edit products as 'Shop Manager'.After the last update I can no longer adjust products with the shop manager account. I have already tried to reconnect and reinstall the plugin.

It seems, when a connection is established, that the editing of products is no longer possible. How can we fix this?

**Comment by AashikP** [comment]
Another report in https://wordpress.org/support/topic/a-error-about-shop-manager-accounts/

**Comment by patrickadam** [comment]
Hi @AashikP,

But what's the solution?

**Comment by AashikP** [comment]
Hello @patrickadam 

> But what's the solution?

I do not have a solution yet, so I've flagged the other report on the forum here so that our developers can further investigate this.

**Comment by gezmenadam** [comment]
I have still same problem in my web sites on this date! Why they don't fix it?

**Comment by gabrielfilippi** [comment]
I'm having the same problem on my website, please look into this issue urgently.

**Comment by rawdreeg** [comment]
I was unable to reproduce this issue. I created a "Shop Manager" user, and I could add and edit products with no issues. This could be a plugin compatibility issue or an issue with the hosting provider. 

If you're still experiencing this issue, please open a support ticket on the [WordPress.org Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/).

If you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).
