### ISSUE TITLE
Woocommerce for Facebook Marketplace In Addition To Facebook Shop Creation

### ISSUE THREAD

**Issue by rebuys** [woocommerce/facebook-for-woocommerce#1735]
## Feature requests
Facebook now allows certain Facebook partners to List Business Ecommerce into Facebook Marketplace instead of just creating a Facebook Shop. 

Information from facebook is Here:  
https://www.facebook.com/business/help/2197639333799894?id=2427773070767892

The following information is found here:  https://www.facebook.com/business/help/1855394307892939?id=2427773070767892

List Ecommerce Inventory on Marketplace
These are the listing partners we work with to show ecommerce inventory on Marketplace. Ecommerce retailers should contact one of these partners to express interest in having inventory appear in Marketplace on Facebook:

adMixt
BigCommerce
CedCommerce
ChannelAdvisor
CommerceHub
DataCaciques
Feedonomics
Productsup
Quipt
ShipStation
Shopify
Zentail

If you have an idea for how we could improve Facebook for WooCommerce, please let us know by [contacting our support team](https://woocommerce.com/my-account/create-a-ticket/)! We'd love to learn more about the problem you're facing and how Facebook for WooCommerce could help solve it.

## Developers

We welcome your contributions. 🙌 Here are a few tips to help us work together:

- If you submit a new PR, please ensure the description explains why the change is needed, follows WordPress coding standards, is compatible with PHP 5.6, and contains a small changeset — PRs with massive changesets are likely to be rejected or asked for revisions, as they’re much harder to review for potential issues.
- If you’d like to propose a more substantial changeset, feel free to start a discussion of why and the proposed implementation in this issue! Giving our team a heads up increases the likelihood of changes being accepted quickly.
- Internet points are available for PRs that include test coverage! 🏆 💯 Especially failing + passing tests for bug fixes.

**Comment by haszari** [comment]
Hi there @rebuys - I'm not aware of any plans for supporting Facebook Marketplace in Facebook for WooCommerce. I'm closing this feature request for now.
