### ISSUE TITLE
Facing errors while installing plugin in wordpress

### ISSUE THREAD

**Issue by vijaysinghwarwal** [woocommerce/facebook-for-woocommerce#1741]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
I tried to install plugin in wordpress and faced fatal and illegal string offset errors.

## ✔️ Expected behavior
I use to work on facebook pixel a lot, this should not happen in this way. It use to install very smoothly.

![34d05d0f-e1f2-4b3f-90c8-9e614cf38043](https://user-images.githubusercontent.com/76710277/103247924-96da3a80-498e-11eb-8ccf-5710a25b7b5c.png)

**Comment by jconroy** [comment]
Hi @vijaysinghwarwal 

Sorry to hear of your difficulties - what version of the plugin where you running? What version of WordPress, WooCommerce and PHP?

I haven't seen other reports of this.

**Comment by haszari** [comment]
Closing – we haven't had any other reports of this or any follow up. I'm not aware of any similar issue.
