### ISSUE TITLE
large actions table results in non-performant query

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/facebook-for-woocommerce#1796]
## 🔎 Isolate the bug

- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Reported in 3801136-zen that the query that runs on the init hook to `schedule_feed_generation` runs on every page load and ads 3-4 seconds of load time.

The site does have several subscriptions - the system status report shows a total of ~15k and the scheduled actions table seems to reflect that as well.

##🚶‍♀️ Steps to reproduce

## ✔️ Expected behavior
That the query needn't run on every page load

**Comment by glagonikas** [comment]
To add to my initial request
1. This was on Version 2.3.1 but 2.3.2 doesn't mention anything related on the changelogs
2. This affects any user role, not just admins.
3. On a busy website, it generates a huge number of queries that have the potential to break the site. Disabling the plugin makes a huge difference. (in our case, our page load went from 15s to 2s during a promo)

**Comment by glagonikas** [comment]
Adding an index on the actionscheduler table as following should resolve the issue, but [it's not a key that ships with actionscheduler](https://github.com/woocommerce/action-scheduler/blob/master/classes/schema/ActionScheduler_StoreSchema.php#L52-L58) and I'm unsure if this plugin should be responsible for creating it.

Ideally, you should consider the less invasive option of not calling this query if it's not necessary.

```
ALTER TABLE `wp_actionscheduler_actions` ADD INDEX `hook,status` (`hook`, `status`); 
```

**Comment by haszari** [comment]
See also related request - increase default feed regeneration interval #1882 .

**Comment by danielbitzer** [comment]
I have 41,204 scheduled actions on my site and the query is taking `0.0007s`. However, I tend to agree that checking the feed action is scheduled on every request isn't ideal.

<img width="1329" alt="Screen Shot 2021-04-16 at 11 30 18 am" src="https://user-images.githubusercontent.com/1892137/114960920-29073f80-9ea7-11eb-8943-f329be499496.png">

**Comment by glagonikas** [comment]
Hi @danielbitzer the query times you report are considerably different to what we get and I wonder how you managed to get such a performant database?

Our actionscheduler_actions table currently has 1m records and 730Mb, which is obviously a lot more than yours and with the index added, the query runs in `0.062s`, but without it, we experienced massive query times. This is on a powerful dedicated database server with the latest MariaDB and Redis.

Where is your database hosted (dedicated server or cloud?) and what are the server specs? can you share your `my.ini` in case you have some tweaks that we could use? Is it MySQL or MariaDB and what version? Do you use any type of query caching?

p.s. if I'm not mistaken, the number of records on the table have increased significantly since we reported this, due to AutomateWoo

**Comment by danielbitzer** [comment]
@glagonikas this test was on my local dev site. 

Ahh I see 1m action records is quite a lot! Completed actions should delete after 30 days. Is that happening on your site?

Yep AutomateWoo creates a lot of actions since needs to do a lot of background processing. 

You must have a site traffic site. Can you share the URL and how many products, orders and AW workflows you have?

**Comment by glagonikas** [comment]
@danielbitzer Yes, the actions are deleted correctly, but we have a busy site with Subscriptions and we started testing AW. We don't actually have any workflows live at the moment, but we do capture abandoned carts so AW works in the background.

As Peter confirmed here https://github.com/woocommerce/action-scheduler/issues/530#issuecomment-808300595 running queries on a remote site, performs differently, especially when it's a multi-server setup (like ours).

He couldn't reproduce the deadlocks we reported until he tried on a remote server.

So this would explain why you see such fast queries and ours is so much slower (without the index).

**Comment by danielbitzer** [comment]
Ahh thanks for linking that other issue. Interesting discussion happening over there.

What kind of query times do you see running the following query?

```
SELECT a.action_id
FROM wp_actionscheduler_actions a
WHERE 1=1
AND a.hook='wc_facebook_regenerate_feed'
AND a.status IN ('in-progress', 'pending')
LIMIT 0, 1
```

**Comment by glagonikas** [comment]
With the index in place, both queries run at around 0.06-0.07 sec. 

We're quite busy and I can't remove the index, so to ignore it, I modified your query and run it as
```
SELECT SQL_NO_CACHE
a.action_id
FROM wp_actionscheduler_actions a
IGNORE INDEX (`hook, status`)
WHERE 1=1
AND a.hook='wc_facebook_regenerate_feed'
AND a.status IN ('in-progress', 'pending')
LIMIT 0, 1

Duration for 1 query: 0.109 sec.
```

**Comment by danielbitzer** [comment]
Thanks for that! 

I'm thinking we should introduce a more efficient version of the `as_next_scheduled_action()` that uses a single query to check whether an event is scheduled. `as_next_scheduled_action()` will usually perform 3 queries which is completely unnecessary for this use case. We can also remove the order by `ORDER BY scheduled_date_gmt` which should speed things up.

The other option is we could temporarily cache the value as an WP transient.

How does that query above perform compared to the existing 3 queries that are currently used?

```
SELECT a.action_id
FROM wp_actionscheduler_actions a
WHERE a.hook='wc_facebook_regenerate_feed'
AND a.status='in-progress'
ORDER BY scheduled_date_gmt DESC
LIMIT 1
```

```
SELECT a.action_id
FROM wp_actionscheduler_actions a
WHERE a.hook='wc_facebook_regenerate_feed'
AND a.status='pending'
ORDER BY scheduled_date_gmt ASC
LIMIT 1
```

```
SELECT a.*, g.slug AS `group`
FROM wp_actionscheduler_actions a
LEFT JOIN wp_actionscheduler_groups g
ON a.group_id=g.group_id
WHERE a.action_id= {%SOME ACTION ID%}
```

**Comment by glagonikas** [comment]
```
SELECT SQL_NO_CACHE a.action_id
FROM wp_actionscheduler_actions a
IGNORE INDEX (`hook, status`)
WHERE a.hook='wc_facebook_regenerate_feed'
AND a.status='pending'
ORDER BY scheduled_date_gmt ASC
LIMIT 1

Duration for 1 query: 2.110 sec.
```

The other two are fast.

**Comment by danielbitzer** [comment]
Ok so that's much slower. That must be because of to the `ORDER BY scheduled_date_gmt` clause.

Here's my proposed PR: https://github.com/woocommerce/action-scheduler/pull/688

**Comment by glagonikas** [comment]
correct. without the `ORDER BY`, it runs at just 0.07 sec
