### ISSUE TITLE
FATAL ERROR in Google Product Category in woocommerce products

### ISSUE THREAD

**Issue by nygaardc** [woocommerce/facebook-for-woocommerce#1804]
FATAL ERROR occurs when facebook-for-woocommerce plugin is active and I choose the Google Product Category: Media->Books->Printed Books

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
![fatal-error](https://user-images.githubusercontent.com/80683455/111143094-b2181780-8585-11eb-8f09-168f5611ebe0.jpg)

When I activate facebook for woocommerce and edit my product google category, I get a FATAL ERROR.

It is no longer possible for me to sync this product to facebook. And it is not possible to revert back.

##🚶‍♀️ Steps to reproduce
1. Download facebook for woocommerce
2. Edit your product
3. Choose facebook tab and select Google product category.

## ✔️ Expected behavior
I expected that the plugin would allow me to choose google product category without crashing.

## 🗃 Logs

The Woocommerce test page shows all ok.
![status_1](https://user-images.githubusercontent.com/80683455/111144075-dde7cd00-8586-11eb-8e43-195a77393815.jpg)
![status_2](https://user-images.githubusercontent.com/80683455/111144101-e50edb00-8586-11eb-84b4-1a5d93449e23.jpg)

## Possible solution
If I uninstall facebook for woocommerce plugin, the Facebook options are no longer available in the product screen. Therefore no PHP fatal error. BUT then I cannot use the plugin to sync my products. So it's a catch 22.

HOW CAN I SOLVE THIS?

Any ideas are much appreciated. Thanks a lot.

**Comment by budzanowski** [comment]
I have replicated this on the latest ver. Investigating further.

**Comment by budzanowski** [comment]
Dev Note:
Attributes specification is missing from the Google Product Category to Attributes mapping. The majority of the categories are OK but I have identified a small subset ( 155 items ) of categories that would experience the same error:
[cat_mappings_missing.txt](https://github.com/facebookincubator/facebook-for-woocommerce/files/6142666/cat_mappings_missing.txt)

**Comment by nygaardc** [comment]
Wow, thanks for investigating, budzanowski.

Is there any workaround, I can use? 

After triggering the error, I cannot get rid of the PHP error. It seems to have "bugged" the Facebook option in the products, for which I chose the product category.

**Comment by budzanowski** [comment]
For now, I would just recreate this product and just set the Media > Books without adding the third level. We need to figure out what is the proper course of action for this type of issue.

**Comment by nygaardc** [comment]
Thanks, yes that's a workaround. However, my product is high ranked on SEO, the first page on Google for its keyphrase, so I would prefer not to have to change the URL and lose backlinks if URL is changed. I'll report back to you how it goes. Thanks again.

**Comment by budzanowski** [comment]
Sure, we are working on making the full categories work, that is just a temporary workaround.
