### ISSUE TITLE
Improve support for diagnosing connection issues - show errors mode

### ISSUE THREAD

**Issue by haszari** [woocommerce/facebook-for-woocommerce#1805]
Sometimes the initial connection between the Woo plugin and Facebook fails, with cryptic errors like `Something went wrong`. It might be useful to add an option to log or display more error info to help diagnose what's causing the problem. 

Previously there was an alternative connect server with more logging enabled. This is no longer available; the goal of this issue is to meet that need, i.e. expose more details about connection errors so merchants and support team can easily resolve connection problems.

### Possible solution
- Add an option to plugin e.g. `show errors` or `log errors`. This could be activated via UI, or via code (e.g. filter or wp options). Or potentially just always log errors by default if practical.
- When this option is set, pass it to connect server.
- In connect server, if option is present, capture and return any errors to site.
- Plugin logs or displays errors in site admin UI (could use `WooCommerce > Status > Logs`).

related: 118-gh-Automattic/connect.woocommerce.com

**Comment by haszari** [comment]
There is already a `Debug mode` so perhaps we can couple this to that setting to keep the UI simple.

<img width="832" alt="Screen Shot 2021-03-19 at 10 21 15 AM" src="https://user-images.githubusercontent.com/4167300/111699386-eac53300-889c-11eb-89f1-537ffeea335f.png">

**Comment by haszari** [comment]
Getting more visibility on connection errors might help address these issues: #1697 #1710 #1711

**Comment by soufianejayden** [comment]
hello support sorry for any bother but i have the same  while connection woocomerce with facebook  it show me this message take a look screenshoot

 
![bandicam 2021-07-23 17-28-57-775](https://user-images.githubusercontent.com/82966385/126821063-25c9119d-2e52-43bf-b3ff-39a17f58e774.jpg)
