### ISSUE TITLE
Temporarily disable full sync on 2.3.3 upgrade

### ISSUE THREAD

**Issue by haszari** [woocommerce/facebook-for-woocommerce#1842]
We've had reports (#1839) of full product sync (triggered by 2.3.3 upgrade - #1808) causing issues, especially on sites with large product catalogue.

This revealed a performance issue with product sync code that could affect any full sync (e.g. triggered manually from UI, generating product feed file). In the medium term we are looking at how to improve full sync - #1841. Some sites have disabled Facebook for WooCommerce; the goal is to ensure it's safe for those large sites to upgrade and re-enable Facebook for WooCommerce.

In the short term we need to disable the risky full sync to prevent this from impacting sites. Note this will likely be temporary until we have a more robust full sync.

**Comment by haszari** [comment]
Looking back to 2.3.3 release, it was understood that we needed to sync all products as part of updating the plugin. If we disable that due to performance concern, I'd like to understand any sync / functionality implications. 

@denniskwon  Can you comment on this - if we disable full sync on update, how will that affect product attribute syncing? Can you give an example of how this would affect a site's catalogue on Facebook? Thank you!

**Comment by denniskwon** [comment]
@haszari - The main reason to force the full sync was to apply the other attribute related changes shipped as part of 2.3.3. If the full sync does not happen, it means any already synced products (presumably most of the products in an update scenario) would not be synced again, until they are edited. As such, all of those products may be missing values for attributes sync as color, size, etc.

**Comment by budzanowski** [comment]
Closed with #1844.
