### ISSUE TITLE
Wrong `Value` Field in AddToCart Events 

### ISSUE THREAD

**Issue by abashinfection** [woocommerce/facebook-for-woocommerce#1847]
Hello, 

I recently noticed an unexpected behavior related to AddToCart events. 
When triggering multiple AddToCart events from a website, the `value` field contains a cumulative sum of all the previous AddToCart events. 
Based on my understanding, this is due to the following [code](https://github.com/woocommerce/facebook-for-woocommerce/blob/77f964b075aed4fd060cc39db1e7a780c8bfdf8c/facebook-commerce-events-tracker.php#L572):

```php
$product = wc_get_product( $variation_id ?: $product_id );

// bail if invalid product or error
if ( ! $product instanceof \WC_Product ) {
	return;
}
$event_data = [
	'event_name'  => 'AddToCart',
	'custom_data' => [
		'content_ids'  => $this->get_cart_content_ids(),
		'content_name' => $this->get_cart_content_names(),
		'content_type' => 'product',
		'contents'     => $this->get_cart_contents(),
		'value'        => $this->get_cart_total(),
		'currency'     => get_woocommerce_currency(),
	],
	'user_data' => $this->pixel->get_user_info(),
];
```

As per [Facebook documentation](https://developers.facebook.com/docs/facebook-pixel/reference#standard-events), in the case of AddToCart event we have: 
- `value`: The value of a user performing this event to the business.
- `currency`: The currency for the `value` specified.

It seems to me that the actual value for the `value` field should be the **price of the single product, not the cart total**.

This has a significant impact on multiple tools in the Facebook Business Manager platform. 
For example, when monitoring campaign metrics the total value for AddToCart events is much higher than the actual value in WooCommerce carts. 
This is because each new AddToCart event contains the cumulative sum of prices of all products in the cart:
- _First AddToCart_ event: 1 product, value=_X_
- _Second AddToCart_ event: 2 products in cart, value=_X+Y_
- _Third AddToCart_ event: 3 products in cart, value=_X+Y+Z_

The metrics shown by Facebook will sum the value for all the AddToCart events received: 
- _First AddToCart_ + _Second AddToCart_ + _Third AddToCart_ = (_X_) + (_X+Y_) + (_X+Y+Z_)
While the actual metric should simply be _X+Y+Z_. 

In a similar way, also the fields `content_ids` and `content_name` should be only relative to the single product being added to the cart, not the whole cart contents. 

I believe this is not the expected behavior, since metrics reported by Facebook are way off, but I might be wrong.
Can someone please provide some feedback on this issue? 

Thank you.

**Comment by abashinfection** [comment]
I believe this issue was mentioned in #1212 as well.

**Comment by abashinfection** [comment]
Found an interesting piece of information in [Facebook docs](https://developers.facebook.com/docs/facebook-pixel/implementation/pixel-for-collaborative-ads#parameters): 

|Property Key |	Value Type      | Parameter Description                                                                                   |
|:-----------:|:---------------:|---------------------------------------------------------------------------------------------------------|
|value        |integer or float | Value of a user performing this event to the business.<ul><li>For ViewContent, the value of an item.</li><li><b>For AddToCart, the value of new items added to cart at once. It's not the current total basket value.</b></li><li>For Purchase, the total basket value, including other fees, such as shipping fee and tax.</li></ul>|

**Comment by abashinfection** [comment]
I had a look at FacebookIncubator's [Facebook Pixel for Wordpress](https://github.com/facebookincubator/Facebook-Pixel-for-Wordpress) plug-in and noticed they [implement](https://github.com/facebookincubator/Facebook-Pixel-for-Wordpress/blob/master/integration/FacebookWordpressWooCommerce.php#L234) AddToCart event by setting `value` parameter as the `price * quantity` of new items added to the cart:
```php
private static function getAddToCartValue($cart_item, $quantity) {
    if (!empty($cart_item)) {
      $price = $cart_item['line_total'] / $cart_item['quantity'];
      return $quantity * $price;
    }

    return null;
  }
```

**Comment by abashinfection** [comment]
You can also find a [very similar implementation](http://plugins.svn.wordpress.org/pixel-caffeine/tags/2.3.3/includes/supports/class-aepc-woocommerce-addon-support.php) in the Pixel Caffeine third-party plug-in:
```php
protected function get_add_to_cart_params( $product_id = null, $quantity = 1 ) {
    if ( empty( $product_id ) && null !== WC()->session && ! empty( WC()->session->aepc_last_product_added_to_cart ) ) {
	    $product_id = (int) WC()->session->aepc_last_product_added_to_cart;
	    unset( WC()->session->aepc_last_product_added_to_cart );
    }
    
    $product = wc_get_product( $product_id );
    
    if ( empty( $product ) ) {
	    return array();
    }
    
    return array(
	    'content_type'     => 'product',
	    'content_ids'      => array( $this->maybe_sku( (int) $product_id ) ),
	    'content_category' => AEPC_Pixel_Scripts::content_category_list( (int) $product_id ),
	    'value'            => (float) $product->get_price() * $quantity,
	    'currency'         => get_woocommerce_currency(),
	    'event_id'         => WC()->cart->get_cart_hash(),
	    'unique'           => true,
    );
}
```

I do have a website with Pixel Caffeine installed instead of Facebook For WooCommerce and the proper cart value is reflected in Facebook Business Manager statistics and campaign metrics.

**Comment by danielbitzer** [comment]
Thanks for the detailed report and for your patience @abashinfection! This definitely seems like a bug based on the info provided.

**Comment by abashinfection** [comment]
Thank you @danielbitzer, please let me know if I can help with anything.

**Comment by lewicki-pk** [comment]
Hi @danielbitzer and @haszari 
Has this been fixed?
I'm using version 2.5.1 and still observing this issue.

What's more - when a client goes to checkout, chooses the shipment method with value X and then goes back to the product archive and adds something more to his cart- the value in AddToCart is equal to value of all items in cart + X (shipment cost).

Can I fix that somehow myself before you release the fix?

**Comment by haszari** [comment]
Hi @lewicki-pk 👋 

> Has this been fixed?

No - there's no fix for this yet.

> Can I fix that somehow myself before you release the fix?

Feel free to open a PR if you have a fix for this or any other issue impacting your store. Thank you 🙇
