### ISSUE TITLE
Facebook for Woocommerce critical failure after the latest update

### ISSUE THREAD

**Issue by sreejithmahesan1** [woocommerce/facebook-for-woocommerce#1850]
Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Facebook for WooCommerce.

“There has been a critical error on this website.

Learn more about troubleshooting WordPress.”

Your Facebook page URL :  https://www.facebook.com/picksparrow123/
Your website URL:  https://picksparrow.com/
Current version of Facebook-for-WooCommerce: Version 2.3.4
WooCommerce :Version 4.8.0
 WordPress :WordPress 5.7 running Astra theme.
PHP

**Comment by erikrdana** [comment]
I've had the same issue!

Had to deactivate the plugin.

**Comment by pau1phi11ips** [comment]
Same, had to deactivated the plugin

**Comment by isaariel** [comment]
I have the same issue, also had to deactivate the plugin. Don't know how to proceed now, wait for next update?

**Comment by erikrdana** [comment]
I've updated Wordpress and Woocommerce and it's working now!

**Comment by budzanowski** [comment]
Closing in favor of #1849
