### ISSUE TITLE
opt.tag

### ISSUE THREAD

**Issue by roberttiller** [woocommerce/facebook-for-woocommerce#1858]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by roberttiller** [comment]
ok

**Comment by danielbitzer** [comment]
Looks like spam
