### ISSUE TITLE
BUG REPORT: Plugin storing data in _options table is taking sites down

### ISSUE THREAD

**Issue by GldnKey** [woocommerce/facebook-for-woocommerce#1859]
Since we have installed this plugin we have noticed a **significant load increase** and more recently the site being going down at least once a day.  

Upon investigation it appears that your plugin is storing data in a way that is considered a bad practice and causes issues with sites - in the _options table.

We would like a fix to store the date in your own table or a setting that would allow the plugin to work without storing the date in the _options table. 

Please advise.

Thank you!

**Comment by haszari** [comment]
Thanks for the report @GldnKey  !

Can you give us some more specific details so we understand the problem and how it affects your sites? Please be as specific as possible, the more detail we have the better.

- Tell us more about the problematic row(s) in options table. What are the keys? How many rows? Does this increase with num products or is it constant?
- How is this causing the site to go down?

Thank you 😃

**Comment by GldnKey** [comment]
I can't give you more specific details regarding the tables but what it
does is overpowers the site, causes extreme bloat, and then crashes the
site aka takes it down.  The long and the short of it is that on both sites
this is on if there are any other processes running with it then it pushes
the resource level to a point that even on our high level dreampress site
it causes it to go down.  I will see if I can get more info from our host
to report but that is all I have right now.


--

<https://www.goldenkeypartnership.com/>

OFFICE HOURS: Monday - Friday | 11:00 a.m. - 6:00 p.m. CST | Please allow
up to 1 full business day for reply.

ᐧ
ᐧ

**Comment by haszari** [comment]
Thanks @GldnKey. There are some improvements in progress here - see #1853 #1840 for example.

**Comment by GldnKey** [comment]
Thanks for those updates but that doesn't solve the problem of the fact
that you guys are storing all the data in the _options table instead of its
own table is a BAD practice and causing a lot of issues with the sites
where this is being used.

Does that make sense?

Thanks!

Lauren


--

<https://www.goldenkeypartnership.com/>

OFFICE HOURS: Monday - Friday | 11:00 a.m. - 6:00 p.m. CST | Please allow
up to 1 full business day for reply.

ᐧ

**Comment by haszari** [comment]
> but that doesn't solve the problem of the fact
that you guys are storing all the data in the _options table instead of its
own table is a BAD practice and causing a lot of issues with the sites
where this is being used

We're going to need more specific details to resolve this. When you have more details of what specific database rows/options specifically are causing issues with your sites, please let us know.

**Comment by danielbitzer** [comment]
@GldnKey I'm guessing you're referring to the `wc_facebook_google_product_categories` option and `wc_facebook_google_product_categories` transient which are very large and stored in the options table. I have good news for you! In our next release (2.3.6) we will be removing these options and using a different storage mechanism.

**Comment by GldnKey** [comment]
YES! I think this is exactly what we are talking about!  Yay! When will
that be released?  This is a DIRE need for us from a stability standpoint.

Thank you Daniel!


--

<https://www.goldenkeypartnership.com/>

OFFICE HOURS: Monday - Friday | 11:00 a.m. - 6:00 p.m. CST | Please allow
up to 1 full business day for reply.

ᐧ

**Comment by danielbitzer** [comment]
@GldnKey we will be publishing a RC version and starting a call for testing today. The public release will be mid-next-week. You may wish to use the the RC version when it becomes available but I'd recommend testing it on a non-live store before using it on your live store.

**Comment by danielbitzer** [comment]
Here is the pre-release version: https://github.com/woocommerce/facebook-for-woocommerce/releases/tag/2.4.0-rc.1

**Comment by danielbitzer** [comment]
Closing as this was fixed by #1810 to be be released in 2.4.0.
