### ISSUE TITLE
`Get Started` connection button opens in new tab, leaving orphaned extra tab

### ISSUE THREAD

**Issue by haszari** [woocommerce/facebook-for-woocommerce#1863]
## ✍️ Describe the bug
The `Get Started` button opens a new tab by default (`target="_blank"`). When the connection flow completes, the redirect back to Woo dashboard uses the same tab, leaving a redundant WP dashboard tab open. 

<img width="976" alt="Screen Shot 2021-04-08 at 12 38 47 PM" src="https://user-images.githubusercontent.com/4167300/113951735-45ccc300-9868-11eb-991a-0d1bd4efbf02.png">

Not a major but might be simpler to not force new tab (user can always cmd/ctrl-click or right click to open separate tab). cc @j111q - do we have guidelines in Woo/WP for when to use new tab?

If we do decide to keep the new tab behaviour, consider adding an "external link" icon to the button to indicate it will launch a new tab (and on a separate domain).

## 🚶‍♀️ Steps to reproduce
1. Start with a disconnected Facebook for WooCommerce plugin.
2. Go to `WooCommerce > Marketing > Facebook`.
3. Click `Get Started` and connect site.

At the end of the connection flow, you have an extra (stale) tab in "disconnected" state.

## ✔️ Expected behavior
Use same tab for simplicity and to avoid stale UI state.

**Comment by j111q** [comment]
Yes +1, we shouldn't open in a new tab here! Good catch @haszari.

**Comment by haszari** [comment]
Nice quick win - https://github.com/woocommerce/facebook-for-woocommerce/pull/1885
