### ISSUE TITLE
Update documentation with FB setup requirements and debug information for connection

### ISSUE THREAD

**Issue by rcstr** [woocommerce/facebook-for-woocommerce#1867]
### Description
As part of #1805 we want to update the [documentation](https://docs.woocommerce.com/document/facebook-for-woocommerce/) and include:

- Setup information, this can include a checklist and necessary requirements for FB account/page to be used.
- Include common errors when connecting to FB (and how to proceed? what to do?)

**Comment by haszari** [comment]
Some of the UI text and notice messages have changed - #1822 #1861

Specifically, we now use `Disconnect` where previously used ~~`Uninstall`~~.

**Comment by rcstr** [comment]
Closing this. Docs published on https://docs.woocommerce.com/document/facebook-for-woocommerce/troubleshooting-connection-errors
