### ISSUE TITLE
Add filter to change connect.woocommerce.com URL

### ISSUE THREAD

**Issue by rcstr** [woocommerce/facebook-for-woocommerce#1868]
### Description
In order to make development and testing more convenient, we want to add a filter(s) to change the URL for `connect.woocommerce.com` instances.

### Context
> Let's add a filter to the Facebook plugin to make this more convenient for development/testing.  - @haszari

**Comment by rawdreeg** [comment]
This filter exists as `wc_facebook_connection_proxy_url`. See:

https://github.com/woocommerce/facebook-for-woocommerce/blob/80f4fa9ad313d4c967e5caee86f984bc2e2f9d55/includes/Handlers/Connection.php#L827
