### ISSUE TITLE
Nested actions are lost when tracking a purchase

### ISSUE THREAD

**Issue by anant1811** [woocommerce/facebook-for-woocommerce#1870]
Ticket: 3885097-zd
Slack discussion: https://a8c.slack.com/archives/C7U3Y3VMY/p1617977672327700

User mentioned:

Issue with tracking pixel where upon purchase the tread of actions is reset.
e.g. the current path is:
page view > view content > add to basket > checkout

Then it resets and all the nested actions are lost and a new thread is started for 'purchase'
Where as it need to be :
page view > view content > add to basket > checkout > purchase

So all the actions are logged under the same thread.

Is this something you are aware of? Is this how its set up to work?
I've tested this with only the facebook / woocommerce plugin active and on 2017 theme
We have a screenshot in the ticket with a note
>That is to confirm your store is correctly connected to your Facebook catalog. Next step I'll check out with the developers about the PATH structure.
Is this something for you all to weigh in on, or should this be escalated to Facebook?

**Comment by rawdreeg** [comment]
I checked this. And this is how it works. Sometimes, receiving payment confirmation may take a long time, and we do not hold the action thread on that particular event. I will close this, but you're welcome to re-open with suggestions if needed.
