### ISSUE TITLE
Add setting that allows enabling/disabling feed file generation.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/facebook-for-woocommerce#1873]
For some of the sites feed file is unnecessary. Besides it not being used it can slow down the site and cause performance issues. We need to add a setting that allows disabling the feed file generation. We also need to add a documentation section that explains when the feed file should be used.﻿

**Comment by haszari** [comment]
To clarify some more context here:

- There are two mechanisms for sync implemented in this plugin - feed (FB pull) and batch API (Woo push). 
- The feed approach is no longer recommended in favour of the batch API, which allows incremental updates. Batch API is used by default.
- It's possible to configure Facebook to pull from the feed file, and some existing sites may still be using it.
- The feed file is generated on all sites, even if it's not needed.
- The feed file includes all products, so can be expensive to generate and transmit (CPU/bandwidth).

So we're proposing adding an setting to disable, so sites that don't need the feed file can disable it.

**Comment by haszari** [comment]
Update: after discussion with WooCommerce and Facebook developers, we've confirmed that the feed-based sync is still an important component and will need to be maintained. 

Specifically:

- Both sync mechanisms are an important part of syncing the store from Woo => Facebook.
- Feed is used for periodic update of full catalogue and inventory. There are some performance/scaling implications which we're looking at.
- Batch API is used to incrementally update products as they are edited. 

@budzanowski I'm closing this in favour of reducing the feed generation interval (#1882) and ongoing work to optimise for larger stores.

**Comment by haszari** [comment]
Reopening.

Although feed is an important part of product sync, the current implementation may cause issues for larger stores. We're working on improving feed code so it's reliable for all stores.

In the mean time, it would be useful for larger stores to have the option to disable the feed, or specifically disable the existing/legacy feed code.

**Comment by haszari** [comment]
Related issue: #1871
