### ISSUE TITLE
Low quality of events matching reported by Facebook ads

### ISSUE THREAD

**Issue by unster** [woocommerce/facebook-for-woocommerce#1878]
Hi team,

I am experiencing low quality of event matching reported by Facebook ads. It is happening for quite a time, but so far it didn't affected my ads performance. Now it seems that has changed...

Currently using version 2.3.5.

Some screenshots from my ads panel:
https://i.ibb.co/yVmSyg0/matching-q1.jpg
https://i.ibb.co/RPMFg50/add-to-cart1.jpg

Those factors has lowest numbers: Postal Code & Click ID (fbc)

**Comment by unster** [comment]
Hi, just wanted to ask if there is a chance to get update regarding the issue. It is expected behavior or is it the real issue?

**Comment by danielboos1** [comment]
Any update regarding this?
