### ISSUE TITLE
Add filter for hidden products

### ISSUE THREAD

**Issue by jcastro91** [woocommerce/facebook-for-woocommerce#1879]
Right now, by default, any hidden product in the catalog is also not synced in Facebook.

I believe we can add a filter for this in `includes/Products.php` line 240, so we can bypass this setting. Or if we want to bypass this setting by only the varations.

# Use Case

* If I want a product hidden in my store, but not hidden in my Facebook Catalog.

Right now, for example, I'm using Woocommerce Show Multiple Variations and for that plugin to no show duplicates, I need to set my variable products as Hidden in my store, but I want them to appear (or at least their variations) in the Facebook catalog.

**Comment by MatiasSchefer** [comment]
Hola Jorge, cómo estás? Asumo que hablas español, quería consultarte si has dado con la solución para sortear este obstáculo, ya que tengo el mismo inconveniente, estoy utilizando un plugin similar al tuyo para mostrar las variaciones como productos individuales en la tienda, ocultando el producto padre, y de este modo he perdido los productos en el catálogo de facebook.

Te agradecería mucho si tienés un segundo para comentármelo. Saludos!

**Comment by rawdreeg** [comment]
Hi both,

You should be able to modify the visibility index value by using the `facebook_for_woocommerce_integration_prepare_product`:

https://github.com/woocommerce/facebook-for-woocommerce/blob/08b2d371f2c2c69af0838bda27be7783171ab33f/includes/fbproduct.php#L661-L665

The full `$product_data` array is passed to the filter.

**Comment by rawdreeg** [comment]
closed based on the previous reply.
