### ISSUE TITLE
Implement feed generation using WooCoommerce CSV generation class.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/facebook-for-woocommerce#1901]

**Comment by WPprodigy** [comment]
Just wanted to add a quick note here about some performance concerns.

Currently, `write_product_feed_file()` does one file write call per product row. On hosts that support multiple web containers (VIP Go for example), or have read-only filesystems, file writes like this will each result in a remote request. This quickly adds up as we're talking thousands of rows. Some options:

1) Batch multiple rows together before performing a file write.
2) Write to a tmp file in `get_temp_dir()`, and then push the final result to `/wp-uploads/final-place` when complete. Note that the tmp file is not guaranteed to be present across multiple separate requests though.

**Comment by haszari** [comment]
Thanks for those insights @WPprodigy!

**Comment by budzanowski** [comment]
We are not using WooCommerce CSV for this anymore.
