### ISSUE TITLE
vulnerability found on Official Facebook Pixel v2.2.0

### ISSUE THREAD

**Issue by pranavmtn** [woocommerce/facebook-for-woocommerce#1905]
## 🔎 Isolate the bug
Facebook for WordPress < 3.0.0 - PHP Object Injection with POP Chain 

 I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

**Comment by haszari** [comment]
This issue affects a different plugin - [Facebook for WordPress](https://wordpress.org/plugins/official-facebook-pixel/). This repository is for [Facebook for WooCommerce](https://wordpress.org/plugins/facebook-for-woocommerce/). Note also that the report refers to an older (not current) version of Facebook for WordPress (< 3.0.0, current is 3.0.5). Closing this issue.
