### ISSUE TITLE
Set a minimum required PHP version

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/facebook-for-woocommerce#1907]
This was originally discussed in https://github.com/woocommerce/facebook-for-woocommerce/issues/1906

## Reasoning:

We should define a minimum required PHP version so we all know what language features we can utilize. We also want to make it easier for users by not triggering fatal errors on sites that use old PHP versions. Instead, we want to fail gracefully when encountering an incompatible version of PHP.

I believe we should use PHP 7.0 to align with WooCommerce core and WC Admin.

## Implementation:

Initially I thought the best implementation would be to "define a minimum Woo version and inherit the min PHP version from that Woo version".

However, after some more investigation, I think we should use the `Requires PHP` WordPress plugin header since this is a WordPress.org hosted plugin. This is also what WooCommerce core and WC Admin uses. A handy feature of this header is that incompatible sites will be prevented from updating the plugin and shown a warning (I couldn't find any docs for this). 

More on the `Requires PHP` header:
- https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/
- https://core.trac.wordpress.org/ticket/40934
- https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

**Comment by haszari** [comment]
> I believe we should use PHP 7.0 to align with WooCommerce core and WC Admin.

This makes sense to me - and we should get this in place as soon as we can. However .. we may need to stage it since some of our users are on older versions. Perhaps we can promote the change in a release or two (inbox messages, admin notices and any other way we can communicate with users) before setting the requirement. 

We can also investigate what versions of the plugin customers are using, and ensure that we don't negatively impact that - don't want to increase in merchants running older versions.

> `Requires PHP` WordPress plugin header

Sounds ideal. If we want to confirm the behaviour we can do some tests with environments running old PHP and see what happens.

**Comment by danielbitzer** [comment]
Given the lack of reports about the incompatible PHP 7.1 code in #1906 I think we have room to make the change in 2.5.0. 

> Perhaps we can promote the change in a release or two (inbox messages, admin notices and any other way we can communicate with users) before setting the requirement.

I don't agree that this is necessary. The native WP notice that checks the **Requires PHP** header (see screenshot) is timely and contextual for the user when they attempt to update a plugin. Triggering inbox messages and admin notices that, lets be honest, often get ignored seems like less effective solution. Not to mention it will require more time to implement.

<img width="1370" alt="Screen Shot 2021-04-29 at 10 32 53 am" src="https://user-images.githubusercontent.com/1892137/116490362-5526b580-a8d6-11eb-92bf-4c6a2dd124e4.png">

Also I'm fairly sure that sites running < 7.0 will not be able to receive inbox notifications since WooCommerce Admin won't be available.

**Comment by haszari** [comment]
> I don't agree that this is necessary. The native WP notice that checks the Requires PHP header (see screenshot) is timely and contextual for the user when they attempt to update a plugin. Triggering inbox messages and admin notices that, lets be honest, often get ignored seems like less effective solution. Not to mention it will require more time to implement.

Fair - I'm not saying we have to stage the change or add notices - just that we consider the impact. Adding notices is indeed quite crude, and not necessarily effective - that was just a suggestion ("perhaps") for something we could do to smooth over the change.

The main thing is that we do everything we can to ensure more merchants are running the latest version (whatever form that takes). I.e. this risk is what I'm worried about:

> We can also investigate what versions of the plugin customers are using, and ensure that we don't negatively impact that - don't want to increase in merchants running older versions.
