### ISSUE TITLE
Attribute values with commas break product sync

### ISSUE THREAD

**Issue by slaxxarn** [woocommerce/facebook-for-woocommerce#1909]
## 🔎 Isolate the bug

- [ x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

We have comma ‘,’ in our attribute values and by looking at the source code for the plugin (facebook-for-woocommerce/includes/Products/Sync/Background.php line 299 to 304) you guys do an implode on attributes by comma sign to convert all attributes to a string for “additional_variant_attribute”. This breaks our import by, i guess, on facebooks end, explode by comma sign aswell.

An example how are attribute values are written: processor:1,8 GHz Fyrk\u00e4rnig Core i7 so the whole additional_variant_attribute becomes

"additional_variant_attribute":"bildskarm:HD 1920x1080,processor:1,8 GHz Fyrk\u00e4rnig Core i7,minne:16GB RAM,4g-cellular:Med 4G Cellular,lagring:512GB SSD"

##🚶‍♀️ Steps to reproduce

1. Create a variable product with attribute values that has comma in them ie "1,8 Ghz Four core i7"
2. Try to sync that product

## ✔️ Expected behavior
Sync it to facebook

## 🗃 Logs

`{"message":"Den additional_variant_attribute informationen under  \u00e4r ogiltig. Granska f\u00f6r mer information"}`

**Comment by budzanowski** [comment]
@slaxxarn thank you for the bug report and the investigation. We will look into this.

**Comment by slaxxarn** [comment]
> @slaxxarn thank you for the bug report and the investigation. We will look into this.

Great, thanks!

A new filter to handle this or just escaping comma signs would be enough

**Comment by haszari** [comment]
Hi there @slaxxarn  - can you add some more details of exactly how to reproduce the issue?

I tried adding an attribute value with a comma to a product (`Color: "Blue, ocean, aquamarine, sky, duck-egg"`), and it synched correctly as far as I can tell.

<img width="1086" alt="Screen Shot 2021-04-29 at 12 03 28 PM" src="https://user-images.githubusercontent.com/4167300/116486949-ea2fab80-a8e2-11eb-92ec-220762d11a7b.png">
<img width="969" alt="Screen Shot 2021-04-29 at 12 03 46 PM" src="https://user-images.githubusercontent.com/4167300/116486976-016e9900-a8e3-11eb-8405-bcc18c30fd56.png">

**Comment by slaxxarn** [comment]
> Hi there @slaxxarn - can you add some more details of exactly how to reproduce the issue?
> 
> I tried adding an attribute value with a comma to a product (`Color: "Blue, ocean, aquamarine, sky, duck-egg"`), and it synched correctly as far as I can tell.
> 
> <img alt="Screen Shot 2021-04-29 at 12 03 28 PM" width="1086" src="https://user-images.githubusercontent.com/4167300/116486949-ea2fab80-a8e2-11eb-92ec-220762d11a7b.png">
> 
> <img alt="Screen Shot 2021-04-29 at 12 03 46 PM" width="969" src="https://user-images.githubusercontent.com/4167300/116486976-016e9900-a8e3-11eb-8405-bcc18c30fd56.png">
> 
> I'm guessing this issue affects specific types of products or attributes - can you help us narrow down the issue? Thank you!

I just did some tests with like "Red, green blue" and it worked just fine, but adding the following:
![bild](https://user-images.githubusercontent.com/15977552/116505224-a45eed00-a8ba-11eb-92aa-a64ab353f9f6.png)

Only the value with the dot got imported
![bild](https://user-images.githubusercontent.com/15977552/116505277-c0fb2500-a8ba-11eb-9ae0-ce6dab4ed3cc.png)

Could it be some sort och length issue?

**Comment by slaxxarn** [comment]
This also worked

![Firefox_Screenshot_2021-04-29T05-18-47 151Z](https://user-images.githubusercontent.com/15977552/116505523-6e6e3880-a8bb-11eb-8fc2-dc50f997898b.png)

----

![Firefox_Screenshot_2021-04-29T05-20-26 082Z](https://user-images.githubusercontent.com/15977552/116505533-74641980-a8bb-11eb-866e-0b281a391576.png)

----

![bild](https://user-images.githubusercontent.com/15977552/116505549-80e87200-a8bb-11eb-9b68-83ddfcc999c6.png)

![bild](https://user-images.githubusercontent.com/15977552/116505608-9e1d4080-a8bb-11eb-8ef2-ab88a064ca19.png)



But not the one with processor "2,6 GHz sexkärnig core i7"

**Comment by slaxxarn** [comment]
This works aswell 

![bild](https://user-images.githubusercontent.com/15977552/116505924-65ca3200-a8bc-11eb-8a2c-58b1f00d5cb6.png)

**Comment by budzanowski** [comment]
@slaxxarn, thank you for the additional details.

It will be hard to solve this issue in a way that would satisfy all parties.

Comma works in attributes of type: size, color, pattern, or gender. Other types of attributes need to go into `additional_variant_attribute`. The format for `additional_variant_attribute` is different compared to the attributes that I have listed at the beginning. For those attributes, a comma is not a problem. For things that go inside the `additional_variant_attribute` comma can't really be supported. According to how Facebook has specified this field this should be a comma-separated list of `attribute_name: atttribute_value,`  this means that comma is an essential part of the field structure and can't be used. We will need to escape the field for the `,` symbol, and we will probably provide a filter that would allow merchants to select what should be used instead of a comma.

This means that 2,6Ghz is not possible but 2.6Ghz is.

I have asked Facebook for additional information regarding this but I doubt that there is anything that can be done at this stage except replace the commas with something.

**Comment by slaxxarn** [comment]
> @slaxxarn, thank you for the additional details.
> 
> It will be hard to solve this issue in a way that would satisfy all parties.
> 
> Comma works in attributes of type: size, color, pattern, or gender. Other types of attributes need to go into `additional_variant_attribute`. The format for `additional_variant_attribute` is different compared to the attributes that I have listed at the beginning. For those attributes, a comma is not a problem. For things that go inside the `additional_variant_attribute` comma can't really be supported. According to how Facebook has specified this field this should be a comma-separated list of `attribute_name: atttribute_value,` this means that comma is an essential part of the field structure and can't be used. We will need to escape the field for the `,` symbol, and we will probably provide a filter that would allow merchants to select what should be used instead of a comma.
> 
> This means that 2,6Ghz is not possible but 2.6Ghz is.
> 
> I have asked Facebook for additional information regarding this but I doubt that there is anything that can be done at this stage except replace the commas with something.

Thanks for the reply. So, i need to create a filter in the source code to handle this myself, and then wait for a new relase with this change from your side. I could also make a PR for you guys but it's quite a minor change.

**Comment by budzanowski** [comment]
@slaxxarn
Adding the code for this is not the problem. We can do that quickly. What we are waiting for is a reply from Facebook if there is something that we can do to allow commas or what would be the best approach for this. Maybe there is a way that we can escape the comma that would preserve it on the Facebook side. We will keep this Issue up to date with what we will find.

If it is even possible then avoiding commas in the lists like this:
![image](https://user-images.githubusercontent.com/17271089/116852963-8d3f3880-abf5-11eb-8c7d-5d6355269e93.png)
it would allow all of the items to go through. I understand that this can not be possible to go and change everything if you have a large catalog of items. I will ping the Facebook team again and check if they have some news for me.

**Comment by slaxxarn** [comment]
> @slaxxarn
> Adding the code for this is not the problem. We can do that quickly. What we are waiting for is a reply from Facebook if there is something that we can do to allow commas or what would be the best approach for this. Maybe there is a way that we can escape the comma that would preserve it on the Facebook side. We will keep this Issue up to date with what we will find.
> 
> If it is even possible then avoiding commas in the lists like this:
> ![image](https://user-images.githubusercontent.com/17271089/116852963-8d3f3880-abf5-11eb-8c7d-5d6355269e93.png)
> it would allow all of the items to go through. I understand that this can not be possible to go and change everything if you have a large catalog of items. I will ping the Facebook team again and check if they have some news for me.

Ok great! It just dumb of us to use comma for this, but we have hundreds of variations that has this in the attribute value, so it would be alot of work to replace it. :(

**Comment by budzanowski** [comment]
This will be addressed in #1922 ( currently under review ).

**Comment by slaxxarn** [comment]
Hi!

@budzanowski thanks you fixing this, do you know when the release 2.5 will be out?
