### ISSUE TITLE
Fatal error `is_search()` with custom page / query

### ISSUE THREAD

**Issue by jnz31** [woocommerce/facebook-for-woocommerce#1936]
- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Fatal error: Uncaught Error: Call to a member function is_search() on bool in /xxx/wp-includes/query.php:703 Stack trace: #0 /xxx/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php(378): is_search() #1 /xxx/wp-includes/class-wp-hook.php(292): WC_Facebookcommerce_EventsTracker->inject_search_event(Object(WP_Query)) #2 /xxx/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #3 /xxx/wp-includes/plugin.php(551): WP_Hook->do_action(Array) #4 /xxx/wp-includes/class-wp-query.php(1784): do_action_ref_array('pre_get_posts', Array) #5 /xxx/wp-includes/class-wp-qu in /xxx/wp-includes/query.php on line 703

## 🚶‍♀️ Steps to reproduce
i have a custom page for sale items, where i take the "normal" `$wc_query` and add taxonomy (f.ex. sale/women) and `'post__in' => wc_get_product_ids_on_sale()`. it is based on woocommerce's `archive-product.php`.

here is my tax_query
```
global $wp_query, $language;
$tax_query = WC()->query->get_tax_query();

if (array_key_exists('product_cat', $wp_query->query)) :
    $term = explode('/', $wp_query->query['product_cat']);
    if ((is_array($term) && array_key_exists(0, $term) && $term[0] != 'page')) :
        $tax_query[] = [
            'taxonomy' => 'product_cat',
            'field' => 'slug',
            'terms' => $term[0]
        ];
    endif;
else :
    $term = 'all';
endif;
```

meta_query (only show in-stock items)
```
$meta_query = WC()->query->get_meta_query();
$meta_query[] = [
    'key' => '_stock_status',
    'value' => 'instock'
];
```

...custom query:
```
$args = [
        'post_status' => 'publish',
        'post_type' => 'product',
        'meta_query' => $meta_query,
        'tax_query' => $tax_query,
        'post__in' => wc_get_product_ids_on_sale(),
        'posts_per_page' => 59,
        'orderby' => 'menu_order title',
        'order' => 'ASC',
        'paged' => $paged
];
$wp_query = new WP_Query($args);
```

## ✔️ Expected behavior
this is new behavior (client pointed me to the failing sale page on friday), it worked with no issues before (> 6 month), so not sure, what causes this issue.

i now uncommented the contents of `inject_search_event()` and it works for me. 

i attached my template file, the is a function called `jnz_output_category_navigation()`. it is not related to this issue.
[page-sale.php.zip](https://github.com/woocommerce/facebook-for-woocommerce/files/6450350/page-sale.php.zip)

**Comment by budzanowski** [comment]
> i now uncommented the contents of inject_search_event() and it works for me.

Do you want to say that it started to work again?

**Comment by jnz31** [comment]
ciao haszari

i boiled it down a little further: you inject `inject_search_event` via `add_action('pre_get_posts', [$this, 'inject_search_event']);` so it runs pre query. and inside `inject_search_event` you call `is_search()`. thing is: these condintional tags do not work (always return false) since the query did not even run, yet. so this at least throws a php notice. i removed that action, since its save to say: `if ( ! is_admin() && is_search() && '' !== get_search_query() && 'product' === get_query_var( 'post_type' ) )` === always false

**Comment by jnz31** [comment]
here is another solution, also involving the use of the `$query` argument:

```
        public function inject_search_event($query)
        {

            if (is_admin() || !$query->is_main_query()) {
                return;
            }

            if (!$this->is_pixel_enabled()) {
                return;
            }

            if (is_search() && '' !== get_search_query() && 'product' === get_query_var('post_type')) {

                if ($this->pixel->is_last_event('Search')) {
                    return;
                }

                // needs to run before wc_template_redirect, normally hooked with priority 10
                add_action('template_redirect', [$this, 'send_search_event'], 5);
                add_action('woocommerce_before_shop_loop', [$this, 'actually_inject_search_event']);
            }
        }
```

**Comment by haszari** [comment]
Aha, thanks for digging @jnz31 !

**Comment by melek** [comment]
@jnz31 also shared this error in a [post on the .org support forum](https://wordpress.org/support/topic/fatal-error-uncaught-error-call-to-a-member-function-is_search-on-bool/) with a streamlined description of the fix which may be useful here as well:

> inside `facebook-commerce-events-tracker.php` i changed
`public function inject_search_event() {` to `public function inject_search_event($query) {`, and  
`if ( ! $this->is_pixel_enabled() ) {` to `if ( ! $this->is_pixel_enabled() || ! $query->is_main_query() ) {`  to solve the issue.

**Comment by jnz31** [comment]
yo? can someone implement this easy fix plz?!
