### ISSUE TITLE
Syncing leaves useless `wc_facebook_background_product_sync_job` rows in options table.

### ISSUE THREAD

**Issue by melek** [woocommerce/facebook-for-woocommerce#1943]
## 🔎 Isolate the bug
@budzanowski was able to confirm and isolate the error along with a proposed fix in PR #1940. 

## ✍️ Describe the bug
"After the Background Batch API job is completed the option that was used as the control structure for the process remains in the options table. We have no use for it."

This error resulted in a forum user having thousands of unneeded `wc_facebook_background_product_sync_job` rows in their database's options table: https://wordpress.org/support/topic/wc_facebook_background_product_sync_job/

Every background sync job [adds an option to wp_options table with job data, metadata and status info](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/utilities/class-sv-wp-background-job-handler.php#L402). These options are not cleaned up automatically, so they accumulate over time.

This is likely a performance / database size issue on many stores. The job data includes a list of products to update. So for larger stores with many products, the options will be larger. Because these options accumulate over time, longer-lived stores will have more redundant job rows in their database.

## 🚶‍♀️ Steps to reproduce
Surmised from PR: 
1. Open the options table in the DB and look for `wc_facebook_background_product_sync_job_%` where % is a number
2. Start the Sync, wait till the end,
3. Observe that the new/existing `wc_facebook_background_product_sync_job_%` options were not removed, leading to the accumulation of rows.

Since @budzanowski reproduced this bug and already filed a PR, I have not personally tested these steps.

## ✔️ Expected behavior
There should not be unused, leftover rows once the sync job is completed.

## 🗃 Logs
None at this time.

**Comment by haszari** [comment]
Edit: Added some more info to description about the issue and possible impact/scaling implications.

**Comment by haszari** [comment]
Shifted this to 2.6 based on discussion in #1940. Although this is important and somewhat serious, it's not a new issue, so we shouldn't rush to include in 2.5. If we get a safe fix implemented soon we can reconsider including in 2.5.

**Comment by haszari** [comment]
Assigned to me :) I'll use the new heartbeat event (#1953) to add a job to cleanup `wc_facebook_background_product_sync_job` options in batches, using Action Scheduler framework from #1913.

FYI @budzanowski @danielbitzer
