### ISSUE TITLE
Remove language file from the repository.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/facebook-for-woocommerce#1954]
The .pot file is generated during the release process. It should not live in the repository. This is the standard approach among the plugins. Having the .pot file bloats the history.

Remove it.

**Comment by haszari** [comment]
GNU agrees: (option 2) https://www.gnu.org/software/gettext/manual/html_node/Translations-under-Version-Control.html

**Comment by haszari** [comment]
And WooCommerce core: https://github.com/woocommerce/woocommerce/blob/trunk/.gitignore#L76

**Comment by rawdreeg** [comment]
closed by #2303
