### ISSUE TITLE
Switch to Jetpack autoloader

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/facebook-for-woocommerce#1956]
Because we are going ahead with using a separate [Action Scheduler Job Framework package](https://github.com/woocommerce/action-scheduler-job-framework) we need to ensure that the latest version of the package is loaded into WordPress which Jetpack Autoloader does.

**Comment by haszari** [comment]
Also Jetpack Autoloader is the standard used in WooCommerce Core and many other WooCommerce extensions.

- https://github.com/woocommerce/woocommerce/blob/trunk/composer.json#L17
- https://github.com/woocommerce/woocommerce/blob/master/packages/README.md

**Comment by haszari** [comment]
As I understand it, this is an essential part of shipping #1924 (feed engine revamp), because it uses the job framework. That's now shifted to 2.7, so shifting this alongside.
