### ISSUE TITLE
`const VERSION` not being updated by `woorelease`

### ISSUE THREAD

**Issue by rcstr** [woocommerce/facebook-for-woocommerce#1958]
## Description
[_woorelease_](https://github.com/woocommerce/woorelease) allows to define the plugin version in the [code in multiple ways](https://github.com/woocommerce/woorelease#defined-constants) but this bump will apply only to [main plugin file](https://github.com/woocommerce/woorelease/blob/df17b7948d829cfa64b732d81948ce06a60afcd1/includes/command/class-versionbump-change.php#L90), on our case `facebook-for-woocommerce.php` file but we are defining the version in `class-wc-facebookcommerce.php` file so the bump doesn't happen.

Should we move the `VERSION` const to `facebook-for-woocommerce.php` instead?

Follow up from #1947

**Comment by danielbitzer** [comment]
Good catch! I've moved the version constant in the main plugin file in 422d695514b2dda86a2e8a4f74641606a179ba4f.

**Comment by danielbitzer** [comment]
Fixed by 422d695514b2dda86a2e8a4f74641606a179ba4f, PR merged.
