### ISSUE TITLE
WooCommerce Catalog Visibility - limited visibility settings results in Do Not Sync for Facebook, regardless of product settings

### ISSUE THREAD

**Issue by jessLundie** [woocommerce/facebook-for-woocommerce#1961]
- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Question

When WooCommerce catalog visibility for a product is set to any setting other than *Shop and Search results*, products do not sync to Facebook regardless of what is set in the individual product settings for sync.

Is this a bug or working as intended? Enhancement request? Technical limitation of what Facebook needs to see product data for the sync? 

Reported in 3951632-zen.

## 🚶‍♀️ Steps to reproduce

1. Create a product
2. Set Facebook settings on that product to *Sync and show in catalogue*: https://d.pr/i/3O0GUC
3. Set WC Catalog Visibility settings to *Hidden*: https://d.pr/i/ji3F98
4. In the products list (and in product behavior), see that the product is set to *Do Not Sync* and the product does not sync:
![https://d.pr/i/XNFbmT](https://d.pr/i/XNFbmT+)
Full Image: https://d.pr/i/XNFbmT

**Comment by danielbitzer** [comment]
@jessLundie this is intentional and is implemented by these lines here:

https://github.com/woocommerce/facebook-for-woocommerce/blob/9b1a1dcb696fe4e1926b9f196b0375705fad4c41/includes/Products.php#L238-L241

The comment states `exclude products that are excluded from the store catalog or from search results`.

Do you think it should work differently?

**Comment by jessLundie** [comment]
Ah, thank you @danielbitzer! 

In this particular ticket the merchant has a number of simple products within a Grouped Product. The Grouped Product is set to visible and the simple products are set to hidden for WC display purposes. But, of course, they need all of them to sync to FB. 

In my opinion, since the Facebook plugin now has individual Sync / Do Not Sync options for products, I think the optimal functionality would be:

* Set all non-visible products to Do Not Sync on FB on install, to avoid unintentional syncing of Hidden products
* Have the individual Sync / Do Not Sync option allow merchants to change that as desired

Right now it's pretty confusing, as you can change that setting in the Product Data but then it's not reflected in the Products list or sync behavior. It ends up looking like something is broken with the settings save.

**Comment by jessLundie** [comment]
Also reported in https://wordpress.org/support/topic/sync-issue-7/

**Comment by haszari** [comment]
> Right now it's pretty confusing, as you can change that setting in the Product Data but then it's not reflected in the Products list or sync behavior. It ends up looking like something is broken with the settings save.

Thanks for clarifying @jessLundie. The user experience of the `Product sync` settings tab is not ideal, I find it confusing too. I think changes to settings apply to new products - I think of it as defaults. Something that might be worth looking at in future.

**Comment by haszari** [comment]
> In my opinion, since the Facebook plugin now has individual Sync / Do Not Sync options for products, I think the optimal functionality would be:
> - Set all non-visible products to Do Not Sync on FB on install, to avoid unintentional syncing of Hidden products
> - Have the individual Sync / Do Not Sync option allow merchants to change that as desired

@jessLundie  - feel free to log an issue (enhancement) for this specific improvement, or repurpose this issue 😄

**Comment by danielbitzer** [comment]
> The user experience of the Product sync settings tab is not ideal

👆 this

**Comment by jessLundie** [comment]
Just to clarify, this issue wasn't referring to the Product Sync tab under **Marketing > Facebook > Settings**. 

These customers were referring to the actual individual product sync settings under Product > Product Data > Facebook:

![https://d.pr/i/dhsYJc](https://d.pr/i/dhsYJc+)
Full Image: https://d.pr/i/dhsYJc

Regardless of how you configure this setting, if the product catalog visibility is set to anything but *Shop and Search results*, the product does not sync.

I'm not sure about how the Product Sync tab interacts with the Product Data > Facebook tab settings, but I don't *think* that tab is related to this issue?

**Comment by danielbitzer** [comment]
Oh right, I slightly misread Rua's comment. I thought it was about the Facebook product tab. 

I think we need to revisit all of the sync rules which is becoming more possible in https://github.com/woocommerce/facebook-for-woocommerce/pull/1933. 

It sounds like the UI here and expected sync behavior needs revisiting. Especially the relationship between the **Facebook sync field** and the **Product visibility field**.

I see what you mean, the **Facebook sync field** should arguably override the value of the **Product visibility field**.

**Comment by haszari** [comment]
> Regardless of how you configure this setting, if the product catalog visibility is set to anything but Shop and Search results, the product does not sync.

I too was confused. Sounds like there may be some simpler improvements we could make to the product edit Facebook tab - thanks.

**Comment by jrick1229** [comment]
Very long chat that ended up being this issue: 31056926-hc

**Comment by HMSuperGeek** [comment]
Thanks Joey, but do you have a link to where that goes?

**Comment by jrick1229** [comment]
Sorry @HMSuperGeek - that's just internal reference and not relevant to any information that would help.

**Comment by thisissandip** [comment]
Another one: https://wordpress.org/support/topic/products-with-shop-only-visibility-do-not-sync/

**Comment by rawdreeg** [comment]
I reckon the first thing to do is update this [check](https://github.com/woocommerce/facebook-for-woocommerce/blob/3c2a42de5f8eb162984c243fad1f12952f994af9/includes/ProductSync/ProductValidator.php#L233-L235) which prevents products hidden in search and shown in catalog from syncing.

https://github.com/woocommerce/facebook-for-woocommerce/blob/3c2a42de5f8eb162984c243fad1f12952f994af9/includes/ProductSync/ProductValidator.php#L233-L235

Additionally, adding a simple message to the Channel Visibility meta box would help reduce the confusion though
