### ISSUE TITLE
Reset all Facebook settings. 

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/facebook-for-woocommerce#1963]
## Feature requests

I've seen several posts where manually removing values from the options table should resolve most connection issues. Can we get the following plugin included in Facebook for WooCommerce core which appears to do what's necessary?

https://d.pr/f/rTEhWp

This will add a new tool available at **WooCommerce > Status > Tools** called “Reset Facebook for WooCommerce settings“. 

## Developers

We welcome your contributions. 🙌 Here are a few tips to help us work together:

- If you submit a new PR, please ensure the description explains why the change is needed, follows WordPress coding standards, is compatible with PHP 5.6, and contains a small changeset — PRs with massive changesets are likely to be rejected or asked for revisions, as they’re much harder to review for potential issues.
- If you’d like to propose a more substantial changeset, feel free to start a discussion of why and the proposed implementation in this issue! Giving our team a heads up increases the likelihood of changes being accepted quickly.
- Internet points are available for PRs that include test coverage! 🏆 💯 Especially failing + passing tests for bug fixes.

**Comment by budzanowski** [comment]
The https://github.com/woocommerce/facebook-for-woocommerce/pull/1860 already deletes options when we click Disconnect. The info was added in the docs https://docs.woocommerce.com/document/facebook-for-woocommerce/troubleshooting-connection-errors/#other-errors.

Closing. @johndcoy if you think that this is not correct, please reopen  :)

**Comment by haszari** [comment]
See #1990 - there are some settings that aren't cleared out currently. It would be useful for troubleshooting to have a way to completely reset all settings. Note we may not want to add this to `Disconnect` – as some sites may need to disconnect + reconnect, and preserve various config options.
