### ISSUE TITLE
Delete and reset all products from Facebook

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/facebook-for-woocommerce#1964]
## Feature requests

It would be nice to have a “Delete all products from Facebook” tool that creates batches using the Action Scheduler. The expectation would be that the actions would delete the product from Facebook then remove all stored meta within the WooCommerce site for each product. 

This should be triggered automatically if a product is ever added to the trash.

Here is a link to a public script that is helpful:

https://docs.woocommerce.com/document/facebook-for-woocommerce/facebook-for-woocommerce-delete-or-reset-all-facebook-products/

## Developers

We welcome your contributions. 🙌 Here are a few tips to help us work together:

- If you submit a new PR, please ensure the description explains why the change is needed, follows WordPress coding standards, is compatible with PHP 5.6, and contains a small changeset — PRs with massive changesets are likely to be rejected or asked for revisions, as they’re much harder to review for potential issues.
- If you’d like to propose a more substantial changeset, feel free to start a discussion of why and the proposed implementation in this issue! Giving our team a heads up increases the likelihood of changes being accepted quickly.
- Internet points are available for PRs that include test coverage! 🏆 💯 Especially failing + passing tests for bug fixes.

**Comment by mitchellkrogza** [comment]
Wish I had found this sooner I just deleted my entire catalogue and am now resyncing https://github.com/woocommerce/facebook-for-woocommerce/issues/1987

**Comment by haszari** [comment]
Another way to delete or bulk-reset the catalogue is to use a feed file (data source) with a **replace schedule**: https://www.facebook.com/business/help/2284463181837648

> With Replace schedule, your new file completely overwrites all of the information in your previous file. It adds new items, updates existing items and deletes any items that aren't in the new file. Replace is the default if you set a schedule when you upload a new data feed file for the first time.

**Comment by mitchellkrogza** [comment]
> Another way to delete or bulk-reset the catalogue is to use a feed file (data source) with a **replace schedule**: https://www.facebook.com/business/help/2284463181837648
> 
> > With Replace schedule, your new file completely overwrites all of the information in your previous file. It adds new items, updates existing items and deletes any items that aren't in the new file. Replace is the default if you set a schedule when you upload a new data feed file for the first time.

Thanks @haszari I'll try this next time much easier

**Comment by namiokuzono** [comment]
Hello @haszari ! I referenced your comment to bulk delete the catalog for Facebook using Replace Schedule, but I am not able to complete this task. Did I miss something? It just adds new feeds like this: https://d.pr/i/PmBxAL (Product is indeed added when the feed is updated, but does not replace the whole catalog). As per the FB doc, it says it will delete any products that are no longer listed in the same/new file detected. 

> It adds new items, updates existing items and deletes any items that aren't in the new file.

**Comment by haszari** [comment]
> Hello @haszari ! I referenced your comment to bulk delete the catalog for Facebook using Replace Schedule, but I am not able to complete this task. Did I miss something?

I don't know sorry – I haven't actually tried this, that was an idea from the docs. Things may have changed too.

**Comment by haszari** [comment]
> Did I miss something? It just adds new feeds like this: https://d.pr/i/PmBxAL

<img width="451" alt="Screenshot on 2022-06-16 at 16-18-51" src="https://user-images.githubusercontent.com/4167300/174188919-673dd7a7-cb8a-4c6c-b62b-bc1330450c9d.png">


If you haven't already, make sure you delete all the other feed files in Facebook, and only add a single `Replace schedule` feed.

**Comment by chrism245** [comment]
36520332-zen

**Comment by budzanowski** [comment]
Closing this in favour of #2129. Deleting all products that are matching WC catalog is possible. Problem happens only when we have shadow products as described in #2129
