### ISSUE TITLE
Deprecated notices coming from wc_facebook_background_product_sync AJAX endpoint

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/facebook-for-woocommerce#1966]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Hello team,

Recently we fixed an bug in WooCommerce core and we deprecated `WC_Session_Handler::nonce_user_logged_out`, and the SkyVerge's plugin framework used in this extension is calling this deprecated function in an ajax request. I have already started an issue in the framework side: https://github.com/skyverge/wc-plugin-framework/issues/541

There's also some reports in wp.org: https://wordpress.org/support/topic/nonce_user_logged_out-function-is-deprecated/

## 🚶‍♀️ Steps to reproduce

1. Enable `WP_DEBUG` and `WP_DEBUG_DISPLAY`, see more in https://wordpress.org/support/article/debugging-in-wordpress/
2. Just still WooCommerce and Facebook for WooCommerce, also make all initial set up of the plugin.
3. While syncing products to Facebook note that there's some deprecated notices from `WC_Session_Handler::nonce_user_logged_out` coming from SkyVerge's plugin framework.

Note that's required to enable debugging in WP to see those messages, so not a huge bug or issue, probably could be just fine to advice users to disable PHP errors in production, anyway it's nice if we could patch it soon.

## ✔️ Expected behavior
No deprecated messages.

**Comment by haszari** [comment]
Adding this to 2.7 to get it out of the way if it's easy to fix. If not feel free to remove from milestone :)

**Comment by devonto** [comment]
Hello, any update on this? I'm seeing these messages in logs quite frequently and it'd be good to have it resolved.

**Comment by WillBrubaker** [comment]
Did this change make it into a release? I ask because I've got a ticket reporting the same thing. I don't see the changes from the PR above in my copy of 3.0.15.

**Comment by rawdreeg** [comment]
Thanks for reporting this @WillBrubaker 

The fix (#2411) for #1966 was mistakenly reverted in 87654696c5669a6e0e55a57bc04aec9832881528. I opened a new PR to fix the issue.
