### ISSUE TITLE
Please test with V5.7 of Wordpress

### ISSUE THREAD

**Issue by Viran09** [woocommerce/facebook-for-woocommerce#1969]
## 🔎 Isolate the bug

- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Feed constantly pulls items which are set to not sync to facebook. 

## 🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by haszari** [comment]
Closing - please reopen if there's a specific reproducible issue with Facebook for WooCommerce on WordPress 5.7.
