### ISSUE TITLE
Old Variations Are Not Deleted from Catalog

### ISSUE THREAD

**Issue by mitchellkrogza** [woocommerce/facebook-for-woocommerce#1987]
I have done a mass update on my woocommerce store over the past few weeks, this involved changing attribute names and variation names for all products. As you can see from the attached image some products have 114 variations when each product only actually has 44. Instead of the new data being synced and old data being deleted, Facebook is retaining all the old variations in addition to the new. It's either a horrible Facebook store bug (quite likely) or a problem with this plugin not correctly updating a product as it currently stands. Either way its really terrible for business. I cannot imagine how many people are clicking on a variation that no longer exists. 

I am now in the very painful process of deleting all products from the catalog (second time this year because of REF: https://github.com/woocommerce/facebook-for-woocommerce/issues/1803) 

Facebook unfortunately doesn't have a reset catalog option (not that I have found) so this very painful browser based deletion is simply great fun. When I am eventually finished deleting all products I have to then resync them all. In the interim clients can be lost and when the products resync they all have to go through the validation again before they appear.

![2021-06-03_10-04](https://user-images.githubusercontent.com/9961541/120611137-2612df00-c454-11eb-8242-b795d9cd7823.png)

Facebook says I have 122,900 variations when I actually only have 33,996
![2021-06-03_10-14](https://user-images.githubusercontent.com/9961541/120611603-a5a0ae00-c454-11eb-8517-6c5b8a7fda2c.png)
![2021-06-03_10-15](https://user-images.githubusercontent.com/9961541/120611622-a9343500-c454-11eb-9428-84185132cd4a.png)

**Comment by haszari** [comment]
Thanks for sharing your experience & use case @mitchellkrogza. I can understand that deleting or bulk-replacing the catalogue is a pain point right now.

We're working on improvements to ["data feed" product sync](https://www.facebook.com/business/help/1898524300466211) which might improve this in future. I'm curious - do you know if your site currently uses a product feed, or is the sync using the [Batch API](https://www.facebook.com/business/help/384041892421495?id=725943027795860)? 

In the meantime, you might also be able to fix up your catalogue by manually uploading a feed/catalogue file (CSV, XML or Google Sheets).

**Comment by mitchellkrogza** [comment]
> Thanks for sharing your experience & use case @mitchellkrogza. I can understand that deleting or bulk-replacing the catalogue is a pain point right now.
> 
> We're working on improvements to ["data feed" product sync](https://www.facebook.com/business/help/1898524300466211) which might improve this in future. I'm curious - do you know if your site currently uses a product feed, or is the sync using the [Batch API](https://www.facebook.com/business/help/384041892421495?id=725943027795860)?
> 
> In the meantime, you might also be able to fix up your catalogue by manually uploading a feed/catalogue file (CSV, XML or Google Sheets).

Hi @haszari I did find a way to delete the entire catalog and resync, took about 2-3 hours in all. It seems facebook is either retaining all the old product information or the plugin is not telling Facebook to delete them.

**Comment by GiannisRallis** [comment]
Hello i have an opened ticket also in facebook for woocomerce support on wordpress.org please check my logs here

https://wordpress.org/support/topic/same-product-double-time-with-different-id/?#post-14550643

**Comment by johndcoy** [comment]
We have an active conversation here. Closing to prevent multiple issues of the same problem. See #2129
