### ISSUE TITLE
Disconnect doesn't clear out all options

### ISSUE THREAD

**Issue by tijosh** [woocommerce/facebook-for-woocommerce#1990]
It appears that the `Disconnect` button doesn't always clear out all connection-related options. Example after disconnecting:

![Screenshot](https://d.pr/i/ZMxOZI+)
*Link to image: https://d.pr/i/ZMxOZI*

Context:
p1622555527247200-slack-C7U3Y3VMY

**Comment by haszari** [comment]
cc @johndcoy – I think you've seen similar reports, or related feedback about the previous SkyVerge "clear all settings" tool. Please add info here - thanks 🙇

**Comment by haszari** [comment]
Tentatively adding this to 2.7. If it's safe to bulk-delete settings automatically on disconnect, we can do that. Alternatively we could implement a hidden UI or CLI to clear things out, or clear settings in uninstall hook, or at a minimum document what settings to delete.

One thing to keep in mind – is it common to disconnect and reconnect _without_ wanting to clear out settings? E.g. merchant wants to reconnect to Facebook, but keep all the config and options in Woo the same. If we clear out everything on disconnect, it could be frustrating.

**Comment by haszari** [comment]
Noting a workaround for removing all settings manually:

- Delete all options with prefix `wc_facebook`.
- May also be some other option names containing `fb` (delete with care).

These options are in the database in the `wp_options` table, and can be accessed & deleted with [WP CLI](https://developer.wordpress.org/cli/commands/option/) or direct SQL queries. Please take care when deleting or editing option directly, especially on a production site.
