### ISSUE TITLE
Investigate where to disable the Batch API actions.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/facebook-for-woocommerce#2013]
Since the feed will be doing the heavy lifting for the product synchronization we will be able to reduce the reasons to trigger Batch API. Probably removing the mass Batch API sync actions would be the best thing to do and leave it just for the single product changes that need synchronization.

**Comment by haszari** [comment]
Thanks for logging this, could require some careful tweaking when the feed is working well.

**Comment by budzanowski** [comment]
Given how Facebook API operates it looks like we can't get rid of mass Batch API sync actions. Closing.
