### ISSUE TITLE
New deletion policy for non-empty product groups

### ISSUE THREAD

**Issue by jconroy** [woocommerce/facebook-for-woocommerce#2021]
Received June 12, 2021

> Starting on June 8, 2021, for API v11.0+, Facebook will no longer allow deletion of non-empty product groups by default. Non-empty product groups can be deleted by applying deletion_method=delete_items to the deletion request. This will delete both the product group and its items. The affected endpoint is ‘DELETED {product_group_id}’.

> After September 6, 2021, this change will be applied to all API versions. Please update your app to prepare for this change before this date.

[Learn More](https://developers.facebook.com/docs/graph-api/changelog/version11.0)

Initially will need an investigation to see what the impact is if any.

**Comment by haszari** [comment]
Tentatively added to 2.7, hopefully we can do a quick investigation and get this wrapped up.

**Comment by budzanowski** [comment]
Update to v11.0 has happened https://github.com/woocommerce/facebook-for-woocommerce/pull/2064 nearly one year ago, I assume that we can close this. If this would be a problem we would have seen this reported. Closing.
