### ISSUE TITLE
Use core Options API instead of direct DB writes

### ISSUE THREAD

**Issue by aidvu** [woocommerce/facebook-for-woocommerce#2023]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
The SkyVerge job framework is not using the [Options API](https://codex.wordpress.org/Options_API). It is writing directly to the DB, which disallows hosting providers to add some limitations that would break the hosting, or the site itself.

e.g. A site with millions of products is going to first write ~5MBs to the options table, then it's going to update it by adding/removing small chunks of data, but still writing ~5MBs every time. With some simple math, this is going to be over a terabyte after the first 200k rows.

I'd suggest either chunking these updates or completely changing how the sync works. It's better to have 1 million rows of specific easily queryable data, than one big chunk you have to `json_encode/decode` every time you want to make a change.

## 🚶‍♀️ Steps to reproduce

1. Generate a site with million of products
1. Run the full product sync

## ✔️ Expected behavior
Nothing breaks, or goes OOM, or writes terabytes of binary logs.

## 🗃 Logs

<details>
	
</details>

**Comment by haszari** [comment]
Tentatively added this to 2.7 – not sure if there's a quick safe way to improve this, but it's definitely a pain point. Thanks for reporting @aidvu.

Some notes about impact:

- The [`Products/Sync/Background`](https://github.com/woocommerce/facebook-for-woocommerce/blob/master/includes/Products/Sync/Background.php) class is used for on-demand full product sync using Batch API (as I understand it). This can be triggered from `Marketing > Facebook > Product sync > Sync products` button. 
- It's implemented on top of the SkyVerge job framework, which stores the job state in an option. 
- That state grows with the number of products.

Can reproduce this issue by setting up a site with many products, then triggering a full sync. This will generate large options rows for the job state, and as the number of products increases, the option gets larger.

**Comment by aidvu** [comment]
The problem isn't only the size of the row. It's consequent (small) updates which write the whole thing over and over with minor changes. 

As for a fix, maybe extend the class that updates the data, and override the methods to use the options api. I haven't really looked if it's possible.

**Comment by haszari** [comment]
Closing and removing from 2.6.1. We're going with a targeted feature flag to allow disable of full batch API background sync (to avoid the large-option/option churn issue).

Long term we need to move away from using the SkyVerge job framework and adopting Action Scheduler instead. Patching or optimising the existing system is not practical. We're better off investing that dev time in either migrating to Action Scheduler, improving feed-based sync, or a combination of both.
