### ISSUE TITLE
Facebook Product set only shows the one latest item with its variation in Facebook catalog

### ISSUE THREAD

**Issue by tzaroon** [woocommerce/facebook-for-woocommerce#2024]
I firstly create the Facebook product set in WordPress.
Then I add the items but it keeps showing the latest one only with its variation. I checked the catalog from facebook business. It was unable to retrieve the variations of the product also.
kindly provide a solution for that.

**Comment by wbshaw** [comment]
I have this same issue - details posted in https://github.com/woocommerce/facebook-for-woocommerce/issues/1993

**Comment by rawdreeg** [comment]
This issue has been solved by PR #2189
