### ISSUE TITLE
Use Feed sync instead of Background Sync on `handle_connect` event

### ISSUE THREAD

**Issue by rcstr** [woocommerce/facebook-for-woocommerce#2025]
The background batch-api sync uses the SkyVerge job framework, which updates an option (`wp_options` table) regularly as the job is processed. This job status option includes all product IDs that need to be synched.

In the case of the a full catalog sync, on a large store, this can cause performance issues and is generally a bad idea. The option is very large and is updated often, which may cause issues if database changes are logged (as they are on some hosts). 

The goal of this issue is to disable the use of the background sync for full catalog sync. There are at least two situations that do this: `Sync products` button in admin, and the initial full sync triggered after successful connection to Facebook (i.e. after onboarding).

See also related issues #2023 #2022 #2013

**Comment by haszari** [comment]
Removing this from 2.6.1 - we're going to provide a targeted feature flag to allow automated opt-out of full background sync.

In future we may look at switching the full sync mechanism from batch API to feed, but we need to prioritise that alongside all other product sync improvements (and may not be appropriate if we make batch API sync scale better). With that in mind, I'm closing this issue.
