### ISSUE TITLE
Sync with tickets form Events Calendar

### ISSUE THREAD

**Issue by AmyEdwards94** [woocommerce/facebook-for-woocommerce#2026]
Hi, I want to sync the tickets from the plugin "The Events calendar" with Facebook, I have the woocommerce FB plugin installed and the tickets have been generated as WooCommerce products, but whenever I set the ticket product to "sync and show in catalog" it automatically reverts back, how do I fix this please?

**Comment by haszari** [comment]
> Hi, I want to sync the tickets from the plugin "The Events calendar" with Facebook, I have the woocommerce FB plugin installed and the tickets have been generated as WooCommerce products, but whenever I set the ticket product to "sync and show in catalog" it automatically reverts back, how do I fix this please?

Facebook allows syncing of physical products only, so event tickets are not supported.

https://www.facebook.com/policies_center/commerce/

https://www.facebook.com/policies_center/commerce/events_or_admission_tickets
