### ISSUE TITLE
Remove scheduled background sync task

### ISSUE THREAD

**Issue by rcstr** [woocommerce/facebook-for-woocommerce#2029]
### Description
`SkyVerge\WooCommerce\Facebook\Products\Sync\Background` is used to schedule the background sync, with #2028 we will switch to feed file sync. So we need to unschedule the task from customer's sites and clean up the data (see `SkyVerge\WooCommerce\Facebook\Jobs\CleanupSkyvergeFrameworkJobOptions`)

**Comment by haszari** [comment]
Closing and removing from 2.6.1. 

- We're going with a targeted feature flag to allow disable of full batch API background sync.
- Any other improvements or changes to product sync overall can be looked at as part of ongoing work, we may or may not need what's requested in this issue.
