### ISSUE TITLE
Re-Sync connection impossible

### ISSUE THREAD

**Issue by RopsTeN** [woocommerce/facebook-for-woocommerce#2030]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Hello. i am facing an issue with Facebook for WooCommerce.
I have a website A that i created and configured etc... everything went well.
I created a copy file of this website A and gave it to friends so they can create a website B quickly and easily using this file copy.
The problem is that when they try to setup the Facebook for WooCommerce, it kept my old settings and connection.
When they click on "Get Started" button to connect with their Business Manager etc.. it directly send them to my Business Manager, and as they don't have access to it, they can't stop the connection with my Business Manager to theirs.

We are blocked, it seems that there is an issue of cache or something that kept my old Facebook Connexion and we can't locate it to reset it.

## 🚶‍♀️ Steps to reproduce

1 - Create a website A, install Facebook for WooCommerce, link it to your Facebook.
2 - Create a copy of this website A (using for example All-in-One WP Migration plugin)
3 - Create a new website B, install All-in-One WP Migration, import the copy of the website A
4 - Install Facebook for WooCommerce, and try to connect to another business manager.
--> They will ask you to connect to the Business Manager from the Website A. But if you are not the same person between the website A and B you will not have access to this Business Manager, so you will be blocked.

## ✔️ Expected behavior

It should allow them to choose a different Business Manager

## 🗃 Logs

<details>
	
</details>

**Comment by haszari** [comment]
Hi @RopsTeN - thanks for reporting this. We have a similar issue open - #1990 - so I'm going to close this.

If you need to manually reset all Facebook settings in WooCommerce, there's a workaround:

- Delete all options with prefix `wc_facebook`.
- May also be some other options containing `wc_fb`, delete with care.

You can delete options using WP CLI or direct from the database (`wp_options` table) if you're comfortable with that (and it's safe to do so on the site). Hope this helps! 

Please comment on #1990 if you have any other info or feedback about this issue. Thanks 🙂
