### ISSUE TITLE
Add feature flag that disables full background sync

### ISSUE THREAD

**Issue by rcstr** [woocommerce/facebook-for-woocommerce#2035]
### Description
We want to allow merchants to disabled all-products sync, this could work as an option that could be set up via `wp_options` table or filter.

This is the method that triggers all-products sync
https://github.com/woocommerce/facebook-for-woocommerce/blob/267f12275f3cf2537276862508dd21bfe38c39cc/includes/Products/Sync.php#L77-L85

**Comment by haszari** [comment]
I think this and #2033 are closely related (or same issue). Leaving open for now but will wrap up when PR etc is finalised.

**Comment by haszari** [comment]
Fixed by #2033 (not sure why this didn't close automatically). Closing :)
