### ISSUE TITLE
Plugin- Apresenta problemas de sincronização do catalogo de produto do site para o catalogo do FB 

### ISSUE THREAD

**Issue by Guidevfull** [woocommerce/facebook-for-woocommerce#2041]
O plugin não envia todos os produtos, como se tivesse uma falha de comunicação entre o FB e o plugin, não consegue indentificar o produto, fica dando uma mensagen de erro de view port content

**Comment by jconroy** [comment]
Hi @Guidevfull 

Thanks for posting and sorry for your difficulties. If you haven't done so please create a support request on woocommerce.com or a [new topic in the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for assistance.

Our happiness team will be better able to support you in those locations.
