### ISSUE TITLE
PHP Warning: array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by spangher** [woocommerce/facebook-for-woocommerce#2044]
## 🔎 Isolate the bug

- [ X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
PHP Warning: array_key_exists() expects parameter 2 to be array, null given in wp-content/plugins/facebook-for-woocommerce/includes/Feed/FeedConfigurationDetection.php on line 110

**Comment by spangher** [comment]
I forget: same warning also on line 114 and 122.

**Comment by solstudioim** [comment]
Looks like this issue is similar to this: https://github.com/woocommerce/facebook-for-woocommerce/issues/2045
