### ISSUE TITLE
Wrong IP sent to Conversion API when site behind proxy

### ISSUE THREAD

**Issue by edu2004eu** [woocommerce/facebook-for-woocommerce#2049]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
My site runs behind CloudFlare. Facebook is complaining that the Conversion API is receiving wrong IP addresses, so I am guessing that the plugin doesn't correctly detect that the site is running behind a proxy and actually sends CloudFlare's IP instead of the client's.

## 🚶‍♀️ Steps to reproduce
1. Install plugin
1. Set up a free CloudFlare account
1. Set the DNS to CF
1. Trigger some FB events
1. Check the FB pixel dashboard

## ✔️ Expected behavior
Client's IP should be sent / FB shouldn't complain about wrong IPs

**Comment by AashikP** [comment]
Another report in 4200192-zen

**Comment by rawdreeg** [comment]
This issue seems to have been fixed by https://github.com/woocommerce/woocommerce/issues/16319. Closing
