### ISSUE TITLE
Facebook for WooCommerce en_basedir restriction in effect. file

### ISSUE THREAD

**Issue by JPVT1977** [woocommerce/facebook-for-woocommerce#2052]
Hi there 

I am not a developer but stuck in Spain and build my wife a WooCommerce site for her art but go stuck this week with an basedir error code. My internet provider just keeps on sending me links and aren't willing to help. I have now figured out how to login into the PHP file but I try and copy/paste all the corrections on this site but it keeps giving me errors. Where can I copy the correct complete PHP file that will sort out the redirect issue if upload it via Filezilla? 

Your assistance will be greatly appreciated. 

FYI this is error message:n_basedir restriction in effect. file(/includes/fbwpml.php) is not within the allowed path(s): (/usr/www/wwws/users/kalvtnyrfs:/usr/wwws/users/kalvtnyrfs:/usr/www/users/kalvtnyrfs:/usr/home/kalvtnyrfs:/usr/local/rmagic:/usr/share/php:/usr/local/lib/php:/tmp:/usr/bin:/usr/local/bin:/usr/local/share/www:/usr/www/share/www:/usr/share/misc:/dev/urandom:/var/www/php_profiler/xhgui) in /usr/www/users/kalvtnyrfs/wp-content/plugins/facebook-for-woocommerce/includes/integrations/integrations.php on line 61 warning: cannot modify header information - headers already sent by

**Comment by prhomhyse** [comment]
Hey @JPVT1977 
To manually resolve this, please remove the beginning slash (/) from /includes/fbwpml.php in `wp-content/plugins/facebook-for-woocommerce/includes/Integrations/Integrations.php`

**Comment by haszari** [comment]
Duplicate issue of #1642 - closing this issue. 

Please feel free to add any comments or insights to #1642 directly – thanks for reporting.
