### ISSUE TITLE
Add a filter to get_all_product_ids_for_sync function

### ISSUE THREAD

**Issue by pogla** [woocommerce/facebook-for-woocommerce#2054]
## Feature requests

It would be very useful to get a filter added to `get_all_product_ids_for_sync` function so developers can define their own ids to sync. I would add something like this to beginning of the function:

```php
$product_ids = apply_filters( 'wc_facebook_product_ids', array() );

if ( $product_ids ) {
    return $product_ids;
}
```

**Comment by jconroy** [comment]
Thanks @pogla 

Please head over to our ideas board to add this feature/idea for us to consider.

https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=398356
