### ISSUE TITLE
Pixel Caffeine Deprecation: Ease Adoption of Facebook for WooCommerce Plug-in

### ISSUE THREAD

**Issue by abashinfection** [woocommerce/facebook-for-woocommerce#2057]
## Pixel Caffeine Deprecation

Since a few weeks back, Pixel Caffeine is deprecated and will no longer receive updates. 
Moreover, the developers stated that their plug-in will no longer work after October 1st, 2021 ([source](https://wordpress.org/support/topic/pixel-caffeine-plug-in-deprecation/)). 
This is a huge opportunity for Facebook for WooCommerce plug-in to onboard new users, giving them a solid alternative that they could rely upon for the years to come. 

Unfortunately, Pixel Caffeine has some implementation differences that make it impossible for some users to easily switch to Facebook for WooCommerce. 

Since I am in the process of adopting Facebook for WooCommerce on a website that has used Pixel Caffeine for the last year, I noticed a few issues which I'll try to explain as best as I can in the following sections.  
This is a work-in-progress list and I may add additional items in the future. 

## Product ID mismatch

This is the most critical issue I noticed, and effectively prevents users from switching to Facebook for WooCommerce, unless they are willing to lose all Pixel events they collected in the past.

Pixel Caffeine has a setting to use the product SKU as Product ID in every Pixel event. Unlike Facebook for WooCoomerce, the SKU is taken as-is, without adding any prefix/postfix. 
So each product is uniquely identified by the SKU in the Facebook Catalog, as shown in the following screenshot:
<img width="931" alt="Screen Shot 2021-07-28 at 11 01 06" src="https://user-images.githubusercontent.com/29240616/127295733-021b5f24-0587-40fd-8e15-a5042c9f92d6.png">

However, the Pixel tracking code generated by Facebook for WooCommerce sends events with a different Product ID, as shown in the following screenshot (from Facebook Pixel Helper extension):
<img width="243" alt="Screen Shot 2021-07-28 at 10 57 49" src="https://user-images.githubusercontent.com/29240616/127295758-558f516a-fe32-46b7-ace0-3f77b78994b5.png">

IMHO, there are two main aspects of this issue:
- Having a matching Product ID between Facebook Catalog products and events fired from the Pixel code.
- Retain all Pixel events generated during years of usage of Pixel Caffeine, meaning we should not upload a new catalog with new Product IDs.

Let me explain those points a little bit better. 
Users that are coming from Pixel Caffeine are likely going to face duplicate products in their Facebook Catalog because Facebook for WooCommerce uses a different pattern for Product ID (mentioned [here](https://github.com/woocommerce/facebook-for-woocommerce/issues/1668#issuecomment-724116874)). So, users might be tempted to remove the old products (created by the Pixel Caffeine feed) from the Facebook Catalog. They seem to have no use anymore since the Pixel code from Facebook for WooCommerce will only match the new Product IDs just added to the catalog.
Unfortunately, Facebook considers the newly added products as entirely new products, even though they are duplicates of the old ones, and is not able to properly account for past events: years of tracking would be lost because we moved to a new Product IDs set. 

I'm not entirely sure this also applies to tracking events within Facebook platforms (interactions with Shops in FB/IG apps and websites). But I highly expect those to be affected as well. 

Facebook for WooCoomeerce seemed to have some settings to control the value of Product ID field, as stated from the [latest documentation](https://docs.woocommerce.com/document/facebook-for-woocommerce/), but I'm not able to find those settings anymore with the latest version of the plug-in.
Here's the relevant screenshots of settings mentioned but not available anymore:
![image](https://user-images.githubusercontent.com/29240616/127300761-a9d9e339-7621-4206-8055-b66bba7cf0c7.png)
  
<img width="1055" alt="Screen Shot 2021-07-28 at 11 42 16" src="https://user-images.githubusercontent.com/29240616/127301162-8cb4de36-9202-4ecd-97dd-498482c63b1c.png">

I believe bringing back those settings would help users to switch to Facebook for WooCommerce and still retain years of tracking events, allowing them to continue designing highly targeted campaigns without not starting over from scratch.  

## Wrong AddToCart Value

This is an issue I've already talked about and explained in great detail. Please refer to #1847 
For users coming from Pixel Caffeine plug-in, having a wrong value for AddToCart events is a big issue. 

Consider the _Value Based Audience_ we can create within the Facebook business platform: all of a sudden, the same AddToCart events start to have an increased value, and Facebook will start believing that some users should be weighted more than others. It will start looking for users more similar to the ones that generated the latest events, but is it true that they have more _value_ to the business? The response is no, what makes them different is simply that Facebook for WooCommerce started valuing those users more because of a bug in the plug-in code.
Again, please refer to #1847 for additional information.

## Conclusions
I strongly believe Facebook for WooCommerce team should take advantage of the deprecation of Pixel Caffeine and take a few steps to make it simple for new potential users to adopt Facebook for WooCommerce plug-in in their websites. 
I'm no PHP expert, but I believe the effort to achieve these changes is minimal, given that many required features were already implemented before, as mentioned by the official documentation. 

I would be glad to help in any way I can, please feel free to provide any feedback on these ideas.

**Comment by abashinfection** [comment]
A viable solution has been suggested in #1197 
That would work with anyone willing to add a filter. 

If you need a more user-friendly, one-click solution, I'm working on this:
<img width="658" alt="Screen Shot 2021-07-30 at 08 00 42" src="https://user-images.githubusercontent.com/29240616/127608065-0662c873-469d-4972-afa6-1a9d11ac5002.png">

**Comment by rawdreeg** [comment]
Thanks for reporting this. Most of these issues have addressed and we're working on addressing issue related to Pixel Tracking and Conversions
