### ISSUE TITLE
Warning: is_readable(): open_basedir restriction in effect

### ISSUE THREAD

**Issue by Agnes1969** [woocommerce/facebook-for-woocommerce#2060]
Hello,
I have a problem with the plugin Facebook for Woocommerce.
Once activated it appears a warning on my front-page of the website:

Warning: is_readable(): open_basedir restriction in effect
<img width="1393" alt="Bildschirmfoto 2021-08-06 um 12 10 10 PM" src="https://user-images.githubusercontent.com/87874506/128496210-c13f8828-918d-4279-9932-4e01a7b17afa.png">

How can I fix this?

**Comment by rwkyyy** [comment]
same issue here.

**Comment by haszari** [comment]
Duplicate issue of #1642 - closing this issue. 

Please feel free to add any comments or insights to #1642 directly – thanks for reporting.
