### ISSUE TITLE
Cannot setup Facebook for Woocommerce

### ISSUE THREAD

**Issue by tmarylena** [woocommerce/facebook-for-woocommerce#2062]
Hi, I downloaded the plugin Facebook for Woocommerce, I pressed activate, and when I go to setup (or configure), the new page never loads and it gets stuck like this forever. 
I also got an automated email from Wordpress about that same url (https://xxxxx.xxxx/wp-admin/admin.php?page=wc-facebook) ,  that detects when a plugin or theme causes a fatal error on your site, and notifies you. The site works by the way, only the plugin cannot be configured

**Comment by jconroy** [comment]
Hi @tmarylena

Thanks for posting and sorry for your difficulties. If you haven't done so please create a support request on woocommerce.com or a [new topic in the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for assistance.

Our happiness team will be better able to support you in those locations.
