### ISSUE TITLE
Disallowed characters in Custom Product Attribute causes error and sync failure

### ISSUE THREAD

**Issue by tijosh** [woocommerce/facebook-for-woocommerce#2063]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

If a disallowed character such as `:` is sent in the `additional_variant_attribute` properties, the associated variation will fail to sync, and an error will be thrown:

`The additional_variant_attribute information under  is invalid.`

## 🚶‍♀️ Steps to reproduce

In my observation, the extension excludes these kinds of characters from the `additional_variant_attribute` in most cases, which makes reproducing difficult. See p74xnj-uJ-p2#comment-1536

1. Create a variable product with an attribute that has the following values: `XS: 80/86 cm, S: 92/98 cm, M: 104/110 cm, L: 116/122 cm`
2. Create variations from all attributes
3. See if the attribute's values were sent in the `additional_variant_attribute` properties, such as:

> "additional_variant_attribute":"cor:Bege,tamanho:L: 116\/122 cm"

## ✔️ Expected behavior

The `additional_variant_attribute` properties only sends valid characters

**Comment by solstudioim** [comment]
Reported on 4453368-Zen

**Comment by johndcoy** [comment]
@message-dimke The filter in the above PR should also include `attribute_name`. The error still occurs if a colon or similar symbol is in the attributes name:

![Screenshot](https://d.pr/i/B5aPCe+)
Screenshot link: https://d.pr/i/B5aPCe
