### ISSUE TITLE
New products are not syncing

### ISSUE THREAD

**Issue by wildsugarart** [woocommerce/facebook-for-woocommerce#2065]
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.

- [X ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.
- [ X] 

## ✍️ Describe the bug

Today I added 2 new products. They will not sync to my FB or IG store. 

## 🚶‍♀️ Steps to reproduce

1. The first step: Add new product
1. The next step: Save (Update) product

## ✔️ Expected behavior

Product will not sync

## 🗃 Logs

https://www.wildsugar.fashion/shop/tops/butterfly-off-the-shoulder-top-in-aloha/

<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.wildsugar.fashion
Site address (URL): https://www.wildsugar.fashion
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.7.0
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.22
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 10.3.31-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: ljlc_
Total Database Size: 143.19MB
Database Data Size: 114.62MB
Database Index Size: 28.57MB
ljlc_woocommerce_sessions: Data: 8.82MB + Index: 0.51MB + Engine MyISAM
ljlc_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ljlc_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
ljlc_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_actionscheduler_actions: Data: 3.85MB + Index: 1.00MB + Engine MyISAM
ljlc_actionscheduler_claims: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_actionscheduler_logs: Data: 12.21MB + Index: 1.54MB + Engine MyISAM
ljlc_commentmeta: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
ljlc_comments: Data: 1.06MB + Index: 0.09MB + Engine InnoDB
ljlc_ebayaffinity_categories: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
ljlc_ebayaffinity_categories_bak: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
ljlc_ebayaffinity_itemspecific_mapping: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_ebayaffinity_log: Data: 13.12MB + Index: 0.29MB + Engine MyISAM
ljlc_ebayaffinity_pushtoken: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_ebayaffinity_shiprules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_ebayaffinity_titlerules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_failed_jobs: Data: 0.18MB + Index: 0.01MB + Engine MyISAM
ljlc_gla_budget_recommendations: Data: 0.11MB + Index: 0.12MB + Engine MyISAM
ljlc_gla_merchant_issues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_gla_shipping_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_gla_shipping_times: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_jig_ext_images: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
ljlc_layerslider: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_layerslider_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ljlc_mailchimp_carts: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ljlc_mailchimp_jobs: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ljlc_mappress_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_mappress_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_masterslider_options: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
ljlc_masterslider_sliders: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
ljlc_ngg_album: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ljlc_ngg_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ljlc_ngg_pictures: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ljlc_options: Data: 17.36MB + Index: 1.14MB + Engine InnoDB
ljlc_postmeta: Data: 31.56MB + Index: 14.84MB + Engine InnoDB
ljlc_posts: Data: 9.44MB + Index: 2.48MB + Engine InnoDB
ljlc_queue: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
ljlc_sbi_instagram_feeds_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ljlc_sbi_instagram_feed_locator: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ljlc_sbi_instagram_posts: Data: 0.29MB + Index: 0.00MB + Engine MyISAM
ljlc_supsystic_tbl_columns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_supsystic_tbl_diagrams: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_supsystic_tbl_rows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_supsystic_tbl_tables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_termmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
ljlc_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
ljlc_term_relationships: Data: 0.52MB + Index: 0.22MB + Engine InnoDB
ljlc_term_taxonomy: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
ljlc_usermeta: Data: 0.28MB + Index: 0.22MB + Engine InnoDB
ljlc_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ljlc_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
ljlc_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ljlc_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wc_order_product_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ljlc_wc_order_stats: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ljlc_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wc_product_meta_lookup: Data: 0.34MB + Index: 0.53MB + Engine MyISAM
ljlc_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_wfBlocks7: Data: 0.20MB + Index: 0.10MB + Engine MyISAM
ljlc_wfConfig: Data: 0.36MB + Index: 0.00MB + Engine InnoDB
ljlc_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wfFileMods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_wfHits: Data: 2.02MB + Index: 0.28MB + Engine InnoDB
ljlc_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ljlc_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ljlc_wfKnownFileList: Data: 0.57MB + Index: 0.08MB + Engine MyISAM
ljlc_wfLiveTrafficHuman: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
ljlc_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_wfLogins: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
ljlc_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ljlc_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_wfNotifications: Data: 0.05MB + Index: 0.01MB + Engine MyISAM
ljlc_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ljlc_wfStatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
ljlc_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ljlc_wps_hit: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
ljlc_wps_index: Data: 0.68MB + Index: 0.94MB + Engine MyISAM
ljlc_wps_key: Data: 0.04MB + Index: 0.07MB + Engine MyISAM
ljlc_wps_object_type: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_wps_query: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_wps_uri: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
ljlc_wps_user_agent: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_campaign: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_email: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_url_mail: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_user: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_wysija_user_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_user_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_wysija_user_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ljlc_yith_wcwl: Data: 0.06MB + Index: 0.03MB + Engine MyISAM
ljlc_yith_wcwl_lists: Data: 0.09MB + Index: 0.14MB + Engine MyISAM
ljlc_yoast_indexable: Data: 2.75MB + Index: 0.44MB + Engine MyISAM
ljlc_yoast_indexable_hierarchy: Data: 0.04MB + Index: 0.14MB + Engine MyISAM
ljlc_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ljlc_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
ljlc_yoast_seo_links: Data: 0.17MB + Index: 0.05MB + Engine MyISAM
ljlc_yoast_seo_meta: Data: 0.14MB + Index: 0.14MB + Engine MyISAM
vp_backup_ljlc_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
vp_backup_ljlc_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
vp_backup_ljlc_ebayaffinity_categories: Data: 1.52MB + Index: 0.20MB + Engine InnoDB
vp_backup_ljlc_ebayaffinity_itemspecific_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_ebayaffinity_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_ebayaffinity_pushtoken: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_ebayaffinity_shiprules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_ebayaffinity_titlerules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
vp_backup_ljlc_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_masterslider_options: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_masterslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_options: Data: 0.66MB + Index: 0.04MB + Engine MyISAM
vp_backup_ljlc_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
vp_backup_ljlc_posts: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
vp_backup_ljlc_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
vp_backup_ljlc_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
vp_backup_ljlc_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
vp_backup_ljlc_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
vp_backup_ljlc_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
vp_backup_ljlc_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_wfBadLeechers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_ljlc_wfConfig: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfHits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_ljlc_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_ljlc_wfKnownFileList: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfLeechers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfLogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_ljlc_wfScanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_wfStatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_wfVulnScanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_ljlc_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_ljlc_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_ljlc_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
vp_backup_ljlc_wps_index: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_ljlc_wps_key: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_ljlc_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_ljlc_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_ljlc_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amn_mi-lite: 2
amp_validated_url: 9
attachment: 2363
avia_framework_post: 55
custom_css: 5
customize_changeset: 1
display_type: 7
displayed_gallery: 7
ec-product: 166
feedback: 55
flamingo_contact: 4
flamingo_inbound: 1
gal_display_source: 5
jetpack_migration: 2
jetpack-portfolio: 1
jetpack-testimonial: 15
jp_img_sitemap: 1
jp_pay_product: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
lightbox_library: 8
nav_menu_item: 48
ngg_gallery: 20
ngg_pictures: 223
oembed_cache: 12
page: 33
portfolio: 10
post: 41
product: 405
product_variation: 4140
revision: 845
shop_coupon: 2
shop_order: 182
shop_order_refund: 7
shop_quote: 1
wysijap: 1
yith-wcpsc-wc-chart: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

VaultPress: by Automattic – 2.1.4
Add From Server: by Dion Hulse – 3.4.5
Afterpay Gateway for WooCommerce: by Afterpay – 3.2.2
Akismet Anti-Spam: by Automattic – 4.1.11
Facebook for WooCommerce: by Facebook – 2.6.1
Google Listings and Ads: by WooCommerce – 1.4.2
Smash Balloon Instagram Feed: by Smash Balloon – 2.9.3.1
Jetpack: by Automattic – 10.0
Mailchimp for WooCommerce: by Mailchimp – 2.5.2
Really Simple SSL: by Really Simple Plugins – 5.0.10
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Update Theme and Plugins from Zip File: by Jeff Sherk – 2.0.0
WooCommerce Blocks: by Automattic – 5.7.0
WooCommerce Currency Converter: by WooCommerce – 1.6.25
WooCommerce Stripe Gateway: by WooCommerce – 5.4.0
WooCommerce: by Automattic – 5.6.0
Wordfence Security: by Wordfence – 7.5.5
Yoast SEO: by Team Yoast – 17.0
YITH WooCommerce Wishlist: by YITH – 3.0.25
Zip - WooCommerce: by Zip – 2.3.7

### Inactive Plugins (2) ###

AMP: by AMP Project Contributors – 2.1.3
WP Super Cache: by Automattic – 1.7.4

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

installatron_hide_status_test.php: by  –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: booking (booking)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #506 - /shop/
Cart: #507 - /cart/
Checkout: #28 - /checkout/
My account: #29 - /my-account/
Terms and conditions: #1095 - /shipping-and-returns/

### Theme ###

Name: Enfold Child
Version: 1.0
Author URL: http://www.kriesi.at
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.8.6.2
Parent Theme Author URL: https://kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,472
Oldest: 2021-08-10 17:02:40 +1000
Newest: 2021-08-26 19:56:27 +1000

Failed: 9,419
Oldest: 2020-03-26 10:49:12 +1000
Newest: 2021-08-19 10:15:28 +1000

Pending: 4
Oldest: 2021-08-27 08:03:34 +1000
Newest: 2021-08-29 16:00:48 +1000

### Status report information ###

Generated at: 2021-08-26 20:00:35 +10:00
`
</details>

**Comment by DSsalesrep** [comment]
When I update a product I receive this message: Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0

**Comment by strarsis** [comment]
Do you also get an API error in the plugin logs? You can enable debug logging in the "Connections" tab in the plugin settings.
https://github.com/woocommerce/facebook-for-woocommerce/issues/2068

**Comment by jconroy** [comment]
Hi @wildsugarart

Thanks for posting and sorry for your difficulties. If you haven't done so please create a support request on woocommerce.com or a [new topic in the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for assistance.

Our happiness team will be better able to support you in those locations.
