### ISSUE TITLE
Facebook for Woocommerce + Litespeed + Facebook API events

### ISSUE THREAD

**Issue by maxcyrekpol** [woocommerce/facebook-for-woocommerce#2066]
## 🔎 Isolate the bug

- [ x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
When the listespeed cache is enabled, the facebook for woocommerce event ID is also cached and do not change with every reload so it stays cached too and should be dynamically updated.

## 🚶‍♀️ Steps to reproduce

1. Enable litespeed cache
1. Enable Facebook for Woocommerce

## ✔️ Expected behavior
Facebook event ID should change even if full page is cached

<details>
	
</details>

**Comment by DarlanOliveiraSA** [comment]
Estou com este mesmo problema agora, minhas páginas estão recebendo o mesmo Event_ID e com isto não contabilizam o conteúdo pois estão considerando como evento duplicado.

Gostaria de saber qual foi a sua solução para este caso, tendo em vista que este chamado parece ser bem antigo e sem resposta.

**Comment by rawdreeg** [comment]
CLosing in favor of #1920
