### ISSUE TITLE
[Latest release | breaking] Bad Request: "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v10.0."

### ISSUE THREAD

**Issue by strarsis** [woocommerce/facebook-for-woocommerce#2068]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Product sync doesn't work (automatically or triggered), API error logged (with debug log enabled).

## 🚶‍♀️ Steps to reproduce

1. Install and enable the `WooCommerce` and `facebook for WooCommerce` plugins.
2. Connect the `facebook for WooCommerce` plugin (to a shop catalog).
3. Trigger product synchronization, as using the `Product sync` tab, `Sync products`.

## ✔️ Expected behavior
Product synchronization should work (automatically and triggered).

## 🗃 Logs

<details>

````
08-31-2021 @ 19:01:43 - Request
Request
method: POST
uri: https://graph.facebook.com/v9.0/[...]/items_batch
user-agent: Facebook-for-WooCommerce/2.6.1 (WooCommerce/5.6.0; WordPress/5.8)
[...]

08-31-2021 @ 19:01:43 - Response
Response
code: 400
message: Bad Request
[...]
body: {"error":{"message":"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v10.0.","type":"OAuthException","code":2635,"fbtrace_id":"AmqPHVwKaYduKn74UCHBiez"}}
````

</details>

**Comment by yurovigorr** [comment]
Wow! Now here i found a new solution: https://ru.wordpress.org/plugins/facebook-for-woocommerce/#developers
Update to the 2.6.3-dev ver. and it'll solve the problem!

**Comment by strarsis** [comment]
@yurovigorr: Thanks! I will update to that version and hopefully this fixes the issue.
