### ISSUE TITLE
Products created via the WooCommerce Mobile App do not automatically sync to Facebook

### ISSUE THREAD

**Issue by dsvwilson** [woocommerce/facebook-for-woocommerce#2073]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When you use the WooCommerce mobile app (or an external API service) to create a WooCommerce product, the product does not immediately sync to Facebook. When you edit the product and then update, syncing happens. 

## 🚶‍♀️ Steps to reproduce

1. Connect your site to the WooCommerce mobile app
2. Connect Facebook for WooCommerce and enable syncing via Marketing > Facebook > Product sync.
3. Add a product via the WooCommerce mobile app and check your Facebook catalog. It does not sync.
4. Edit the product and update. Check the catalog again. It will have synced. 

## ✔️ Expected behavior

The newly added product should sync once it is published via the mobile app, just as it does when a product is published via the web version.

## 🗃 Logs

No logs to show.

<details>
	
</details>

**Comment by radialmonster** [comment]
Hi, I'm the one that submitted this bug.  A few additional points. 

When you use the WooCommerce mobile app (or an external API service) to create a WooCommerce product, the product does not immediately sync to Facebook. When you edit the product *using the woocommerce in the wp-admin of the website* and then update, syncing happens.

Step 3 - Add a product, *or edit an existing product*,  via the WooCommerce mobile app and check your Facebook catalog. It does not sync.
Step 4 - * Visit the website wp-admin, woocommerce,* Edit the product, *even without changing anything, and click* update. Check the catalog again. It will have synced.

**Comment by tecdisol** [comment]
We have the same problem
our (external API service) is 
https://yuju.io

please inform when problem solved please
https://www.almacenflotablanca.com

**Comment by csmcneill** [comment]
This issue has been reported in 4251555-zen.

**Comment by sukafia** [comment]
Hi @radialmonster, can you test this issue again on the latest version of WooCommerce and the Facebook for WooCommerce extension? I'm asking because the products sync just fine on my end. 

Also, can you confirm if the issue you're seeing is products not syncing at all or taking a while to sync? (e.g syncing within 30 mins to 1 hour). Thank you!

**Comment by israhes** [comment]
hey, this is still happening, any new about ?

**Comment by csmcneill** [comment]
Apologies—misclicked to reopen the issue.
