### ISSUE TITLE
Selecting Facebook Ads during setup, yet no connected Ad manager account shown

### ISSUE THREAD

**Issue by solstudioim** [woocommerce/facebook-for-woocommerce#2074]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
I have an active Facebook ads account, during the onboarding setup, I selected the Facebook Ads option, selected the ads account. Once the setup completed, I got redirected back to WooCommerce and yet no connected ads account was shown:

![Markup 2021-09-07 at 08 27 46](https://user-images.githubusercontent.com/17371139/132274783-f13f0b73-15bf-4763-a89a-55bdf6801107.png)
![Markup 2021-09-07 at 09 20 48](https://user-images.githubusercontent.com/17371139/132274796-e4e165ed-2bfe-4d56-9512-95768081dc21.png)
![Markup 2021-09-07 at 09 23 28](https://user-images.githubusercontent.com/17371139/132274808-c33f346d-0bd3-48fa-a187-ca4b820094bf.png)

Strangely, I was able to create a catalog based ads campaign, using the catalog created through the WooCommerce integration:
![Markup 2021-09-07 at 09 25 43](https://user-images.githubusercontent.com/17371139/132275048-ae74c02c-0e7b-4429-9bc7-35933852c984.png)
![Markup 2021-09-07 at 09 25 06](https://user-images.githubusercontent.com/17371139/132275085-2f7852f4-8bd4-4bc0-b9b1-cd9efc302aa9.png)

As far as I am aware I didn't have this issue before
## 🚶‍♀️ Steps to reproduce

1. Have an active Facebook ads account
2. Select Facebook ads during Facebook for WooCommerce onboarding setup screen, select the ads account
3. No connected ads account shown

## ✔️ Expected behavior

When Facebook ads option is selected during setup, and the user has an active Facebook ad account, it should automatically show a connected Facebook ads

## 🗃 Logs

<details>
	`
### WordPress Environment ###

WordPress address (URL): https://solsubs.mystagingwebsite.com
Site address (URL): https://solsubs.mystagingwebsite.com
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.23
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.78.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.31-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_
Total Database Size: 44.42MB
Database Data Size: 29.59MB
Database Index Size: 14.83MB
wp_woocommerce_sessions: Data: 0.34MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.31MB + Index: 0.33MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fakenames: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.53MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 1.09MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.23MB + Index: 0.28MB + Engine InnoDB
wp_email_log: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.08MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 9.42MB + Index: 9.50MB + Engine InnoDB
wp_posts: Data: 2.19MB + Index: 0.44MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.06MB + Index: 0.19MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.20MB + Index: 0.41MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 799
aw_workflow: 19
customize_changeset: 2
custom_css: 1
elementor_library: 1
event_ticket: 6
fgf_rules: 1
fme_upload_files: 1
nav_menu_item: 4
page: 20
post: 1
product: 396
product_variation: 773
revision: 36
shop_coupon: 4
shop_order: 401
shop_order_refund: 4
shop_subscription: 72
wc_booking: 4
wc_membership_plan: 1
wc_user_membership: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Facebook for WooCommerce: by Facebook – 2.6.4
WooCommerce: by Automattic – 5.6.0

### Inactive Plugins (76) ###

Action Scheduler - Disable Default Queue Runner: by Prospress Inc. – 1.0.0
Advanced Database Cleaner: by Younes JFR. – 3.0.3
Akismet Anti-Spam: by Automattic – 4.1.12
All-in-One WP Migration: by ServMask – 7.44
AutomateWoo: by WooCommerce – 5.5.1
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.1
Bulk Edit Products, Prices & Attributes for Woocommerce: by ELEX – 1.0.3
Clean Options: by Mittineague – 1.3.2
Code Snippets: by Code Snippets Pro – 2.14.1
Combine Reviews for WooCommerce: by Ahmad Shyk – 1.0.0
CTX Feed: by WebAppick – 4.4.14
Customer Upload Files for WooCommerce: by FME Addons – 1.0.4
Elementor: by Elementor.com – 3.4.3
Email Log: by Sudar – 2.4.5
Extend WooCommerce Subscription Intervals: by Brent Shepherd – 1.0
Facebook for WordPress: by Facebook – 3.0.5
Free Gifts for WooCommerce: by FantasticPlugins – 6.2
Jetpack: by Automattic – 10.0
JSM's Show Post Metadata: by JS Morisset – 1.3.0
JSON Content Importer: by Bernhard Kux – 1.3.12
Maybe Pass requests through Moesif: by Will Brubaker – 0.1b
Multi Currency for WooCommerce: by VillaTheme – 2.1.7
My Database Admin: by wpshrike – 1.1.22
Order Simulator for WooCommerce: by 75nineteen Media LLC – 1.0.2
PayPal Sandbox IPN Tester: by WooThemes – 1.0.0
Plugins Garbage Collector (Database Cleanup): by Vladimir Garagulya – 0.12
Query Monitor: by John Blackbourn – 3.7.1
Say What?: by Ademti Software – 2.0.2
Subscription Box For WooCommerce: by Codup – 1.1.3.4
Subscriptions Add-On for WooCommerce: by Codup – 1.2.9.5
Transients Manager: by Pippin Williamson – 1.8.1
Turbo Admin: by Ross Wintle – 1.0.3
User Role Editor: by Vladimir Garagulya – 4.60.1
User Switching for WooCommerce: by Krokedil – 2.0.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.45
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.24
WooCommerce Account Funds: by Themesquad – 2.3.11 (update to version 2.5.3 is available)
WooCommerce Admin Custom Order Fields: by SkyVerge – 1.15.1
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.29 (update to version 3.1.30 is available)
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.5.0 (update to version 3.6.2 is available)
WooCommerce Blocks: by Automattic – 5.6.0
WooCommerce Bookings: by WooCommerce – 1.15.37 (update to version 1.15.43 is available)
WooCommerce Box Office: by WooCommerce – 1.1.32 (update to version 1.1.35 is available)
WooCommerce Brands: by WooCommerce – 1.6.24 (update to version 1.6.25 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.6.0 (update to version 1.6.2 is available)
WooCommerce Composite Products: by SomewhereWarm – 8.2.0
WooCommerce Deposits: by WooCommerce – 1.5.6 (update to version 1.5.7 is available)
WooCommerce Dynamic Pricing: by Element Stark – 3.1.24 (update to version 3.1.26 is available)
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.1
WooCommerce Memberships: by SkyVerge – 1.21.7 (update to version 1.22.4 is available)
WooCommerce Multi-currency: by TIV.NET INC – 2.14.0 (update to version 2.14.1 is available)
WooCommerce Name Your Price: by Kathy Darling – 3.2.3 (update to version 3.3.2 is available)
WooCommerce Order Barcodes: by WooCommerce – 1.3.23 (update to version 1.3.24 is available)
WooCommerce Order Delivery: by Themesquad – 1.9.0 (update to version 1.9.2 is available)
WooCommerce Payments: by Automattic – 2.9.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.2
WooCommerce PayPal Payments: by WooCommerce – 1.5.1
WooCommerce Product Bundles: by SomewhereWarm – 6.11.1 (update to version 6.12.0 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.41 (update to version 1.10.46 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.18
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.14 (update to version 2.3.15 is available)
WooCommerce Store Credit: by Themesquad – 3.6.1 (update to version 3.9.1 is available)
WooCommerce Stripe Gateway: by WooCommerce – 5.4.0
WooCommerce Subscription Downloads: by WooCommerce – 1.1.31
WooCommerce Subscriptions: by WooCommerce – 3.1.2 (update to version 3.1.4 is available)
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.4
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WooCommerce USPS Shipping: by WooCommerce – 4.4.51 (update to version 4.4.62 is available)
WooCommerce Waitlist: by Neil Pie – 2.2.4 (update to version 2.3.0 is available)
WooCommerce Zapier: by OM4 Software – 2.0.8 (update to version 2.2.1 is available)
WordPress Importer: by wordpressdotorg – 0.7
WP Crontrol: by John Blackbourn & crontributors – 1.10.0
WP phpMyAdmin: by Puvox.software – 5.1.1
WP Rollback: by Impress.org – 1.7.1
WP STAGING: by WP-STAGING – 2.8.5
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.1.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP STAGING Optimizer: by René Hermenau – 1.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
box (box)
bundle (bundle)
composite (composite)
deposit (deposit)
external (external)
grouped (grouped)
simple (simple)
store_credit (store_credit)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.8.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,207
Oldest: 2021-08-11 04:40:54 +0000
Newest: 2021-08-28 14:18:04 +0000

Pending: 37
Oldest: 2021-09-07 02:32:19 +0000
Newest: 2024-08-13 08:08:39 +0000

Failed: 1
Oldest: 2021-05-18 05:36:45 +0000
Newest: 2021-05-18 05:36:45 +0000

Canceled: 3
Oldest: 2021-08-12 02:58:54 +0000
Newest: 2021-08-27 03:27:43 +0000

### Status report information ###

Generated at: 2021-09-07 02:31:28 +00:00
`
</details>

**Comment by amElnagdy** [comment]
35407180-hc

**Comment by solstudioim** [comment]
I wonder, because there is no step in the onboarding process to select a particular Ads Account, rather any ads account within a Business Manager connected with [Facebook for WooCommerce](https://woocommerce.com/products/facebook/?aff=10486&cid=1131038) should be able to be managed directly through Facebook, we can remove that information field on the plugin connection setting altogether: 

![Markup 2022-07-29 at 09 22 13](https://user-images.githubusercontent.com/17371139/181670246-657696cf-e3e8-4275-97e4-f3111f97ab05.png)

**Comment by solstudioim** [comment]
Reported in 5430439-zd-woothemes

**Comment by rawdreeg** [comment]
Meta seems to have fixed this. Closing
