### ISSUE TITLE
Remove first_name and last_name url params from the query

### ISSUE THREAD

**Issue by DeniscoDp5** [woocommerce/facebook-for-woocommerce#2075]
Hi!
Facebook manage events says this to me, an issue related to privacy url params passed when firing events such Purchase
![image](https://user-images.githubusercontent.com/30060768/132519561-1dca31f2-32d7-4902-a4aa-f3738bf4d1a6.png)

There seems to be the param first_name and last_name passed to facebook. Is there a way to remove them? It happends when the endpoint **order-received** has been hit

/checkout/order-received/22978/?key=_removed_&utm_nooverride=_removed_&PayerID=_removed_&st=_removed_&tx=_removed_&cc=_removed_&amt=_removed_&cm=_removed_&payer_email=_removed_&payer_id=_removed_&payer_status=_removed_&**first_name**=_removed_&**last_name**=_removed_&address_name=_removed_&address_street=_removed_&address_city=_removed_&address_state=_removed_&address_country_code=_removed_&address_zip=_removed_&residence_country=_removed_&txn_id=_removed_&mc_currency=_removed_&mc_fee=_removed_&mc_gross=_removed_&protection_eligibility=_removed_&payment_fee=_removed_&payment_gross=_removed_&payment_status=_removed_&payment_type=_removed_&handling_amount=_removed_&shipping=_removed_&tax=_removed_&item_name1=_removed_&quantity1=_removed_&mc_gross_1=_removed_&tax1=_removed_&num_cart_items=_removed_&txn_type=_removed_&payment_date=_removed_&business=_removed_&receiver_id=_removed_&notify_version=_removed_&custom=_removed_&invoice=_removed_&verify_sign=_removed_&_filteredParams=_removed_&fbclid=IwAR2FxusEni0TVDaYOAo7b8PabhDx5Td4wJ9tdfcGWQYbavPOKAGNYYbi1Sg

**Comment by DeniscoDp5** [comment]
hi, still now i have the same problem recourring. I ignore the event on facebook but it's not the best solution

**Comment by kokomomtl** [comment]
I am having the same issue. Following.

**Comment by rawdreeg** [comment]
Thanks @kokomomtl, @DeniscoDp5 for reporting this.

I haven't been able to reproduce the error on a clean setup. I'd like to investigate this further, can you please share a copy of your site’s System Status? You can find it via WooCommerce > Status. Select “Get system report” and then “Copy for support”.

**Comment by kokomomtl** [comment]
`
### WordPress Environment ###

WordPress address (URL): ##
Site address (URL): ##
WC Version: 7.0.0
REST API Version: ✔ 7.0.0
WC Blocks Version: ✔ 8.5.1
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.0.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.51 (Debian)
PHP Version: 7.4.30
PHP Post Max Size: 50 MB
PHP Time Limit: 120
PHP Max Input Vars: 3600
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~buster-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.0.0
WC Database Prefix: tsh_
Total Database Size: 468.38MB
Database Data Size: 343.05MB
Database Index Size: 125.33MB
tsh_woocommerce_sessions: Data: 9.02MB + Index: 0.19MB + Engine InnoDB
tsh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tsh_woocommerce_order_items: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
tsh_woocommerce_order_itemmeta: Data: 5.52MB + Index: 6.03MB + Engine InnoDB
tsh_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tsh_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tsh_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tsh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_actionscheduler_actions: Data: 13.52MB + Index: 11.47MB + Engine InnoDB
tsh_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_actionscheduler_logs: Data: 25.56MB + Index: 5.03MB + Engine InnoDB
tsh_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
tsh_automatewoo_customers: Data: 0.22MB + Index: 0.58MB + Engine InnoDB
tsh_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tsh_automatewoo_guests: Data: 0.20MB + Index: 0.34MB + Engine InnoDB
tsh_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tsh_automatewoo_log_meta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
tsh_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tsh_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_bv_ip_store: Data: 0.33MB + Index: 0.38MB + Engine InnoDB
tsh_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_commentmeta: Data: 0.34MB + Index: 0.14MB + Engine InnoDB
tsh_comments: Data: 2.52MB + Index: 1.42MB + Engine InnoDB
tsh_essb3_click_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_ewwwio_images: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
tsh_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_gf_entry: Data: 1.52MB + Index: 0.17MB + Engine InnoDB
tsh_gf_entry_meta: Data: 2.52MB + Index: 4.47MB + Engine InnoDB
tsh_gf_entry_notes: Data: 0.36MB + Index: 0.14MB + Engine InnoDB
tsh_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_gf_form_meta: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
tsh_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_gf_form_view: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
tsh_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_icl_languages_translations: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
tsh_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_icl_mo_files_domains: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
tsh_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_icl_strings: Data: 11.52MB + Index: 21.08MB + Engine InnoDB
tsh_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_icl_string_pages: Data: 15.55MB + Index: 23.06MB + Engine InnoDB
tsh_icl_string_positions: Data: 1.52MB + Index: 0.14MB + Engine InnoDB
tsh_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_icl_string_translations: Data: 6.52MB + Index: 4.03MB + Engine InnoDB
tsh_icl_string_urls: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
tsh_icl_translate: Data: 23.52MB + Index: 1.52MB + Engine InnoDB
tsh_icl_translate_job: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
tsh_icl_translations: Data: 1.52MB + Index: 1.45MB + Engine InnoDB
tsh_icl_translation_batches: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
tsh_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_icl_translation_status: Data: 12.38MB + Index: 0.08MB + Engine InnoDB
tsh_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_nextend2_section_storage: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tsh_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_nextend2_smartslider3_sliders: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
tsh_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_nextend2_smartslider3_slides: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
tsh_nm_personalized: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_options: Data: 22.22MB + Index: 0.19MB + Engine InnoDB
tsh_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
tsh_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_postmeta: Data: 50.56MB + Index: 21.98MB + Engine InnoDB
tsh_posts: Data: 41.48MB + Index: 3.53MB + Engine InnoDB
tsh_prli_clicks: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
tsh_prli_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_prli_links: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
tsh_prli_link_metas: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_redirection_404: Data: 1.02MB + Index: 0.19MB + Engine InnoDB
tsh_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_redirection_items: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
tsh_redirection_logs: Data: 2.02MB + Index: 0.20MB + Engine InnoDB
tsh_revslider_css: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
tsh_revslider_css_bkp: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
tsh_revslider_layer_animations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_revslider_sliders_bkp: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
tsh_revslider_slides: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
tsh_revslider_slides_bkp: Data: 0.23MB + Index: 0.02MB + Engine InnoDB
tsh_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_rg_form_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
tsh_rg_form_view: Data: 0.34MB + Index: 0.30MB + Engine InnoDB
tsh_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_rg_lead: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
tsh_rg_lead_detail: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
tsh_rg_lead_detail_long: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
tsh_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tsh_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_slp_extendo_meta: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tsh_sl_setting: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_sl_tag: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_snp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_snp_stats: Data: 0.27MB + Index: 0.48MB + Engine InnoDB
tsh_store_locator: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tsh_termmeta: Data: 0.23MB + Index: 0.13MB + Engine InnoDB
tsh_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
tsh_term_relationships: Data: 0.31MB + Index: 0.20MB + Engine InnoDB
tsh_term_taxonomy: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
tsh_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_tinvwl_items: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
tsh_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_usermeta: Data: 3.52MB + Index: 4.02MB + Engine InnoDB
tsh_users: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
tsh_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
tsh_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
tsh_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wc_customer_lookup: Data: 0.22MB + Index: 0.23MB + Engine InnoDB
tsh_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
tsh_wc_order_coupon_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
tsh_wc_order_product_lookup: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
tsh_wc_order_stats: Data: 0.27MB + Index: 0.22MB + Engine InnoDB
tsh_wc_order_tax_lookup: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
tsh_wc_product_attributes_lookup: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
tsh_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_wc_product_meta_lookup: Data: 0.16MB + Index: 0.34MB + Engine InnoDB
tsh_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_wfBlockedIPLog: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
tsh_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tsh_wfConfig: Data: 1.33MB + Index: 0.00MB + Engine InnoDB
tsh_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wfFileMods: Data: 41.58MB + Index: 0.00MB + Engine InnoDB
tsh_wfHits: Data: 2.02MB + Index: 0.25MB + Engine InnoDB
tsh_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
tsh_wfKnownFileList: Data: 18.52MB + Index: 0.00MB + Engine InnoDB
tsh_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wfLogins: Data: 0.41MB + Index: 0.16MB + Engine InnoDB
tsh_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wfNotifications: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
tsh_wfPendingIssues: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
tsh_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
tsh_wfStatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
tsh_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_woocommerce_bundled_itemmeta: Data: 0.36MB + Index: 0.41MB + Engine InnoDB
tsh_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wpr_rocket_cache: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
tsh_wpr_rucss_used_css: Data: 0.20MB + Index: 0.28MB + Engine InnoDB
tsh_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tsh_yoast_indexable: Data: 6.52MB + Index: 2.14MB + Engine InnoDB
tsh_yoast_indexable_hierarchy: Data: 0.42MB + Index: 0.56MB + Engine InnoDB
tsh_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tsh_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tsh_yoast_seo_links: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
tsh_yoast_seo_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 2
acf-field: 10
acf-field-group: 4
attachment: 4258
aw_workflow: 8
custom_css: 2
customize_changeset: 2
ig_campaign: 1
ig_message: 7
jetpack_migration: 2
mention: 94
ml-slide: 6
ml-slider: 2
nav_menu_item: 94
oembed_cache: 3
omapi: 15
page: 64
portfolio: 8
post: 159
product: 358
product_variation: 479
revision: 773
shop_coupon: 42
shop_order: 2130
shop_order_refund: 26
snp_mail_log: 760
snp_popups: 4
soliloquy: 1
wccf_product_field: 4
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

Gravity Forms: by Gravity Forms – 2.6.7
WPML Multilingual CMS: by OnTheGoSystems – 4.5.11
Advanced Custom Fields PRO: by WP Engine – 6.0.3
CAPTCHA 4WP: by WP White Security – 7.1.1
Akismet Anti-Spam: by Automattic – 5.0.1
AutomateWoo: by WooCommerce – 5.5.21
WordPress Backup & Security Plugin - BlogVault: by Backup by BlogVault – 4.82
CheckoutWC: by Objectiv – 7.7.2
ConvertKit for WooCommerce: by ConvertKit – 1.5.1
ConvertKit: by ConvertKit – 2.0.0
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.1
GTM4WP: by Thomas Geiger – 1.16.1
Facebook for WooCommerce: by Facebook – 2.6.28
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: by HubSpot – 9.0.338
MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.82
Image optimization service by Optimole: by Optimole – 3.5.0
OptinMonster: by OptinMonster Popup Builder Team – 2.10.0
Pinterest for WooCommerce: by WooCommerce – 1.2.4
Redirection: by John Godley – 5.3.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Safe SVG: by 10up – 2.0.3
Stamped.io Reviews & UGC for WooCommerce: by Stamped.io – 2.3.2
StarBox: by Squirrly UK – 3.4.5
String Locator: by InstaWP – 2.6.0
TI WooCommerce Wishlist: by TemplateInvaders – 2.0.9
TSHU: by Thierry Lavergne – 1.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.23

Product Customer List for WooCommerce: by Kokomo – 3.1.2
Widget Context: by Kaspars Dambis – 1.3.2
Product Feed PRO for WooCommerce: by AdTribes.io – 11.9.6
WooCommerce Checkout Add-Ons: by SkyVerge – 2.5.7
WooCommerce Stripe Gateway: by WooCommerce – 6.9.0
Pixel Manager for WooCommerce: by SweetCode – 1.25.1
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.0.2
Invoices for WooCommerce: by Bas Elbers – 3.1.9
WooCommerce Price Based on Country Pro Add-on: by Oscar Gare – 2.21.0
WooCommerce Product Bundles: by WooCommerce – 6.17.2
WooCommerce Price Based on Country (Basic): by Oscar Gare – 2.2.6
WooCommerce Shipment Tracking: by WooCommerce – 1.9.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.1
WooCommerce: by Automattic – 7.0.0
Wordfence Security: by Wordfence – 7.7.1
Yoast SEO: by Team Yoast – 19.9
WP Mail SMTP: by WPForms – 3.6.1
WP Rocket: by WP Media – 3.12.2.1
WPML Media: by OnTheGoSystems – 2.7.1
WPML String Translation: by OnTheGoSystems – 3.2.2

### Inactive Plugins (5) ###

Query Monitor: by John Blackbourn – 3.10.1
Slide down notification bar: by Thierry Lavergne – 1.1
Smart Slider 3: by Nextend – 3.5.1.11
Trustpilot-reviews: by Trustpilot – 2.5.914
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (1) ###

Object Cache Pro (MU): by Rhubarb Group – 1.16.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CAD ($)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #1651 - /shop/
Cart: #1652 - /cart/
Checkout: #1653 - /checkout/
My account: #1654 - /my-account/
Terms and conditions: #4068 - /terms-and-conditions/

### Theme ###

Name: TSHU (Storefront)
Version: 2.5.3.1568747515
Author URL: https://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.1.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Geolocation debug info ###

Default customer location: geolocation
MaxMind GeoIP database: ✔
MaxMind GeoIP license: ✔
MM_COUNTRY_CODE: ❌
GEOIP_COUNTRY_CODE: ❌
HTTP_CF_IPCOUNTRY: ❌
HTTP_X_COUNTRY_CODE: ❌
HTTP_X_REAL_IP: 74.58.147.178
HTTP_X_FORWARDED_FOR: 74.58.147.178
REMOTE_ADDR: 74.58.147.178
Real external IP: 74.58.147.178
WCPBC_USE_REMOTE_ADDR: –
Geolocation Test: ✔

### PBC Settings ###

Version: 2.2.6
Base location: CA:QC
Base currency: CAD
Price Based On: billing
Shipping: ✔
Test mode: –
Test country: –
Load products price in background: ✔
Currency format: [price][symbol]
Exchange rate API: floatrates
Prices entered with tax: –
Calculate tax based on: shipping
Display prices in the shop: excl

### Zone Pricing Canada ###

zone_id: canada
name: Canada
countries: CA
currency: CAD
exchange_rate: 1
auto_exchange_rate: yes
exchange_rate_fee: 0
round_nearest: 
currency_format: 
price_thousand_sep: 
price_decimal_sep: ,
price_num_decimals: 2
disable_tax_adjustment: yes
real_exchange_rate: 1
round_after_taxes: no
trim_zeros: no

### Zone Pricing Europe ###

zone_id: europe
name: Europe
countries: AX | AD | AT | BE | CY | EE | FI | GF | TF | DE | GR | GP | IE | IT | LV | LT | LU | MT | MQ | YT | MC | ME | NL | PT | RE | BL | MF | PM | SM | SK | SI | ES | VA
currency: EUR
exchange_rate: 0.7387990392418
auto_exchange_rate: yes
exchange_rate_fee: 0
round_nearest: 
currency_format: 
price_thousand_sep: 
price_decimal_sep: ,
price_num_decimals: 2
disable_tax_adjustment: yes
real_exchange_rate: 0.738799
round_after_taxes: no
trim_zeros: no

### Zone Pricing France ###

zone_id: france
name: France
countries: FR
currency: EUR
exchange_rate: 0.7387990392418
auto_exchange_rate: yes
exchange_rate_fee: 0
round_nearest: 
currency_format: 
price_thousand_sep: 
price_decimal_sep: ,
price_num_decimals: 2
disable_tax_adjustment: no
real_exchange_rate: 0.738799
round_after_taxes: no
trim_zeros: no

### Zone Pricing Other countries ###

zone_id: other-countries
name: Other countries
countries: AF | AL | DZ | AS | AO | AI | AQ | AG | AR | AM | AW | AU | AZ | BS | BH | BD | BB | BY | PW | BZ | BJ | BM | BT | BO | BQ | BA | BW | BV | BR | IO | BN | BG | BF | BI | KH | CM | CV | KY | CF | TD | CL | CN | CX | CC | CO | KM | CG | CD | CK | CR | HR | CU | CW | CZ | DK | DJ | DM | DO | EC | EG | SV | GQ | ER | ET | FK | FO | FJ | PF | GA | GM | GE | GH | GI | GL | GD | GU | GT | GG | GN | GW | GY | HT | HM | HN | HK | HU | IS | IN | ID | IR | IQ | IM | IL | CI | JM | JP | JE | JO | KZ | KE | KI | KW | KG | LA | LB | LS | LR | LY | LI | MO | MG | MW | MY | MV | ML | MH | MR | MU | MX | FM | MD | MN | MS | MA | MZ | MM | NA | NR | NP | NC | NZ | NI | NE | NG | NU | NF | KP | MK | MP | NO | OM | PK | PS | PA | PG | PY | PE | PH | PN | PL | PR | QA | RO | RU | RW | ST | SH | KN | LC | SX | VC | WS | SA | SN | RS | SC | SL | SG | SB | SO | ZA | GS | KR | SS | LK | SD | SR | SJ | SZ | SE | CH | SY | TW | TJ | TZ | TH | TL | TG | TK | TO | TT | TN | TR | TM | TC | TV | UG | UA | AE | GB | US | UM | UY | UZ | VU | VE | VN | VG | VI | WF | EH | YE | ZM | ZW
currency: USD
exchange_rate: 0.73565557324607
auto_exchange_rate: yes
exchange_rate_fee: 0
round_nearest: 
currency_format: 
price_thousand_sep: 
price_decimal_sep: ,
price_num_decimals: 2
disable_tax_adjustment: yes
real_exchange_rate: 0.735656
round_after_taxes: no
trim_zeros: no

### Product Bundles ###

Database Version: 6.17.2
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-10-31 16:49:17 -04:00
Options: ✔
Notes: 109
Onboarding: completed

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 2
Oldest: 2022-10-16 14:50:43 -0400
Newest: 2022-10-21 05:36:24 -0400

Complete: 13,813
Oldest: 2022-10-01 06:57:51 -0400
Newest: 2022-10-31 10:04:08 -0400

Failed: 12,718
Oldest: 2022-09-05 07:15:21 -0400
Newest: 2022-10-16 14:50:58 -0400

In-progress: 1
Oldest: –
Newest: –

Pending: 24
Oldest: -0001-11-29 18:42:28 -0517
Newest: 2022-11-01 06:17:54 -0400


### Status report information ###

Generated at: 2022-10-31 10:06:29 -04:00
`

**Comment by rawdreeg** [comment]
Thanks @kokomomtl,

I had a look at the system report. Unfortunately, I am still unable to reproduce even using the same payment processor. Could you confirm you can still reproduce this error consistently even when using the latest version of the Facebook for WooCommerce plugin? If yes, could you please share with me a screen recording?

R

**Comment by kokomomtl** [comment]
Hi @rawdreeg , unfortunately it's not something we are seeing or able to test on our side, it's facebook themselves sending us alerts once in a while. I can't say if it's fixed or not. Did you have any mention of first_name and last_name in your code? If so, if you have removed it, then you should be good.

**Comment by rawdreeg** [comment]
Thanks, the only other [report](https://wordpress.org/support/topic/potentially-violating-personal-data-sent-to-facebook-2/) I could find on this is from more than a year ago. We're passing a referrer URL to FB; neither WooCommerce nor we add these additional parameters to the URL. WooCommerce only adds the "key" param and, in some cases, the `utm_nooverride.`

The only other explanation would be that these parameters are added to the IPN URL provided to a payment processor. The closest issue I could find here is related to an old version of [WooCommerce PayPal Checkout Gateway](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/444). This extension has since been phased out in favor of [WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/). 

I will mark this issue as closed. However, feel free to reopen it if you have a new occurrence of the problem or have more details.

**Comment by kokomomtl** [comment]
Hi rawdreeg, we do not have paypal, the only payment processor we are using is stripe...
