### ISSUE TITLE
Facebook Shop Rejected and cannot be published

### ISSUE THREAD

**Issue by Miekvs** [woocommerce/facebook-for-woocommerce#2081]
I am very unhappy. My Facebook Shop has been rejected for some reason and I do not know why and no one can tell me why. I am also told that this is PERMANENT that I will NEVER be able to open a shop on Facebook?? How is that possible? 
Please can you check my profile and help me? I do not see any red flags on my business account and no reason for why it would not meet the eligibility requirements. Please advise me on how to fix this problem.

**Comment by sukafia** [comment]
Hi @Miekvs, I am sorry to hear your Facebook shop has been rejected. However, this platform exists for development issues (e.g bugs) experienced with the Facebook for WooCommerce extension. You'd want to [contact Facebook support](https://www.facebook.com/business/help/900699293402826) for account related queries.
