### ISSUE TITLE
"This shop has added new items."

### ISSUE THREAD

**Issue by Waleedov** [woocommerce/facebook-for-woocommerce#2082]
Why do all my followers see my random products in their feed with this message: "This shop has added new items."
How do I disable this?
This makes people mute me and unfollow me.

**Comment by jconroy** [comment]
Hi @Waleedov 

Thanks for posting and sorry for your difficulties. If you haven't don so please create a support request on woocommerce.com or a [new topic in the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for assistance.

Our happiness team will be better able to support you with this type of question in those locations.
