### ISSUE TITLE
The plugin should use non-blocking calls to Facebook

### ISSUE THREAD

**Issue by Dekadinious** [woocommerce/facebook-for-woocommerce#2094]
As we all are aware, Facebook had issues today. This plugin made our store very slow. Especially choosing variations took a very long time. I believe this is because the plugin makes a call to Facebook each time you want to choose variations, and perhaps on every page load also.

After deactivating the plugin, our store was fast again. We have a high traffic store, and even just a few hours of this slowness hits our conversion rate so hard that we lose tens of thousands of dollars. This happened today.

Can you please look into making the calls to Facebook non-blocking? By that I mean that if Facebook is slow to answer, the plugin should NOT block anyone from choosing variations, loading pages, or making a purchase.

Problems with Facebook should NOT affect an entire WooCommerce-store.

**Comment by vdwijngaert** [comment]
It might be a quick workaround to change the value of this constant to something a lot less than 500 seconds...

https://github.com/woocommerce/facebook-for-woocommerce/blob/fee35c324eefad86177ccfc07ea965abff7909dd/includes/fbgraph.php#L30

**Comment by Dekadinious** [comment]
Yeah, there is just no reason for the WooCommerce store to know if the call to Facebook was a success or not. Don't wait for a response. Send the call non-blocking.

**Comment by lukecav** [comment]
https://github.com/woocommerce/facebook-for-woocommerce/issues/2095

**Comment by jconroy** [comment]
Closing in favor of https://github.com/woocommerce/facebook-for-woocommerce/issues/2095
