### ISSUE TITLE
Product quantity (inventory) in WooCommerce are not synced into Facebook shop

### ISSUE THREAD

**Issue by izonelb** [woocommerce/facebook-for-woocommerce#2097]
Product quantity (inventory) in WooCommerce are not synced into Facebook shop

**Comment by carlaochoa** [comment]
Again and again.... this problem is driving me crazy!!!!

**Comment by budzanowski** [comment]
Hello, 

Thank you for reaching out.

Please provide a detailed scenario of how to duplicate your problem. For example: are you setting quantity in the product manually and updating the product and the plugin does not sync the quantity or does some other event change the quantity and then it does not get synced correctly?

Best regards!

**Comment by gaitagarcia** [comment]
same problem!!!

**Comment by rawdreeg** [comment]
Hello,

Any chance you could give us more info on how to reproduce?

I have set the inventory qty to 0 for one of my test products, and It correctly shows the product as being out of stock:

![Screenshot 2022-07-19 at 12 07 05](https://user-images.githubusercontent.com/4209011/179726693-9823aca5-cdaf-4196-a311-79c4cc22933b.jpg)
![Screenshot 2022-07-19 at 12 06 50](https://user-images.githubusercontent.com/4209011/179726724-fd36a242-2654-43c7-a2d9-b6815b9fc3b4.jpg)

Thanks,
R

**Comment by budzanowski** [comment]
I have checked this as well and the inventory with qty 0 syncs correctly.

Closing as stale. Please reopen with reproduction scenario in case we are missing something.
