### ISSUE TITLE
Orders placed on Facebook don't appear in WooCommerce

### ISSUE THREAD

**Issue by tijosh** [woocommerce/facebook-for-woocommerce#2110]
## ✍️ Describe the bug

Orders are placed through Facebook's checkout but don't appear in WooCommerce orders list. On the Facebook side of things, the messaging says the order "needs to be acknowledged in WooCommerce." 

Order details (like customer name) do not appear in log files if debug logging is enabled. The orders just aren't reaching WooCommerce.

https://wordpress.org/support/topic/order-pending-acknowlegement/

Also 4415708-zen

**Comment by shaunkuschel** [comment]
Received another report of this on 4949194-zen

**Comment by shaunkuschel** [comment]
Also reported on 4959506-zen

**Comment by theabhig** [comment]
5247319-zen

**Comment by solstudioim** [comment]
5469779-zd-woothemes

**Comment by message-dimke** [comment]
#2217 has a possible fix for this, but can not be tested since requires Facebook test account we don't have and can not obtain.

**Comment by theabhig** [comment]
Also in 5247319-zen

**Comment by rawdreeg** [comment]
we've dropped support for Order Sync in #2390. So will close this as won't fix.
