### ISSUE TITLE
Fatal error caused by incompatible function signature

### ISSUE THREAD

**Issue by wojsmol** [woocommerce/facebook-for-woocommerce#2112]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Fatal error: Declaration of SkyVerge\WooCommerce\Facebook\Jobs\GenerateProductFeed::process_item($product, $args) must be compatible with Automattic\WooCommerce\ActionSchedulerJobFramework\AbstractChainedJob::process_item($item, array $args) in /wp-content/plugins/facebook-for-woocommerce/includes/Jobs/GenerateProductFeed.php on line 18
## 🚶‍♀️ Steps to reproduce

1. Install woocomerce - latest stable version - 5.8.0
2. Install facebook-for-woocommerce - 2.6.6
3.  Activate both plugins.
4.  Observe fatal error as posted above.

## ✔️ Expected behavior
no php fatal error - all works as expected 
## 🗃 Logs
N/A IMHO

Relevant code line https://github.com/woocommerce/facebook-for-woocommerce/blob/225d96525f5d3ac9330f597ba17af8041b24082a/includes/Jobs/GenerateProductFeed.php#L114

**Comment by mbeerandon** [comment]
My site went down due to this - exact same error. I had to disable plugin. My site is on autoupdate and this is the first time I have had an issue with plugins.

**Comment by wojsmol** [comment]
@mbeerandon For a quock fix for this fatal or chenge
```php
protected function process_item( $product, $args ) {}
```
to
``php
protected function process_item( $product, array $args ) {}
```
