### ISSUE TITLE
 Variations not syncing

### ISSUE THREAD

**Issue by idowebwork** [woocommerce/facebook-for-woocommerce#2116]
Simple products sync, while those with variations are not. Seems to affect products created as far back as those created September 16, 2021. Attaching a CSV export of one of the variable products which are not getting ID numbers from facebook.

I've done the following: 
- Used both the “Reset Facebook metadata” and “Delete product(s) on Facebook”. Neither caused the variations to re-sync fully.
- Set a few of the products to “Exclude From Facebook Sync” and back to “Include In Facebook Sync” on the product listing admin page with the Bulk Operations dropdown.
- Recreated a new copy of the product

None of this causes Facebook to issue ID numbers for the variations. Some of the products have variations with a zero inventory on some variations, but even ones in stock don't get a variation number. Even products with all in stock variations see the same result.

Attached is a product with 6 variations, only 2 currently in stock.

[woocommerce-product-export-2021_11_09_10_59_56.csv](https://github.com/woocommerce/facebook-for-woocommerce/files/7501125/woocommerce-product-export-2021_11_09_10_59_56.csv)
.

**Comment by idowebwork** [comment]
Forgot the variation
[woocommerce-product-variations-export-2021_11_10_10_57_03.csv](https://github.com/woocommerce/facebook-for-woocommerce/files/7508999/woocommerce-product-variations-export-2021_11_10_10_57_03.csv)
s

**Comment by mircearek** [comment]
No news on this? I also have the same issue on a website and it's so god damn frustrating.

**Comment by idowebwork** [comment]
Completed a full export as requested using Woo's built in export. Really don't like that there is no granular control of exporting only certain products. But that's a Woo issue. Hope this helps!

[wc-product-export-10-11-2021-1636581864172.csv](https://github.com/woocommerce/facebook-for-woocommerce/files/7516244/wc-product-export-10-11-2021-1636581864172.csv)
.

**Comment by jconroy** [comment]
Hi @idowebwork thanks for opening the issue - If you are still pursuing a solution - would you be able to share how many attributes those variations have?

I can see a similar issue here https://github.com/woocommerce/facebook-for-woocommerce/issues/2050#issuecomment-931043127 reported that if there are too many attributes FB won't access the variations.

I'll close for now and recommend creating a support request on woocommerce.com or a [new topic in the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for assistance.

Our happiness team will be better able to support you in those locations and then we can create an issue with relevant information once/if a bug has been isolated.
