### ISSUE TITLE
Events with wrong product ID if a variation is selected as default

### ISSUE THREAD

**Issue by nroccogit** [woocommerce/facebook-for-woocommerce#2117]
Just installed the latest version 2.6.7 to enable Facebook Pixel advanced event tracking and conversion API.
My setup is latest WP, Woocommerce and WPML website.

Step to reproduce:
Suppose to have Product A (id: 450) with two variation:
– Product A Size M (variation id: 2501) => set as default
– Product A Size L (variation id: 2502)

This is what happens when you browse the website:
– view_content should track the content_ids of the preselected/default variation if set. Now it track Product A (id: 450), but, for me, it will be better if content_ids was Product A Size M (variation id: 2501)
– when you add to cart Product A Size M (variation id: 2501) the plugin track correct the content_ids with Product A Size M (variation id: 2501). So this is ok, but not related to previous view_content event… so it sounds like I add to cart a product that I never seen 🙂

This can fire this error in the Facebook related Business Manager: "_Pixel has low event source match rate_"

Moreover... not strictly related to this bug report...  the add to cart event has the value: Product price + Shipping Cost, wich is not very good. I'm expecting to see "value" as the price of the product/s in the cart without shipping costs.

**Comment by rawdreeg** [comment]
This has been fixed by #2279. Closing.
