### ISSUE TITLE
Product description not synced to Facebook in Variable products when attribute uses all caps

### ISSUE THREAD

**Issue by darcie** [woocommerce/facebook-for-woocommerce#2120]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

If the attribute title uses all caps (SIZE: M), this causes the sync to fail as Facebook doesn't allow only uppercase in any field. Facebook seems to see the variation attributes as the only description on the variation. 

>Product description is all capital letters. Please change the description to lowercase in order to allow your product to be synchronized.

Once a description is added in the variation Description or Facebook Description, the variation can be synced. It seems like the product description and short description are ignored. 

## 🚶‍♀️ Steps to reproduce

1. Create a variable product
1. Use ALL CAPS in the attribute name and value (SIZE, XS | S | M | L )
2. Do not complete Description or Facebook Description in any variant
3. Publish the product
3. See an error in Facebook Product Sync that Product description is all capital letters.
4. Add a description to a variation and update the product. The variation has synced. https://d.pr/i/NlqwTM

Additional steps:

1. Change the attribute name to regular case (SIZE to Size)
2. Update the product
3. See that all variations have synced 

## ✔️ Expected behavior

I expected that the main product description/short description would also be used for variable products like it is for simple products. 

4448916-zen

**Comment by budzanowski** [comment]
@darcie Thank you for the issue.

We have a fix ready https://github.com/woocommerce/facebook-for-woocommerce/pull/2121 and we will try to include it in the next release.
