### ISSUE TITLE
The plugin is not purging completed background jobs from wp_options fast enough

### ISSUE THREAD

**Issue by Dekadinious** [woocommerce/facebook-for-woocommerce#2122]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

We had a traffic spike during a campaign, and our site suddenly became very sluggish. We found that this plugin does a slow query very often:

`SELECT COUNT(*)
                        FROM wp_options
                        WHERE option_name LIKE 'wc_facebook_background_product_sync_job_%'
                        AND ( option_value LIKE '%\"status\":\"queued\"%' OR option_value LIKE '%\"status\":\"processing\"%' )`

The index returned about 145 000 rows for this query. Since this is a text search, it's not possible to index this much better in the database. The solution is to reduce the dataset. We saw that 97 % of the dataset was for completed jobs. After deleting those, our site was back up to speed.

After some digging, we found that you have a "heartbeat" that deletes 250 rows every day from this table. This is not nearly enough for large stores. It seems that this plugin is made for smaller stores? Can you increase this number significantly, or maybe not have such a limit at all?

## 🚶‍♀️ Steps to reproduce

Should not be necessary.

## ✔️ Expected behavior

Don't fill the wp_options table with these things. Use your own table, or at the very least delete more per batch. Or better yet, just delete the job when completed rather than setting it to a completed status? You probably want these logs for something, but I don't see what as long as you are already purging them when completed.

## 🗃 Logs

Not relevant.

**Comment by budzanowski** [comment]
@Dekadinious Hi!

You are correct on all fronts. When we have received the plugin for maintenance and development we have identified the jobs problem. Our solution was to ( what you have found ) delete the jobs in a cyclic fashion. It looks like we have underestimated the number of jobs created for big stores. Just out of curiosity: how big is the store you are managing? 

The jobs options are not really used. They are an artifact of the skyverge/wc-plugin-framework plugin framework that someone decided to use a long time ago. We will most likely ( I need to doublecheck if it is OK ) stop storing the completed jobs entirely as you suggest, we will also increase the cleanup speed.

One additional question. Were the 145 000 rows for the options with the status "queued" OR "processing" or for all types: queued, processing, completed?

Best Regards,
Bartosz

**Comment by Dekadinious** [comment]
Thanks for the fast answer. The 145 000 rows were for  all types, because the database needs to search through them all to determine if they have a specific status, even in your query where you are looking for only processing or queued 🙂 At least as far as my understanding of the matter goes 👍

So the 144 000 completed jobs slowed down the query significantly. 

We have about 14 000 products (including variations) 👌

**Comment by Dekadinious** [comment]
I'll just tag you since I forgot @budzanowski  :)

**Comment by rawdreeg** [comment]
I believe we've addressed this issue in #2179. I will go ahead and close this one.
