### ISSUE TITLE
After activation plugin product/post page get error 500 on the admin panel.

### ISSUE THREAD

**Issue by RobertCody** [woocommerce/facebook-for-woocommerce#2126]
Hi!
In the logs the error is related to $product_object, (get_type, get_regular_price...) all of its functions do not work, seems like object is empty. 
The page do not showing some blocks after the problem block. 
Thanks !

**Comment by jconroy** [comment]
Hi @RobertCody 

Thanks for posting and sorry for your difficulties. If you haven't don so please create a support request on woocommerce.com or a [new topic in the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for assistance.

Our happiness team will be better able to support you in those locations.
