### ISSUE TITLE
slug bug on product update

### ISSUE THREAD

**Issue by CedricEnvision** [woocommerce/facebook-for-woocommerce#2127]
Hi,
Here is the bug encountered: when I update a product, the product slug changes to the slug of another product. In the same way the short description, the variations and the price change for another product. When I deactivate the plugin everything is fine. I have the impression that syncronization is malfunctioning and causing changes in some fields of woocommerce product. Can you tell me if there is something to do to fix this bug? Thanks very much.
Regards,
Cedric

**Comment by futyko** [comment]
Hi,

I have the same issue here. 

Product updates only work if I disable 'product sync'.

Could you please check and get back to us?

Thank you!

**Comment by jconroy** [comment]
Going to mark as closed as I suspect it will be the same as #2145 

> this being caused by the Flatsome screen edit product UI, where the other product in question is introduced by one of the Flatsome theme shortcodes. Could you test with a default theme and confirm?

Please open a support tick on woocommerce.com or the [wordpress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you need further assistance.

**Comment by futyko** [comment]
FfW will have the same problem with any theme or plugin shortcode, not just flatsome. It should be fixed by the plugin devs.

**Comment by mattermarketing** [comment]
Agreed - this isn't a theme issue - it's solely related to the Facebook plugin. We run Shopkeeper theme fwiw

**Comment by mattermarketing** [comment]
We've also disabled the sync as per the other threads. It is still misbehaving.
