### ISSUE TITLE
Unlinked products lingering in Facebook catalog

### ISSUE THREAD

**Issue by tijosh** [woocommerce/facebook-for-woocommerce#2129]
## ✍️ Describe the bug

It's possible to have unlinked or “shadow” products in the Facebook catalog which used to be synced but are no longer linked to the WooCommerce site. The IDs of the products on FB don’t match anything in the WooCommerce DB. These products might be a duplicate of an actively-synced product or they may be now-deleted products in WooCommerce. 

In at least one instance (4419208-zen), the shadow products came from the [bug where Draft products were being synced to the FB catalog](https://github.com/woocommerce/facebook-for-woocommerce/issues/1803).

When attempting to delete these products on Facebook, they get this message or a variation of it:
> Permanently remove this item from the catalogue. To delete this item, remove it in the same way that it was added.

Meaning, Facebook is directing the merchant to delete the product from WooCommerce, but there's nothing in WooCommerce to delete.

## 🚶‍♀️ Steps to reproduce

Difficult to reproduce; no known steps at this time.

I've tried reproducing this by disconnecting the Facebook for WooCommerce extension and reconnecting multiple times, deleting products in between, but the products are correctly deleted/updated/synced every time.

**Comment by tijosh** [comment]
4419208-zen , where products were seemingly also left in the catalog after the Draft product sync issue.

**Comment by aheckler** [comment]
4787580-zen also seems like it might be this. In this case, the user has deleted all products from the WC side. They have thousands left on the FB side, but cannot delete them via our code here:

https://woocommerce.com/document/facebook-for-woocommerce-delete-or-reset-all-facebook-products/

... since they don't exist in WC any longer. FB support also told them that they (FB) cannot delete the catalog either "because it was made from woocommerce".

**Comment by tijosh** [comment]
34445004-hc

**Comment by theabhig** [comment]
5251792-zen looks like it is being affected by the same issue

**Comment by theabhig** [comment]
5258121-zen also seems to be having this issue

**Comment by johndcoy** [comment]
The only way around this is to Edit the item from within Facebook, make a minor change to the product, then manually delete it from within Facebook:

![Screenshot](https://d.pr/i/AlToBn+)
Screenshot link: https://d.pr/i/AlToBn

A solution would consist of getting this code to work as expected:

https://woocommerce.com/document/facebook-for-woocommerce-delete-or-reset-all-facebook-products/

Ideally, a "Delete all orphaned products from Facebook" that checks all synced products with published products in WooCommerce and makes a request to delete the item in Facebook otherwise.

**Comment by rawdreeg** [comment]
Great find with the workaround, @johndcoy 

> A solution would consist of getting this code to work as expected:
> 
> [woocommerce.com/document/facebook-for-woocommerce-delete-or-reset-all-facebook-products](https://woocommerce.com/document/facebook-for-woocommerce-delete-or-reset-all-facebook-products/)

I haven't tested this yet, but from the look of it, the script deletes all product still in users DB. In cases where the products are completely deleted (programmatically deleted, for example), some orphan products will remain on the FB catalog.
 
> For sites already experiencing this issue, a nice solution would be to add a feature like "Delete all orphaned products from Facebook" that checks all synced products with published products in WooCommerce and makes a request to delete the item on Facebook otherwise.
> 

The suggestion assumes that the deleted products are still available in the trash, or we keep a reference of all deleted products (in some cases, users have moved sites or the old posts' metadata have been cleared, for example). We can try to get all products in the connected catalog and compare them with all published products and delete the deltas (we'll need a way of confirming the product marked for deletion).

This topic needs more discussions imho.

**Comment by puntope** [comment]
> Adding a conversation I had in here p1655324358160569-slack-C7U3Y3VMY with more info regarding the snippet

@rawdreeg  Since the output of that snippet seems inconsistent one idea coming from that conversation is about adding some WP Debug lines in the snippet with some outputs  to check whats going on in the cases of "not working"

cc: @gabrielbonifacio

**Comment by rawdreeg** [comment]
Thanks @puntope,

> @rawdreeg Since the output of that snippet seems inconsistent one idea coming from that conversation is about adding some WP Debug lines in the snippet with some outputs to check whats going on in the cases of "not working"

Good suggesting. This would be a good start.


@gabrielbonifacio 

> What if we also worked on a tool where the user enters the product ID on a field and then a manual delete operation is triggered? They could get the product ID of the orphaned product from Facebook's catalog.

That's definitely worth exploring. There is also another discussion in #1964 with some [suggestions](https://github.com/woocommerce/facebook-for-woocommerce/issues/1964#issuecomment-861133020) worth exploring.

**Comment by rawdreeg** [comment]
We have fixed a few of the issues that would cause a product to become unlinked:

- #2256 
- #2259

**Comment by rawdreeg** [comment]
@tijosh,

FB now allows bulk deletion from the FB Catalog Manager:

![Screenshot 2022-10-20 at 20 26 17](https://user-images.githubusercontent.com/4209011/197028877-d55fc3d6-cd22-47f9-8c1b-9f126ed15ada.jpg)

Could you confirm? This means we can probably close this issue.

**Comment by tijosh** [comment]
@rawdreeg in my testing, I'm not able to delete items added via WooCommerce:
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/35117248/197032663-9256bd17-4d7e-4c74-b9e0-6a1238717988.png">

**Comment by rawdreeg** [comment]
Ah. Interesting. Maybe this is only available to new catalogs? I haven't been able to confirm. But I try the journey. See attached:


https://user-images.githubusercontent.com/4209011/197043692-82666189-6a07-45e6-a7fb-50794759ab6b.mov

I believe we've covered everything we could from our end, short of deleting catalog items on disconnection, which I don't think we should do.

**Comment by tijosh** [comment]
> short of deleting catalog items on disconnection

It's been a while since I've tested this, but the "Delete all products" snippet previously didn't work to remove the unlinked products on Facebook. Is there a reason that wouldn't be feasible? I agree that deleting the catalog contents on disconnection isn't ideal, but it seems like the snippet should work when conscientiously used. 

In either case, I think the best way forward for any future occurrences would be to:

1. Disconnect the extension
2. Delete the Facebook catalog and create a new one.
3. Reconnect the extension 

There have been a lot of improvements to the extension since this issue was opened, with diminishing occurrences of the original issue.

**Comment by ecgan** [comment]
The PR for this issue has been released in https://github.com/woocommerce/facebook-for-woocommerce/releases/tag/3.0.5.
