### ISSUE TITLE
is_ajax to  be deprecated in WC 6.1.0

### ISSUE THREAD

**Issue by rrennick** [woocommerce/facebook-for-woocommerce#2133]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
`is_ajax()` will be deprecated in WooCommerce 6.1.0. This originally surfaced in https://github.com/woocommerce/woocommerce/pull/31400#issuecomment-996004091. You have three usages: https://github.com/woocommerce/facebook-for-woocommerce/search?q=is_ajax

## 🚶‍♀️ Steps to reproduce

1. Install & activate this plugin with WooCommerce `trunk`

**Comment by iMazed** [comment]
Found in https://wordpress.org/support/topic/the-is_ajax-function-is-deprecated-since-version-6-1-0-replace-wit/ as well!

**Comment by kieron** [comment]
Also seeing this. Wouldn't mind but it prints the message on the front end for some reason, guess that is a WP thing.

**Comment by doominio** [comment]
I'm getting my error_log filled up with this. Also, for whatever reason, it doesn't report which plugin is causing the problem, all I get is this:

`The is_ajax function is deprecated since version 6.1.0. Replace with wp_doing_ajax.`

**Comment by bedewy** [comment]
i also got same error and more :(

 wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php:86
SkyVerge\W\P\v\P\Lifecycle->add_hooks()
wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/Lifecycle.php:69
SkyVerge\W\P\v\P\Lifecycle->__construct()
wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php:37
SkyVerge\W\F\Lifecycle->__construct()
wp-content/plugins/facebook-for-woocommerce/class-wc-facebookcommerce.php:1089
WC_Facebookcommerce->init_lifecycle_handler()
wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/class-sv-wc-plugin.php:154
SkyVerge\W\P\v\SV_WC_Plugin->__construct()
wp-content/plugins/facebook-for-woocommerce/class-wc-facebookcommerce.php:112
WC_Facebookcommerce->__construct()
wp-content/plugins/facebook-for-woocommerce/class-wc-facebookcommerce.php:1105
WC_Facebookcommerce::instance()
wp-content/plugins/facebook-for-woocommerce/class-wc-facebookcommerce.php:1171
facebook_for_woocommerce()
wp-content/plugins/facebook-for-woocommerce/facebook-for-woocommerce.php:129
WC_Facebook_Loader->init_plugin()
wp-includes/class-wp-hook.php:303
do_action('plugins_loaded')
wp-settings.php:441

**Comment by jconroy** [comment]
Closing - this should have been fixed in https://github.com/woocommerce/facebook-for-woocommerce/pull/2140 which was released in version 2.6.9  on 15 Jan 2022
