### ISSUE TITLE
Error returned at end of Configuration

### ISSUE THREAD

**Issue by HerveKL** [woocommerce/facebook-for-woocommerce#2134]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

![image](https://user-images.githubusercontent.com/96332437/146635102-a4191d72-a671-49a6-8cb5-0d8b1ea6004d.png)
![image](https://user-images.githubusercontent.com/96332437/146635121-03bfa318-43e6-4a9d-a6ae-c7b53d4d7029.png)

## 🚶‍♀️ Steps to reproduce

Error page returned after configuration steps completed successfully.

## 🗃 Logs

<details>
	
2021-12-18T08:22:51+00:00 CRITICAL Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/hilltost/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Marketing.php:270
Stack trace:
#0 /home/hilltost/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Marketing.php(270): count(NULL)
#1 /home/hilltost/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Marketing.php(118): Automattic\WooCommerce\Admin\Features\Marketing->get_knowledge_base_posts('marketing')
#2 /home/hilltost/public_html/wp-includes/rest-api/class-wp-rest-server.php(1140): Automattic\WooCommerce\Admin\API\Marketing->get_knowledge_base_posts(Object(WP_REST_Request))
#3 /home/hilltost/public_html/wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc-admin/marke...', Array, NULL)
#4 /home/hilltost/public_html/wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch(Object(WP_REST_Request))
#5 /home/hilltost/public_html/wp-includes/rest-api.php(370): WP_REST_Server->serve_request('/wc-admin/marke...')
#6 /home/hilltost/public_html/wp-includes/class-wp-hook.php(303): rest_api_loaded(Object(WP))
#7 /home/hilltost/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#8 /home/hilltost/public_html/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#9 /home/hilltost/public_html/wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#10 /home/hilltost/public_html/wp-includes/class-wp.php(750): WP->parse_request('')
#11 /home/hilltost/public_html/wp-includes/functions.php(1291): WP->main('')
#12 /home/hilltost/public_html/wp-blog-header.php(16): wp()
#13 /home/hilltost/public_html/index.php(17): require('/home/hilltost/...')
#14 {main}
  thrown in /home/hilltost/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Marketing.php on line 270

</details>

**Comment by jconroy** [comment]
Hi please create a support request on woocommerce.com or a [new topic in the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for assistance.

Our happiness team will be better able to support you in those locations.
