### ISSUE TITLE
Plugin Not sending Server Event

### ISSUE THREAD

**Issue by ankit-enalito** [woocommerce/facebook-for-woocommerce#2138]
When server-side tracking is properly configured we should be able to see both Browser and Server being mentioned for all events. Like the add to cart one indicated below.

![FB-Server-Event-Issue](https://user-images.githubusercontent.com/68953812/147934407-0ac80217-c22e-4fc0-b0fa-fbe141f2727d.png)

And since all other events don't appear in a similar manner, we know there's an issue.

The server event is not sent properly by Facebook For WooComerce plugin. So Can you please let me know what will be the issue?

**Comment by rawdreeg** [comment]
No longer reproducible. Please re-open if this is still an issue.
