### ISSUE TITLE
Sites using the Turkish language and Turkish lira (₺) cannot connect properly

### ISSUE THREAD

**Issue by csmcneill** [woocommerce/facebook-for-woocommerce#2139]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When a merchant whose WooCommerce site language is set to Turkish and their currency is set to the Turkish lira (₺), they cannot connect to Facebook. When they attempt to do so, no information appears under **Marketing > Facebook > Connection**.

![Markup on 2022-01-03 at 09:46:51](https://user-images.githubusercontent.com/82999806/147952173-8ea31560-34a9-4b80-9b65-0dd818fc0683.png)

## 🚶‍♀️ Steps to reproduce

1. Set the site language to Turkish.
2. Set the currency to the Turkish lira (₺).
3. Connect to Facebook.
4. Return to the site after the connection is complete.
5. Note that no details are visible on **Marketing > Facebook > Connection**.

## ✔️ Expected behavior

Merchants should be able to connect to Facebook when using Turkish and the Turkish lira.

## 🗃 Logs

`01-03-2022 @ 15:43:15 - Unable to detect valid feed configuration: No catalog ID`

## 📝 Notes

We've found that the only way to resolve this issue is to change to English/USD, disconnect Facebook, reconnect, and then change the language/currency _after_ successfully connecting and ensuring that all of the information populates properly in **Marketing > Facebook > Connection**.

When I made the initial connection using Turkish and the Turkish lira on my JN site, I saw the following errors displayed on the page, but I cannot determine if this is displayed for every merchant experiencing this issue:

```
Notice : Undefined offset: 0 in /srv/users/user918de7ea/apps/user918de7ea/public/wp-content/plugins/facebook-for-woocommerce/includes/API/FBE/Installation/Read/Response.php on line 149

Notice : Undefined property: stdClass::$pages in /srv/users/user918de7ea/apps/user918de7ea/public/wp-content/plugins/facebook-for-woocommerce/includes/API/FBE/Installation/Read/Response.php on line 87

Notice : Undefined offset: 0 in /srv/users/user918de7ea/apps/user918de7ea/public/wp-content/plugins/facebook-for-woocommerce/includes/API/FBE/Installation/Read/Response.php on line 149

Notice : Undefined offset: 0 in/srv/users/user918de7ea/apps/user918de7ea/public/wp-content/plugins/facebook-for-woocommerce/includes/API/FBE/Installation/Read/Response.php on line 149

Notice : Undefined offset: 0 in /srv /users/user918de7ea/apps/user918de7ea/public/wp-content/plugins/facebook-for-woocommerce/includes/API/FBE/Installation/Read/Response.php on line 149

Notice : Undefined offset: 0 in /srv/users /user918de7ea/apps/user918de7ea/public/wp-content/plugins/facebook-for-woocommerce/includes/API/FBE/Installation/Read/Response.php on line 149

Notice : Undefined offset: 0 in/srv/users/user918de7ea/apps/user918de7ea/public/wp-content/plugins/facebook-for-woocommerce/includes/API/FBE/Installation/Read/Response.php on line 149

Notice : Undefined offset: 0 in /srv /users/user918de7ea/apps/user918de7ea/public/wp-content/plugins/facebook-for-woocommerce/includes/API/FBE/Installation/Read/Response.php on line 149
```

Affected tickets thus far:

- 4636857-zen
- 4637776-zen
- 4640292-zen

<details>
`
### WordPress Environment ###

WordPress address (URL): https://intimate-orca.jurassic.ninja
Site address (URL): https://intimate-orca.jurassic.ninja
WC Version: 6.0.0
REST API Version: ✔ 6.0.0
WC Blocks Version: ✔ 6.3.3
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.9.4
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.27
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.0.0
WC Database Prefix: wp_
Total Database Size: 4.82MB
Database Data Size: 3.37MB
Database Index Size: 1.45MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Companion Plugin: by Osk – 1.21
Facebook for WooCommerce: by Facebook – 2.6.8
Jetpack: by Automattic – 10.4
WooCommerce: by Automattic – 6.0.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.2.1
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2022-01-03 15:42:26 +0000
Newest: 2022-01-03 15:43:15 +0000

### Status report information ###

Generated at: 2022-01-03 15:56:45 +00:00
`
</details>

**Comment by odskaren** [comment]
I am having this same problem. In the English side.  I can not get it to link back with my Facebook. The last button Return to WooCommerce Integration does not work.

**Comment by solstudioim** [comment]
As reported here as well: https://wordpress.org/support/topic/pixel-and-ad-account-information-not-visible/

**Comment by aliosmanyuksel** [comment]
> As reported here as well: https://wordpress.org/support/topic/pixel-and-ad-account-information-not-visible/

It's not working for me.

**Comment by muhammedyagci** [comment]
same problem

**Comment by simplysaru** [comment]
Another issue in 4908767-zen

**Comment by message-dimke** [comment]
Hi, @maxdupenois !

Depending on WP language the User-Agent header to Facebook API changes. 

WP in English: `WooCommerce-for-Facebook/2.6.12 (WooCommerce/6.3.1; WordPress/5.9.3)`
WP in Turkish: `WooCommerce-için-Facebook/2.6.12 (WooCommerce/6.3.1; WordPress/5.9.3)`

Turkish is failing with a 400 response.

Does Facebook use User-Agent to track something? 
We can cleanup non-latin characters into `WooCommerce-icin-Facebook` or have it `WooCommerce-for-Facebook` between the languages.

**Comment by shohanhossainnab** [comment]
A related report in 5162034-zen. The merchant reported that the Facebook extension does not add the products to the catalog. When they change the site language to English and the currency to USD, the products sync correctly in the catalog. The current workaround is to manually convert the prices of all products to Turkish Lira and change the site language back to Turkish
