### ISSUE TITLE
Stock No Sincronize in Shop.

### ISSUE THREAD

**Issue by gaitagarcia** [woocommerce/facebook-for-woocommerce#2144]
Hi, sory my bad english.
I see that in my site ( woocommerce ) the stock in products is 0 but in the facebook shop only say that is Available. 
This error it allows the customers can buy in facebook shop, but i dont have stock in my woocomerce.
PLease Help me. 
Thanks

**Comment by jconroy** [comment]
Related https://github.com/woocommerce/facebook-for-woocommerce/issues/2097

**Comment by rawdreeg** [comment]
Hi @gaitagarcia,

Any chance you could give us more info on how to reproduce?

I have set the inventory qty to 0 for one of my test products, and It correctly shows the product as being out of stock:

![Screenshot 2022-07-19 at 12 07 05](https://user-images.githubusercontent.com/4209011/179726693-9823aca5-cdaf-4196-a311-79c4cc22933b.jpg)
![Screenshot 2022-07-19 at 12 06 50](https://user-images.githubusercontent.com/4209011/179726724-fd36a242-2654-43c7-a2d9-b6815b9fc3b4.jpg)

Thanks,
R

**Comment by rawdreeg** [comment]
Will close in favor of #2097
