### ISSUE TITLE
Error: "Deprecated: is_ajax is deprecated since version 6.1.0!"

### ISSUE THREAD

**Issue by smmilrigattiere** [woocommerce/facebook-for-woocommerce#2146]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

After updating the last version of the plugin, if we activate Facebook for WooCommerce we can't login to the website's backend. We receive this error message: "_Deprecated: is_ajax is deprecated since version 6.1.0! Use wp_doing_ajax instead. in /home2/kmilriga/public_html/wp-includes/functions.php on line 5211_"
If the plugin is disabled we can enter on the website backend as usual. 

<details>
	
</details>

**Comment by jconroy** [comment]
Closing as a duplicate of https://github.com/woocommerce/facebook-for-woocommerce/issues/2133
