### ISSUE TITLE
Handling multiple Facebook catalogues - Products disappeared in one

### ISSUE THREAD

**Issue by OriginalUserName** [woocommerce/facebook-for-woocommerce#2149]
Hi,

We have two catalogues on our business account : 

- One which is automatically synchronized using the module, containing all our WooCommerce products.
- One we created manually, containing a few products we added manually. We use it for automatic social campaigns based on this catalogue's products.

The issue is that all our products disappeared from the manual catalogue, causing our Facebook ads to deactive themselves. In emergency, we added the products back to reactivate our campaigns. 

How can we prevent this from happening again, and is there something we did wrong in the configuration of the module ? Is there a better way to handle multiple catalogues ?

Thank you for your feedback.

**Comment by jconroy** [comment]
Hi @OriginalUserName !

Thanks for opening an issue. I this case it's hard to tell what's happening without working with you to get more information and this github repo isn't the best place for support like that.

Please head over to [woocommerce.com](woocommerce.com) to open a support ticket or [use our support forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/).

Cheers.
