### ISSUE TITLE
Scheduled products aren't syncing to Facebook automatically

### ISSUE THREAD

**Issue by anant1811** [woocommerce/facebook-for-woocommerce#2150]
- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When a product is scheduled to be published at a later time, it doesn't sync to Facebook automatically after it's published. But when you manually sync the product by clicking the "Sync Products" button, it syncs. 

## 🚶‍♀️ Steps to reproduce

1.  Scheduled a variable and a simple product
2.  Published on schedule
3.  Product did not sync to Facebook, but generated an error
4.  When the regenerate feeds job was run, the same error occurred and the item was not published to Facebook

    01-25-2022 @ 10:30:09 - Generating a fresh product feed file
    01-25-2022 @ 10:30:09 - Product feed file generated
    01-25-2022 @ 10:30:20 - Request
    uri: https://graph.facebook.com/v11.0/catalog:519813615893065:d2NfcG9zdF9pZF83OTk=/?fields=id,product_group{id}
    timeout: 500
    
    01-25-2022 @ 10:30:20 - Response
    code: 400
    message: Bad Request
    body: {"error":{"message":"(#100) Could not find Product Item for catalog id 519813615893065, retailer id wc_post_id_799","type":"OAuthException","code":100,"fbtrace_id":"AUpy95ZtzB0L5vpz5ItUxWs"}}
    

1.  When the product was updated (just hit the update button) it was published to Facebook

## ✔️ Expected behavior

The product should sync with Facebook automatically after they are published. 

Reported in 4704048-zen

**Comment by mitchellkrogza** [comment]
Same problem, I had to open the auto published product again and click update to make it sync.

**Comment by jonasborneland** [comment]
Im also still struggling with this
