### ISSUE TITLE
Parse error in facebook-commerce.php on line 709 - plugin version 2.6.10

### ISSUE THREAD

**Issue by wojsmol** [woocommerce/facebook-for-woocommerce#2157]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Parse error: syntax error, unexpected ')' in /wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 709
## 🚶‍♀️ Steps to reproduce
1. Install woocomerce - latest stable version - 5.9.1
2. Install facebook-for-woocommerce - 2.6.10
3.  Activate both plugins.
4.  Observe fatal error as posted above.
## ✔️ Expected behavior
No parse error -all works as expected

## 🗃 Logs
N/A

relevant core part
https://github.com/woocommerce/facebook-for-woocommerce/blob/5c12461928b3dd561c82a807febdc5ea1aaadf6b/facebook-commerce.php#L706-L709

changing this part to
```php
 $block_sync = apply_filters( 
 	'facebook_for_woocommerce_block_full_batch_api_sync', 
 	false
 ); 
```
fixes this issue for me

## Environment details
WordPress 5.9. - latest on the time of plugin update  - also occurs on WP 5.9.1
WooCommerce: 6.2.0
Facebook for WooCommerce:2.6.10
PHP Version: 7.1.9

**Comment by wojsmol** [comment]
More detailed environment details added in first post.

**Comment by matthewmeaklim** [comment]
Hi,

As requested by Wojciech Smoliński, please see exact plugin versions.

WordPress Version: 5.9.1
WooCommerce Version: 6.2.1
Facebook for WooCommerce Version: 2.6.10

PHP Version: 7.4.26
MySQL Version: 10.5

Thanks,

Matthew

**Comment by casset-id** [comment]
> ## 🔎 Isolate the bug
> 
>     * [x]  I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
> 
>     * [x]  I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.
> 
> 
> ## ✍️ Describe the bug
> 
> Parse error: syntax error, unexpected ')' in /wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 709
> ## 🚶‍♀️ Steps to reproduce
> 
>     1. Install woocomerce - latest stable version - 5.9.1
> 
>     2. Install facebook-for-woocommerce - 2.6.10
> 
>     3. Activate both plugins.
> 
>     4. Observe fatal error as posted above.
> 
> 
> ## ✔️ Expected behavior
> 
> No parse error -all works as expected
> ## 🗃 Logs
> 
> N/A
> 
> relevant core part
> 
> https://github.com/woocommerce/facebook-for-woocommerce/blob/5c12461928b3dd561c82a807febdc5ea1aaadf6b/facebook-commerce.php#L706-L709
> 
> changing this part to
> 
> ```
>  $block_sync = apply_filters( 
>  	'facebook_for_woocommerce_block_full_batch_api_sync', 
>  	false
>  ); 
> ```
> 
> fixes this issue for me
> ## Environment details
> 
> WordPress 5.9. - latest on the time of plugin update - also occurs on WP 5.9.1 WooCommerce: 6.2.0 Facebook for WooCommerce:2.6.10 PHP Version: 7.1.9

This solution works for all of my site. Thanks.

**Comment by jconroy** [comment]
Thanks @wojsmol we'll aim to get a fix out for this asap

**Comment by eason9487** [comment]
Hi @wojsmol 👋 

Thanks for the detailed information! [Plugin version 2.6.11](https://github.com/woocommerce/facebook-for-woocommerce/releases/tag/2.6.11) was released to fix this issue.
