### ISSUE TITLE
rich_text_description field for product descriptions 

### ISSUE THREAD

**Issue by shrelf** [woocommerce/facebook-for-woocommerce#2159]
## Feature requests
Hi,
Currently, no rich text product descriptions are possible, resulting in unstructured, messy and even completely unreadable descriptions on facebook and instagram.

However, a **rich_text_description** field in feeds is supported by facebook:
https://en-gb.facebook.com/business/help/2302017289821154?id=725943027795860

Please add this to the plugin!
Just one more input field under the "Facebook Description" field on the product edit page would do the job.

Thanks.

**Comment by jconroy** [comment]
Hi @shrelf thanks!

Can you please add your idea/feature suggestion to the ideas board please?

https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=398356

Cheers
