### ISSUE TITLE
I made an update yesterday and it blocked my access to my Dashbord Wordpress. The extension has a problem. I had to deactivate it to access my Dashboard. Please fix this issue soon

### ISSUE THREAD

**Issue by rafik-10** [woocommerce/facebook-for-woocommerce#2161]

**Comment by wojsmol** [comment]
@rafik-10 Please see https://github.com/woocommerce/facebook-for-woocommerce/issues/2157 there is a temporary fix for this in the first post. If the fix works for you then post your environment details in mentioned issue.

**Comment by jconroy** [comment]
Assuming this is a duplicate of https://github.com/woocommerce/facebook-for-woocommerce/issues/2157 - closing for now unless there is more information/a different error to add
