### ISSUE TITLE
After a product is set to "do not sync" the items gets rejected for dynamic ads by Facebook

### ISSUE THREAD

**Issue by rashedripon** [woocommerce/facebook-for-woocommerce#2163]
## 🔎 Isolate the bug

- [ ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
After a product is set to "do not sync" the items get rejected for dynamic ads by Facebook. This happens as soon as they change the setting in the individual product in WooCommerce.

Not sure if changing the sync setting can affect ads eligibility. Would like to know if this is a problem with our extension.

## 🚶‍♀️ Steps to reproduce

1. Change the sync settings of a product in WooCommerce to "Do not sync"
2. Immediately, the product gets rejected for dynamic ads

![If this image fails to load, please visit:](https://d.pr/i/DM2X7A+)
Image Link: https://d.pr/i/DM2X7A

The product has to be submitted for review manually again when this happens.

## ✔️ Expected behavior

Updating sync settings should not affect dynamic ad eligiblity.

## Discussions

It was reported first on 4789916-zen and discussed internally slack-p1645536761506389-slack-C7U3Y3VMY

**Comment by sukafia** [comment]
I've tested this issue on my end and couldn't replicate it.

Sync settings: https://d.pr/i/ND14YJ
Dynamic ads eligibility on FB: https://d.pr/i/I6RrlV

I've waited for minutes and the product is still eligible for dynamic ads. 
(I think what will likely happen is that the product will be removed from the catalog later since it's set not to sync. )

**Comment by budzanowski** [comment]
> (I think what will likely happen is that the product will be removed from the catalog later since it's set not to sync. )

That is true.

Closing until we will get additional details, for now, it looks like there is nothing that we can do here.
