### ISSUE TITLE
Delete Facebook Shop via Woocommerce

### ISSUE THREAD

**Issue by gtriantafyllou** [woocommerce/facebook-for-woocommerce#2167]
Hello, 

I hope you are all well. 

Our client has set up Facebook Shop via integration with Woocommerce. 

Now, she wants to delete the current Facebook Shop and create a new one. 

We know that a Facebook Shop created via Woocommmerce, can only be deleted via Woocommerce settings, not through Business Manager or Facebook. 

The problem is, that their developer has uninstalled the plugin, but still, the Facebook Shop appears on their Facebook Page.

Can you please advise us on how to proceed, in order to delete the Shop? 
We would like to know the required steps, now that the plugin is already unistalled. 

Thank you in advance

**Comment by jconroy** [comment]
Hi @gtriantafyllou the best place to get support is via our correct support channels on WordPress.org and/or WooCommerce.com - I believe I've seen this question come through since this posting so I will close it out and discussion can continue via those channels.
