### ISSUE TITLE
Are Microdata tags required?

### ISSUE THREAD

**Issue by MaximePHAMTHANH** [woocommerce/facebook-for-woocommerce#2175]
Hi everyone, 
I've correctly installed Facebook for Woocommerce but my catalogue doesn't sync.
My research have lead me to think that the pixel, though active, doesn't send the correct data to FB.

I've tried to manually debug the pixel and the FB helper says the microdata tags on my WP site are missing: id, price and availability.
(link to the helper: https://business.facebook.com/ads/microdata/debug?url=)

Therefore my question: is modifying the microdata for products on my WP mandatory for this plugin to work, or am I searching in the wrong direction?
It would seem odd that everyone with this plugin went into the trouble of doing this, but maybe some themes come with microdata already correctly setup, idk

Side note: article about microdata from FB: https://developers.facebook.com/docs/marketing-api/catalog/guides/microdata-tags

**Comment by jconroy** [comment]
Hi @MaximePHAMTHANH thanks for reaching out. The best place to get help from our happiness engineers is via the WordPress.org forums or WooCommerce.com support channels. Please reach out to one of our team members there.
