### ISSUE TITLE
Problem with integration.

### ISSUE THREAD

**Issue by camiloecheverry11** [woocommerce/facebook-for-woocommerce#2177]
Hi. We are try to reconnect the plugin but we are getting admin permission required. you don't have permission to edit these settings. reach out to the admin of www.

Thanks

We’re happy to help with this question! Our support team works in our help desk rather than GitHub, though, so please use one of the following tools instead:

## 📖 Read documentation

The [Facebook for WooCommerce documentation](https://docs.woocommerce.com/document/facebook-for-woocommerce/) will help you set up the extension, use its features, and answer frequently asked questions. 

## 👩‍💻 Check forums

The [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) let you review other user questions and issues and learn what worked for them. 

## 🗣 Contact support

Our support team would be happy to help answer your questions! [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)

**Comment by jconroy** [comment]
Hi @camiloecheverry11 thanks for getting in touch and sorry to hear of your difficulties. The best place to get help from our happiness engineers is via the WordPress.org forums or WooCommerce.com support channels.
