### ISSUE TITLE
error verifying domain who is already verified

### ISSUE THREAD

**Issue by ivan-vilches** [woocommerce/facebook-for-woocommerce#2178]
Hello i am using this plugin, when i click on the pixel on data origins it show me like the domain is not verified and i click on verify domain but is already verified. please check the images and sorry for my english.
thanks you
![1](https://user-images.githubusercontent.com/982720/160957248-4eda835e-bb5d-466b-9f78-a11faac0b992.png)
![2](https://user-images.githubusercontent.com/982720/160957274-f67dd52d-217a-4dd6-a20a-17804b156f3b.png)
* also i noticed in the panel for configuring web events it show me this domain and i dont know where it come from
mysite.com.translate.goog

thanks you

**Comment by jconroy** [comment]
Hi @ivan-vilches thanks for getting in touch and sorry for your difficulties. The best place to get support from our happiness engineers is via the WordPress.org forums or through WooCommerce.com channels. Please start a thread there and someone should be able to continue helping you out.
