### ISSUE TITLE
Scheduled job logs written to options table are never removed if job does not complete

### ISSUE THREAD

**Issue by nicdwilson** [woocommerce/facebook-for-woocommerce#2179]
## 🔎 Isolate the bug

- [ x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Data stored to the options table as `wc_facebook_background_product_sync_job` is removed from the table on a daily basis by the code [here](https://github.com/woocommerce/facebook-for-woocommerce/blob/0e7b598eaff2ef27bb728ad5c099f03e149bc223/includes/Jobs/CleanupSkyvergeFrameworkJobOptions.php#L39).

They are only removed when the job has the status `completed`. This means that jobs with other statuses are never removed, resulting in excessive options table entries.

Sample entry from 4811711-zen

` {"requests":{"p-0":"UPDATE",....snip...,"status":"failed","started_processing_at":"2021-11-16 11:51:39","updated_at":"2021-11-16 11:51:41","total":42,"progress":42,"handles":["redacted"],"completed_at":"2021-11-16 11:51:41","failed_at":"2021-11-16 11:51:43","failure_reason":"Uncaught Exception: Job data key \"requests\" not set in \/var\/www\/html\/wp-content\/plugins\/facebook-for-woocommerce\/includes\/Products\/Sync\/Background.php:69\nStack trace:\n#0 \/var\/www\/html\/wp-content\/plugins\/facebook-for-woocommerce\/vendor\/skyverge\/wc-plugin-framework\/woocommerce\/utilities\/class-sv-wp-background-job-handler.php(588): SkyVerge\\WooCommerce\\Facebook\\Products\\Sync\\Background->process_job()\n#1 \/var\/www\/html\/wp-content\/plugins\/facebook-for-woocommerce\/vendor\/skyverge\/wc-plugin-framework\/woocommerce\/utilities\/class-sv-wp-background-job-handler.php(168): SkyVerge\\WooCommerce\\PluginFramework\\v5_10_0\\SV_WP_Background_Job_Handler->handle()\n#2 \/var\/www\/html\/wp-includes\/class-wp-hook.php(303): SkyVerge\\WooCommerce\\PluginFramework\\v5_10_0\\SV_WP_Background_Job_Handler->maybe_handle()\n#3 \/var\/www\/html\/wp-includes\/class-wp-hook.php(327): WP_Hook->apply_filters()\n#4 \/var\/www\/html\/wp-includes\/plugin.php(470): WP_Hook->do_action()\n#5 \/var\/www\/html\/wp-admin\/admin-ajax.php(202): do_action()\n#6 {main}\n thrown"} `

## ✔️ Expected behavior
The options table should not be used to store logs

## 🗃 Reference
4811711-zen (several thousand log entries)

**Comment by jconroy** [comment]
Thanks @nicdwilson
