### ISSUE TITLE
Something went wrong when connecting to facebook!

### ISSUE THREAD

**Issue by ebwebsteem** [woocommerce/facebook-for-woocommerce#2180]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [  ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.  -> No the teme I am using is "Blossom Spa Pro" by Blossom Themes.

## ✍️ Describe the bug

When I want to sync products from my WooCommerce catalog to Facebook, I connect myself to Facebook from the back-office of the Facebook plugin. Everything seems to be fine, but at the end, I have this message : "Could not retrieve Facebook Business Extension System User". (screenhot here: https://www.screencast.com/t/LfHGKnu7g).
But actually WooCommerce is well associated with my Facebook page (proof here: https://www.screencast.com/t/f2Xnydh6plcm).
The thing is that at the end, I can never sync my WooCommerce products. I precise that my Facebook catalog is empty.

## 🚶‍♀️ Steps to reproduce

I just follow the all connection process to Facebook from the Facebook plugin back-office.

## ✔️ Expected behavior

My WooCommerce products should appear in my Facebook Shop!

## 🗃 Logs

<details>
	`
### WordPress Environment ###

WordPress address (URL): https://leboudoirdannabel.fr
Site address (URL): https://leboudoirdannabel.fr
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.25
PHP Post Max Size: 130 Mo
PHP Time Limit: 165
PHP Max Input Vars: 16000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.6.50-log
Max Upload Size: 128 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Post Type Counts ###

attachment: 997
blossom-portfolio: 9
custom_css: 1
customize_changeset: 1
elementor_library: 2
giftcard: 4
nav_menu_item: 48
page: 28
post: 2
product: 502
product_variation: 996
revision: 1229
shop_order: 6
sln_attendant: 2
sln_booking: 887
sln_service: 83
wp_global_styles: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

All in One SEO Pack: par All in One SEO Team – 4.1.9.4
Beautiful and responsive cookie consent: par Beautiful Cookie Banner – 2.7.2
BlossomThemes Toolkit: par blossomthemes – 2.2.2
Boxtal Connect: par API Boxtal – 1.2.12
Elementor Pro: par Elementor.com – 3.6.4
Elementor: par Elementor.com – 3.6.1
ELEX Dynamic Pricing and Discounts for WooCommerce: par ELEX – 3.7.7
WP All Export - User Export Add-On: par Soflyy – 1.0.0
Facebook for WooCommerce: par Facebook – 2.6.12
Site Kit by Google: par Google – 1.71.0
HM Multiple Roles: par HM Plugin – 1.6
Smash Balloon Instagram Feed: par Smash Balloon – 6.0.4
Jetpack: par Automattic – 10.7
Limit Login Attempts Reloaded: par Limit Login Attempts Reloaded – 2.24.0
Loco Translate: par Tim Whitlock – 2.6.1
PW WooCommerce Gift Cards: par Pimwick
LLC – 1.202

Redirection: par John Godley – 5.2.3
Salon Booking Wordpress Plugin - Free Version: par Salon Booking System – 7.5
UpdraftPlus - Sauvegarde/Restauration: par UpdraftPlus.Com
DavidAnderson – 1.22.11

Widget for Google Reviews: par RichPlugins  – 2.1.4
WooCommerce Stripe Gateway: par WooCommerce – 6.3.0
Hiboutik: par Hiboutik & Murelh Ntyandi – 1.2.1
WooCommerce Shipping & Tax: par WooCommerce – 1.25.25
WooCommerce: par Automattic – 6.3.1
WP All Export: par Soflyy – 1.3.4
WP Fastest Cache: par Emre Vona – 0.9.9
Widgets d'avis Google: par Trustindex.io  – 8.2.2
WPForms Lite: par WPForms – 1.7.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)
wgm_gift_card (wgm_gift_card)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #6 - /boutique/
Panier: #7 - /panier/
Commander: #8 - /commander/
Mon compte: #9 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Blossom Spa Pro
Version: 2.3.0
Author URL: https://blossomthemes.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Terminé: 1 985
Oldest: 2022-03-02 10:39:10 +0100
Newest: 2022-04-01 13:20:31 +0200

En attente: 7
Oldest: 2022-04-01 13:35:31 +0200
Newest: 2022-04-03 06:55:33 +0200

### Status report information ###

Generated at: 2022-04-01 13:31:16 +02:00
`
</details>

**Comment by jconroy** [comment]
Hi @ebwebsteem sorry to hear of your difficulties. The best place to get support with one of our happiness engineers is via the WordPress.org forums or through the WooCommerce.com support channels. Please start a topic there.
