### ISSUE TITLE
Blank Id Numbers

### ISSUE THREAD

**Issue by muhammedyagci** [woocommerce/facebook-for-woocommerce#2181]
Hello, it says installation completed successfully, but the pixel installation does not occur and all the information that the Id numbers should contain is blank.
https://www.screencast.com/t/Kuz6Q2AB0O

**Comment by jconroy** [comment]
Hi @muhammedyagci the best place for support is via the wordpress.org forums and WooCommerce.com support channels. Our team will be best suited to helping you there. If a bug is identified they'll be open an issue with some more detailed information.
