### ISSUE TITLE
Facebook doesn't show up in the new navigation

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/facebook-for-woocommerce#2184]
## 🔎 Isolate the bug

If we go to WooCommerce > Setttings > Advanced > Features and enable the Navigation option, Facebook doesn't show under Extensions. Instead it shows `FB Product Sets` which is part of the old menu.

![image](https://user-images.githubusercontent.com/11388669/162208780-79d38377-9cb9-4d26-bd5a-9eb036c4248d.png)

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## 🚶‍♀️ Steps to reproduce

1. Activate the Facebook plugin
2. Go to WooCommerce > Setttings > Advanced > Features and enable the Navigation option
3. View the new navigation menu and confirm Facebook doesn't show under Extensions

## ✔️ Expected behaviour

I tested by temporarily moving the line `$this->use_woo_nav = ...` to within the `add_menu_item` function and then it does appear.

![image](https://user-images.githubusercontent.com/11388669/162209566-3b674d48-5162-49bb-a659-71ccb2c975cf.png)

So at first glance it looks like the code to detect the feature is called too early, not sure which init hook would be best to use instead tough.

**Comment by rawdreeg** [comment]
@mikkamp moving this into the `admin_menu` hook seem perfectly reasonable. I see that is the approach some of the other extensions are taking. 

Alternatinatively,  the [init](https://github.com/woocommerce/facebook-for-woocommerce/blob/master/class-wc-facebookcommerce.php#:~:text=)%3B-,%24this%2D%3Einit()%3B,-%7D) function could be run on init.
