### ISSUE TITLE
Loco translation plugin does not synchronize when active

### ISSUE THREAD

**Issue by tarikyalcinkaya** [woocommerce/facebook-for-woocommerce#2186]
## 🔎 Isolate the bug

- [ x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
I noticed that because the plugin changed the user agent, it did not synchronize. I fixed this by doing it manually myself.

https://snipboard.io/CWUGDL.jpg
https://wordpress.org/support/topic/if-the-site-is-in-turkish-it-does-not-synchronize

**Comment by message-dimke** [comment]
Hi, @tarikyalcinkaya 

There is a pull request which has been merged and is waiting for the release.
[Forcing latin characters into user-agent http request header.](https://github.com/woocommerce/facebook-for-woocommerce/pull/2192)
