### ISSUE TITLE
Plugin is faulty. Do not deed the correct product warehouse, overrides the price.

### ISSUE THREAD

**Issue by Zemislav** [woocommerce/facebook-for-woocommerce#2187]
## 🔎 Isolate the bug

- [ y] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [y ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
The plugin is error. Cannot correctly load a warehouse for the product. Product price cannot be rewritten. It shows that the product is composed but the product is simple. Plugin rewrite  product LINK. See video! Please correct it urgently.

https://youtu.be/xSyagFHJtU8

### wp-core ###

version: 5.9.3
site_language: sk_SK
user_language: sk_SK
timezone: Europe/Bratislava
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www6/p5802/monq.sk/web
wordpress_size: 585,76 MB (614213990 bytes)
uploads_path: /var/www6/p5802/monq.sk/web/wp-content/uploads
uploads_size: 200,46 MB (210198975 bytes)
themes_path: /var/www6/p5802/monq.sk/web/wp-content/themes
themes_size: 16,07 MB (16854702 bytes)
plugins_path: /var/www6/p5802/monq.sk/web/wp-content/plugins
plugins_size: 187,76 MB (196877046 bytes)
database_size: 32,95 MB (34553856 bytes)
total_size: 1&nbsp;023,01 MB (1072698569 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Flatsome Child (flatsome-child)
version: 3.0
author: UX Themes
author_website: (undefined)
parent_theme: Flatsome (flatsome)
theme_features: core-block-patterns, post-thumbnails, woocommerce, title-tag, automatic-feed-links, customize-selective-refresh-widgets, sensei, html5, menus, post-formats, widgets
theme_path: /var/www6/p5802/monq.sk/web/wp-content/themes/flatsome-child
auto_update: Zakázané

### wp-parent-theme ###

name: Flatsome (flatsome)
version: 3.15.4
author: UX-Themes
author_website: http://www.uxthemes.com/
theme_path: /var/www6/p5802/monq.sk/web/wp-content/themes/flatsome
auto_update: Zakázané

### wp-plugins-active (28) ###

Add-on Contact Form 7 - Mailpoet 3: version: 1.3.19, author: Tikweb, Zakázané automatické aktualizácie
All-in-One WP Migration: version: 7.57, author: ServMask, Zakázané automatické aktualizácie
Classic Editor: version: 1.6.2, author: WordPress Contributors, Zakázané automatické aktualizácie
Contact Form 7: version: 5.5.6, author: Takayuki Miyoshi, Zakázané automatické aktualizácie
Contact Form CFDB7: version: 1.2.6.4, author: Arshid, Zakázané automatické aktualizácie
Email Verification for WooCommerce: version: 2.3.2, author: WPFactory, Zakázané automatické aktualizácie
Extendons Mix & Match Bundles: version: 2.0.3, author: Extendons, Zakázané automatické aktualizácie
Flamingo: version: 2.2.3, author: Takayuki Miyoshi, Zakázané automatické aktualizácie
Google Listings and Ads: version: 1.12.4, author: WooCommerce, Zakázané automatické aktualizácie
Invoices for WooCommerce: version: 3.1.9, author: Bas Elbers, Zakázané automatické aktualizácie
Loco Translate: version: 2.6.1, author: Tim Whitlock, Zakázané automatické aktualizácie
MailPoet 3 (New): version: 3.86.0, author: MailPoet, Zakázané automatické aktualizácie
MailPoet 3 Premium (New): version: 3.86.1, author: MailPoet, Zakázané automatické aktualizácie
Pay for Payment for WooCommerce: version: 2.1.5, author: Karolína Vyskočilová, Zakázané automatické aktualizácie
Pinterest for WooCommerce: version: 1.0.10, author: WooCommerce, Zakázané automatické aktualizácie
Really Simple SSL: version: 5.3.1, author: Really Simple Plugins, Zakázané automatické aktualizácie
Regenerate Thumbnails: version: 3.1.5, author: Alex Mills (Viper007Bond), Zakázané automatické aktualizácie
Slovenská pošta - ePodací hárok: version: 1.2, author: Matej Podstrelenec, Zakázané automatické aktualizácie
WooCommerce: version: 6.3.1, author: Automattic, Zakázané automatické aktualizácie
WooCommerce 123kurier.sk: version: 1.0, author: 123kurier.sk, Zakázané automatické aktualizácie
WooCommerce Google Analytics Integration: version: 1.5.8, author: WooCommerce, Zakázané automatické aktualizácie
WooCommerce Stripe Gateway: version: 6.3.0, author: WooCommerce, Zakázané automatické aktualizácie
WordPress Importer: version: 0.7, author: wordpressdotorg, Zakázané automatické aktualizácie
WPify Woo: version: 3.5.4, author: WPify s.r.o., Zakázané automatické aktualizácie
WP Mail SMTP: version: 3.3.0, author: WPForms, Zakázané automatické aktualizácie
WP Rocket: version: 3.11.0.3, author: WP Media, Zakázané automatické aktualizácie
YITH WooCommerce Wishlist: version: 3.8.0, author: YITH, Zakázané automatické aktualizácie
Yoast SEO: version: 18.5.1, author: Team Yoast, Povolené automatické aktualizácie

### wp-plugins-inactive (8) ###

All In One WP Security: version: 4.4.11, author: Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy, Zakázané automatické aktualizácie
Facebook for WooCommerce: version: 2.6.12, author: Facebook, Zakázané automatické aktualizácie
GDPR Cookie Consent: version: 2.1.1, author: WebToffee, Zakázané automatické aktualizácie
Nextend Social Login: version: 3.1.4, author: Nextendweb, Zakázané automatické aktualizácie
Site Kit by Google: version: 1.71.0, author: Google, Zakázané automatické aktualizácie
WooCommerce PDF Invoices & Packing Slips: version: 2.14.4, author: WP Overnight, Zakázané automatické aktualizácie
WP Product Feed Manager: version: 1.39.0, author: Michel Jongbloed, Zakázané automatické aktualizácie
Zero Spam for WordPress: version: 5.3.2, author: Highfivery LLC, Povolené automatické aktualizácie

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1808
imagemagick_version: ImageMagick 7.1.0-20 Q16-HDRI x86_64 2022-01-22 https://imagemagick.org
imagick_version: 3.5.1
file_uploads: File uploads is turned off
post_max_size: 512M
upload_max_filesize: 512M
max_effective_size: 512 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 47 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 47 GB
	imagick::RESOURCETYPE_MEMORY: 23 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FARBFELD, FAX, FF, FILE, FITS, FL32, FLV, FRACTAL, FTP, FTS, FTXT, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, KERNEL, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, QOI, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RSVG, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YAML, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0-1160.15.2.el7.x86_64 x86_64
httpd_software: Apache
php_version: 8.0.15 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 360
memory_limit: 256M
max_input_time: 360
upload_max_filesize: 512M
php_post_max_size: 512M
curl_version: 7.29.0 NSS/3.53.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.34
client_version: mysqlnd 8.0.15
max_allowed_packet: 524288000
max_connections: 200

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www6/p5802/monq.sk/web/wp-content
WP_PLUGIN_DIR: /var/www6/p5802/monq.sk/web/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Nedefinovaný
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wp_mail_smtp ###

version: 3.3.0
license_key_type: lite
debug: No debug notices found.
lite_install_date: jan 12, 2022 @ 7:27pm

<details>
	
</details>

**Comment by jconroy** [comment]
Hi @Zemislav  really sorry to hear of your difficulties. The best place to get support is [via the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) which we monitor or on [WooCommerce.com > Dashboard > Support and create a ticket.](https://woocommerce.com/support/).
