### ISSUE TITLE
Product feed problem

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/facebook-for-woocommerce#2188]
When product category contains comma. It will be treated as a separate category.

For example one product have multiple category like:
Category 1: House, Garden & Kitchen
Category 2: Home Improvement

Then the product_path will be:
House, Garden & Kitchen, Home Improvement

It will be treated as 3 Categories. See: https://support.google.com/merchants/answer/6324406?hl=en

Problem:
https://github.com/woocommerce/facebook-for-woocommerce/blob/66f30d1e86025dd1b26cefa58f2b7d8bc4745d59/includes/fbutils.php#L122

**Comment by message-dimke** [comment]
Hey, @erikdemarco! Is the issue related to Google or Facebook?

**Comment by erikdemarco** [comment]
@message-dimke If you look at the source code I mentioned facebook also will handle this 2 categories as 3 categories

**Comment by message-dimke** [comment]
@erikdemarco, I do not see this issue related to Facebook in any way. Facebook requires Google Product Category (GPC) or Facebook Product Category (FPC) for categorising products effectively. If you do not provide any GPC nor FPC but your WooCommerce categories when syncing products to Facebook, commas in category names do not create multiple categories.

<img width="492" alt="Dima_commerce_account_name" src="https://user-images.githubusercontent.com/9010963/165368422-5afaec0a-c381-43ea-9892-86746443575e.png">

If you have any issues with Facebook-for-woocommerce, please, provide detailed step-by-step instructions on how to reproduce the issue with as much information as possible to provide, including screens and logs if applicable.

**Comment by jconroy** [comment]
Hi erikdemarco thanks for taking the time to message - based on @message-dimke 's message above I'll mark as closed. The best place to get support is [via the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) which we monitor or on [WooCommerce.com > Dashboard > Support and create a ticket.](https://woocommerce.com/support/) - please feel free to reach out to our team there.
