### ISSUE TITLE
Cannot finish Facebook for WooCommerce plugin integration

### ISSUE THREAD

**Issue by pedrojosehv** [woocommerce/facebook-for-woocommerce#2201]
I have installed and tried to instegrate Facebook for Woocommerce plugin on https://chicbeutik.store/ several times. 

Everytime I try I keep getting this message:

“Could not retrieve installation IDs”

I have started the installation from scratch many times after changing the wc_facebook_external_business_id field in /wp-admin/options.php and I keep getting the same error.

How else can I troubleshoot this?

**Comment by jconroy** [comment]
Hi @pedrojosehv really sorry to hear of your difficulties. The best place to get support is [via the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) which we monitor or on [WooCommerce.com > Dashboard > Support and create a ticket.](https://woocommerce.com/support/).

**Comment by valerirpetrov** [comment]
I have exactly the same problem. I was trying to reinstall the plugin.
I passed all the steps. There seemed to be no problem, and in the end, Voocommerts made that error.
