### ISSUE TITLE
FB Pixel doesn't track ajax Add to cart events (and solution)

### ISSUE THREAD

**Issue by hogash** [woocommerce/facebook-for-woocommerce#2219]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

FB Pixel doesn't track ajax Add to cart events. 

It seems to happen because this code here https://github.com/woocommerce/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L632 is checking only when the DB option of the Cart redirection has been saved, because by default it returns `false` .

So instead of the condition `'no' === get_option( 'woocommerce_cart_redirect_after_add' )` 

it should be either

`'no' === get_option( 'woocommerce_cart_redirect_after_add', 'no' )`  (has the default)

or

`'yes' !== get_option( 'woocommerce_cart_redirect_after_add' )` (compare against yes)

**Comment by rawdreeg** [comment]
Thanks for reporting this, @hogash. I was able to reproduce this. We should be able to address this in time for our next planned release.

**Comment by hogash** [comment]
@rawdreeg awesome, thanks!!

**Comment by omleto** [comment]
I think it still doesn't work. Echhhh
