### ISSUE TITLE
FB collections not appearing on Instagram shop

### ISSUE THREAD

**Issue by RelovedAgain** [woocommerce/facebook-for-woocommerce#2221]
Hello,

Can someone tell me why collections are not appearing on my instagram shop? Is this a bug caused by the Facebook for Woo-commerce plugin? 

I have:
WooCommerce version: 5.6.2
Latest version of Facebook for WooCommerce

I manually create collections on the Facebook Commerce Shop. Since the end of April, all the new collections created on Facebook Commerce would not appear on Instagram Shop. I contacted the FB Support and, firstly, they told me it was caused by products having broken links. I removed all the products with issues but I still have the same issue. FB is still investigating on this and they don't have a clue on what's going on.

**Comment by rawdreeg** [comment]
Hi @RelovedAgain,

It looks like the issue will need to resolve with FB. Unless you have issues with the plugin specifically, FB support is the best point of contact to get the problem resolved.
