### ISSUE TITLE
How to call facebook sync from another plugin

### ISSUE THREAD

**Issue by nikoboomer** [woocommerce/facebook-for-woocommerce#2229]
Hello first of all thank you for this beautiful plugin.
I have a plugin that updates the price via ajax.
From what I saw the facebook plugin only syncs if you hit the update button.
Therefore, when my other plugin updates the price by ajax, the changes are not reflected in the facebook synchronization.

My question is how to call the update manually through another plugin.
Is there a trigger to call the sync function?

I need to call sync when the ajax response ends in exactly this code.

```
                $.ajax({
                type : 'POST',
                url : ajaxurl,
                data : {
                action: 'updatenotasexterpronedu',
                notasadmin : notasadmin,
                product_id: <?php echo $post->ID; ?>,
                execute: "addnotes" //otroidenficiador
                },
                success: function(response) {

               **//// I need to call the product synchronization here ///**
               **//// I need to call the product synchronization here ///**
               **//// I need to call the product synchronization here ///**

                if (response == "Okeytodo") {
                alert ("Nota de Producto y precio Externo actualizada");
                }
                else {
                alert ("Error de respuestas, Nota y precio de Producto Externo no actualizada");
                }
                }
            }); 
```
Thanks

**Comment by rawdreeg** [comment]
Hi  Nico,

Changes to the product are automatically synced with the Product Sync job (every hour).

You can run the sync for a given product using the create_or_update_products method, yeah.

https://github.com/woocommerce/facebook-for-woocommerce/blob/6187cef5b7a819026925a3d2c21aacdb4e035fe6/includes/Products/Sync.php#L95-L100

eg:

facebook_for_woocommerce()->create_or_update_products( array ( $product->get_id() ) )
