### ISSUE TITLE
Facebook for WooCommerce error: (#100) Missing Permission

### ISSUE THREAD

**Issue by tanjid** [woocommerce/facebook-for-woocommerce#2233]
## 🔎 Isolate the bug

- [ ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

In product edit page it shows Facebook for WooCommerce error: (#100) Missing Permission after clicking on update. I tried

- Reinstalling the facebook-for-woocommerce plugin
- Reconnecting using the plugin page
- Deleting WooCommerce app  in business store

## 🗃 Logs

06-22-2022 @ 16:53:42 - Response
code: 400
message: Bad Request
body: {"error":{"message":"(#100) Missing Permission","type":"OAuthException","code":100,"fbtrace_id":"AaOIBVQAwcmqw-Qr8qT1LuW"}}

06-22-2022 @ 16:53:42 - (#100) Missing Permission
06-22-2022 @ 16:53:42 - {"headers":{},"body":"{\"error\":{\"message\":\"(#100) Missing Permission\",\"type\":\"OAuthException\",\"code\":100,\"fbtrace_id\":\"AaOIBVQAwcmqw-Qr8qT1LuW\"}}","response":{"code":400,"message":"Bad Request"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
06-22-2022 @ 16:53:43 - Request
method: POST
uri: https://graph.facebook.com/v12.0/1008963499224636/events
user-agent: Facebook-for-WooCommerce/2.6.16 (WooCommerce/6.6.1; WordPress/6.0)
body: {"data":[{"action_source":"website","event_time":1655895223,"event_id":"cd8cabb0-de11-440a-a791-fa03f686d225","event_source_url":"https:\/\/retailbd.com\/shop\/wr75-wwoor-8874-square-fashion-watch-for-men\/","custom_data":{"content_name":"WR75 WWOOR 8874 Square Fashion Watch for Men","content_ids":"[\"WR75_330340\"]","content_type":"product","contents":"[{\"id\":\"WR75_330340\",\"quantity\":1}]","content_category":"WWOOR","value":"2250","currency":"BDT"},"user_data":{"client_ip_address":"128.199.162.130","client_user_agent":"WP Rocket\/Preload","fbc":"","fbp":""},"event_name":"ViewContent"}],"partner_agent":"woocommerce-6.6.1-2.6.16"}
duration: 0.30055s

`
### WordPress Environment ###

WordPress address (URL): https://retailbd.com
Site address (URL): https://retailbd.com
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 8.0.20
PHP Post Max Size: 50 MB
PHP Time Limit: 400
PHP Max Input Vars: 3500
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.6.51-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wp_
Total Database Size: 902.26MB
Database Data Size: 546.52MB
Database Index Size: 355.74MB
wp_woocommerce_sessions: Data: 5.06MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 7.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 40.58MB + Index: 34.11MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.52MB + Index: 3.63MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 4.52MB + Index: 4.03MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ba_invoice_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ba_prestashop_invoice: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_categorymeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_comments: Data: 22.55MB + Index: 21.09MB + Engine InnoDB
wp_edd_customermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_edd_customers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_faq_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_member_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 8.52MB + Index: 0.50MB + Engine InnoDB
wp_portfolio_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 154.70MB + Index: 144.41MB + Engine InnoDB
wp_posts: Data: 22.55MB + Index: 11.06MB + Engine InnoDB
wp_product_catmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.47MB + Index: 0.48MB + Engine InnoDB
wp_term_taxonomy: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_toolset_post_guid_id: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 83.63MB + Index: 87.27MB + Engine InnoDB
wp_users: Data: 8.52MB + Index: 7.55MB + Engine InnoDB
wp_usquare: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usquare_thmb: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.22MB + Index: 0.48MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.44MB + Index: 0.14MB + Engine InnoDB
wp_wfblockediplog: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 34.58MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 25.55MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.47MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.22MB + Index: 0.30MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wmfo_fraud_attempts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wmfo_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 81.63MB + Index: 5.55MB + Engine InnoDB
wp_wpda_csv_uploads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_logging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_menus: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_project_page: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_project_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_publisher: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_table_design: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_table_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_indexable: Data: 34.58MB + Index: 29.13MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.45MB + Index: 0.66MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.38MB + Index: 0.25MB + Engine InnoDB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

accordions: 1
amn_exact-metrics: 1
attachment: 8697
block: 10
blocks: 13
contactform: 4
custom_css: 1
custom_order_status: 2
et_pb_layout: 34
faq: 3
featured_item: 8
featurestab: 1
member: 8
nav_menu_item: 360
oembed_cache: 4
page: 197
partner: 6
portfolio: 22
post: 16
product: 1779
product_variation: 87
revision: 3
shop_coupon: 1
shop_order: 41562
shop_order_refund: 8
team: 5
testimonial: 4
ux_template: 3
woovouchers: 5
wp_global_styles: 1
wp-types-group: 1
wysijap: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

SSLCommerz Woo Commerce Payment Gateway: by JM Redwan – 1.0.4
Akismet Anti-Spam: by Automattic – 4.2.4
Custom Order Status for WooCommerce: by Tyche Softwares – 2.1.1
Disable XML-RPC: by Philip Erb – 1.0.1
Facebook for WooCommerce: by Facebook – 2.6.16
GAinWP Google Analytics Integration for WordPress: by IntelligenceWP – 5.4.6
Really Simple SSL: by Really Simple Plugins – 5.3.2
Facebook for WooCommerce - settings tools: by SkyVerge – 1.0.0
WooCommerce Banglalink Bulksms: by Monir Hossain – 1.0
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.6.1
Woo Manage Fraud Orders: by Prasidhda Malla – 2.5.4
WooCommerce Order List: by Monir Hossain – 1.0
Direct Checkout for WooCommerce: by QuadLayers – 2.6.2
WooCommerce: by Automattic – 6.6.1
Yoast SEO: by Team Yoast – 19.1
WP Rocket: by WP Media – 3.10.5

### Inactive Plugins (3) ###

MalCare WordPress Security Plugin - Malware Scanner, Cleaner, Security Firewall: by MalCare Security – 4.78
Performance Improvements for WooCommerce: by Luke Cavanagh – 1.0.9
Wordfence Security: by Wordfence – 7.5.11

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: BDT (৳ )
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #388 - /shop/
Cart: #389 - /cart/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #392 - /my-account/
Terms and conditions: #4473 - /terms-and-conditions/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.15.6
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
flatsome/woocommerce/content-product_cat.php

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-06-23 06:54:46 +06:00
Options: ✔
Notes: 50
Onboarding: completed

### Action Scheduler ###

Complete: 5,028
Oldest: 2022-06-21 18:18:21 +0600
Newest: 2022-06-22 15:58:04 +0600

Failed: 3,072
Oldest: 2018-11-12 13:35:29 +0600
Newest: 2018-12-29 22:39:42 +0600

Pending: 2
Oldest: 2022-06-22 18:56:49 +0600
Newest: 2022-06-28 18:55:26 +0600

### Status report information ###

Generated at: 2022-06-22 17:50:20 +06:00
`

**Comment by gabrielbonifacio** [comment]
There's a surge in cases related to the error above:

https://wordpress.org/support/topic/facebook-for-woocommerce-error-100-missing-permission/
https://wordpress.org/support/topic/facebook-for-woocommerce-error-100-missing-permission-2/
https://wordpress.org/support/topic/facebook-for-woocommerce-error-100-missing-permission-3/
https://wordpress.org/support/topic/facebook-woo-commerce-error-100-permission-denied/

5323924-zen
5314939-zen
5310890-zen
5320063-zen
5315805-zen
5323009-zen

**Comment by jconroy** [comment]
Some notes from internal discussion

* Some of the permission issues appears to have started all of sudden, we haven't released any new code since https://github.com/woocommerce/facebook-for-woocommerce/releases/tag/2.6.16
* Some users have reported things starting to work again all of a sudden overnight https://wordpress.org/support/topic/facebook-for-woocommerce-error-100-missing-permission-3/#post-15771410
* We'll investigate but strongly suggest users/HE's should consider connecting/reconnecting and contacting Facebook direct

**Comment by rawdreeg** [comment]
@tanjid, @gabrielbonifacio 

As noted by @jconroy, we could not trace this back to a change in the extension itself. So, this is probably a bug in Meta's platform API. We've had a few more users reporting that the issue just fixed itself (https://wordpress.org/support/topic/facebook-for-woocommerce-error-100-missing-permission-2/#post-15776748). I could find reports of major disruptions in the Meta Business Suite (reported on June 23 ) that could be related to this. 

We will continue to monitor this issue. However, we recommend that users/HE consider connecting/reconnecting and contacting Facebook direct support.

**Comment by rawdreeg** [comment]
We haven't seen any more reports of this issue. So I am going to close this.

**Comment by strarsis** [comment]
Have encountered this issue today. Same error `[...] does not exist, cannot be loaded due to missing permissions, or does not support this operation [...]`, but no specific reason was given.
