### ISSUE TITLE
Facebook for woocommerce prevents store integration with Whatsapp Business

### ISSUE THREAD

**Issue by cbacigalupoAR** [woocommerce/facebook-for-woocommerce#2236]
Since the function of integrating the Facebook store with WhatsApp Bussines came out, I tried all the ways to integrate it, today chatting with Facebook support they told me that I should be able to manage it from the Facebook for Woocommerce plugin that is in charge of Generate catalogs.
Reviewing I do not see that the plugin generates it and not the catalog within facebook associated with the whatsapp phone number is not updated with the information of the site, someone saw some of these options

**Comment by jconroy** [comment]
Hi @cbacigalupoAR thanks for the message. 

> Facebook support they told me that I should be able to manage it from the Facebook for Woocommerce plugin that is in charge of Generate catalogs

I'm not aware of any specific WhatsApp integration within the extension. 

> Reviewing I do not see that the plugin generates it and not the catalog within facebook associated with the whatsapp phone number is not updated with the information of the site, someone saw some of these options

Would you be able to clarify what you mean here? I'd like to make sure I understand correctly.

---

Currently our [ideas board is being migrated](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=398356) - once that is done I think I would recommend creating a topic for us to track popularity of WhatsApp support/integration.

**Comment by rawdreeg** [comment]
Based on @jconroy 's comment, I think we can close this issue.
