### ISSUE TITLE
Tax/VAT sent to Facebook when Calculate tax based on Customer Address

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/facebook-for-woocommerce#2247]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When **Calculate tax based on** is set to _Customer Shipping Address_  or _Customer Billing Address_ and **Display prices in the shop** is _Including tax_, Facebook for WooCommerce will use the Shop base address when sending a product's `[price]` including tax to Facebook.

```
07-12-2022 @ 11:23:38 - Request
uri: https://graph.facebook.com/v12.0/5378239202223009
body: Array
(
    [name] => Square Product 1
    [description] => Square description
    [image_url] => https://coytesting.mystagingwebsite.com/wp-content/uploads/2022/05/original.png
    [additional_image_urls] => 
    [url] => https://coytesting.mystagingwebsite.com/product/square-product-1/
    [category] => Uncategorized
    [brand] => My WordPress Site
    [retailer_id] => sqr123_29
    [price] => 8167
    [currency] => USD
    [availability] => in stock
    [visibility] => published
)
timeout: 500
method: POST
```

## 🚶‍♀️ Steps to reproduce

1. Enable taxes
2. Configure a tax table to include the shop's address and other locations
3. Set the Calculate tax based option to Customer Shipping Address
4. Configure Display prices in the shop to Include tax
5. Assign a product to that tax table
6. Sync that product
7.  See price is inclusive of tax using shop base address

Tax options page ( https://d.pr/i/3wG2q4 )

## ✔️ Expected behavior

The expected behaviour is for the price to include taxes based on the customer's shipping address, not the base shop address. If this is a fallback when a customer shipping address is provided then the option should be made available for merchants to make, not the default behaviour. 

The price on Facebook will not be correct for everyone when the tax is set to the customer shipping address, so there's no need for it to use the shop address for stores that ship globally. When the merchant has chosen "Customer Shipping Address" or "Customer Billing Address" within the tax settings for **Calculate tax based on** and prices on the shop page inclusive of tax, show the option within Marketing > Facebook > Product Sync to use the shop base address as a fallback.  

##  Temporary solution

Set the Display prices in the shop option to "Excluding tax"
![Screenshot](https://d.pr/i/otv2pa+)
Screenshot link: https://d.pr/i/otv2pa

Although this will not send the tax to Facebook this will also force the products on the shop page to not show taxes even if the customer has provided a shipping address. It's not until that customer is on the cart/checkout page that the other option will show taxes inclusive of tax. 

5353866-zd

**Comment by johndcoy** [comment]
@rawdreeg If we're using the shop base address because that's what WooCommerce core is doing with `wc_get_price_to_display`, then I'm curious why core not use the same shop base to include taxes as a backup on it's shop page when customers haven't provided their details?

As much as I juggled if this issue was a bug or feature, the fact that prices show exclusive of tax when customer details haven't been provided when using core, made the different pricing in Facebook difficult to accept.

So this may be less of a bug and more of an enhancement. Maybe instead of `wc_get_price_to_display` WooCommerce core is using another hook for their shop page given the different functionality?

Thanks for thinking this through with me.

**Comment by rawdreeg** [comment]
@johndcoy,

> I'm curious why core not use the same shop base to include taxes as a backup on it's shop page when customers haven't provided their details?

I reckon it does. 

I set up my shop address to Belgium, then configured a simple tax table:

Tax options:

![Screenshot 2022-07-20 at 18 25 03](https://user-images.githubusercontent.com/4209011/180033976-a050bd81-95bf-44b1-adbb-cc8a00c6787a.jpg)

Rates tables:
![Screenshot 2022-07-20 at 18 25 46](https://user-images.githubusercontent.com/4209011/180034071-dc3c14c4-6d00-4727-ab68-6ee1e6051d4c.jpg)

For anonymous users, the tax is shown based on the store address (Price incl tax at 10%):

![Screenshot 2022-07-20 at 18 27 53](https://user-images.githubusercontent.com/4209011/180034879-f37e9e9b-a667-412a-8efd-54127bc5a5b4.jpg)


For another user, I set the shipping address to South Africa (Price incl tax at 20%):
![Screenshot 2022-07-20 at 18 29 05](https://user-images.githubusercontent.com/4209011/180034739-09b50164-957e-413d-8c19-24f2b8353ca7.jpg)

Price of the FB product (Synced based on the store address)

![Screenshot 2022-07-20 at 18 30 58](https://user-images.githubusercontent.com/4209011/180035105-30ec9f2c-dc8b-4e2b-bdc0-ec9443353696.jpg)

**Comment by johndcoy** [comment]
@rawdreeg Thanks for confirming. I must have gotten lost in my investigations and lost track of how core was handling the price. Let's leave the possibility for this feature request to the community to decide. Although currently pending review, I've created an idea titled "Product price exclusive of tax when sent to Facebook" that others who land here can search for on that page to see the status of an idea.
