### ISSUE TITLE
Wrong Product Description / Permalink URL Not Saving

### ISSUE THREAD

**Issue by mattermarketing** [woocommerce/facebook-for-woocommerce#2251]
## 🔎 Isolate the bug

- [x ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
[]

Walkthrough here: (https://www.loom.com/share/7085d5c07891474ab6895d97ca0ace70)

## 🚶‍♀️ Steps to reproduce

You edit a product - save/publish
You edit a url slug and save/publish

the changes made do not hold - this is not a caching issue.

## ✔️ Expected behavior
Product information/short description will not save
Different text from different products is in short description

## 🗃 Logs

<details>
`
### WordPress Environment ###

WordPress address (URL): https://oxfordshireanimalsanctuary.org.uk
Site address (URL): https://oxfordshireanimalsanctuary.org.uk
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.51 (Debian)
PHP Version: 7.4.30
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.20-MariaDB-1:10.4.20+maria~buster-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wp_
Total Database Size: 1537.50MB
Database Data Size: 1170.37MB
Database Index Size: 367.13MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 35.56MB + Index: 30.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 42.55MB + Index: 0.08MB + Engine InnoDB
wp_actionscheduler_actions: Data: 11.02MB + Index: 12.22MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 8.02MB + Index: 6.05MB + Engine InnoDB
wp_bookly_appointments: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_bookly_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_customers: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_bookly_customer_appointments: Data: 0.20MB + Index: 0.23MB + Engine InnoDB
wp_bookly_email_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_bookly_holidays: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_mailing_campaigns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_mailing_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_mailing_list_recipients: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_mailing_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_messages: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_bookly_news: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_bookly_notifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_bookly_orders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_bookly_payments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_schedule_item_breaks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_sent_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bookly_series: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_services: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_shop: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_bookly_staff: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_staff_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_staff_preference_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bookly_staff_schedule_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_staff_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bookly_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_sub_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 83.61MB + Index: 46.09MB + Engine InnoDB
wp_ct_ugdpr_consent_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_datalist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_frm_fields: Data: 3.52MB + Index: 0.13MB + Engine InnoDB
wp_frm_forms: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_frm_items: Data: 2.30MB + Index: 0.53MB + Engine InnoDB
wp_frm_item_metas: Data: 25.45MB + Index: 12.88MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mclean_refs: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nksubcounters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nksubsubscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 12.47MB + Index: 0.34MB + Engine InnoDB
wp_pmxe_exports: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 813.98MB + Index: 207.45MB + Engine InnoDB
wp_posts: Data: 45.53MB + Index: 13.86MB + Engine InnoDB
wp_rafflepro_tickets_customer_to_tickets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rafflepro_tickets_setting: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rafflepro_tickets_winners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 1.02MB + Index: 0.20MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_relevanssi: Data: 2.52MB + Index: 4.55MB + Engine InnoDB
wp_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_feed_caches: Data: 1.50MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 3.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 9.52MB + Index: 7.03MB + Engine InnoDB
wp_users: Data: 0.47MB + Index: 0.36MB + Engine InnoDB
wp_wcs_payment_retries: Data: 1.52MB + Index: 0.09MB + Engine InnoDB
wp_wc_activecampaign: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 8.52MB + Index: 6.06MB + Engine InnoDB
wp_wc_order_stats: Data: 7.52MB + Index: 5.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfBlockedIPLog: Data: 0.19MB + Index: 0.00MB + Engine InnoDB
wp_wfBlocks7: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wfConfig: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_wfHits: Data: 1.02MB + Index: 0.23MB + Engine InnoDB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfKnownFileList: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLogins: Data: 0.42MB + Index: 0.13MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfStatus: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woof_query_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 9.50MB + Index: 5.23MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.38MB + Index: 0.47MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 6.52MB + Index: 3.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 5.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
ajde_events: 105
attachment: 4979
custom_css: 1
easyimageslider: 2
epx_vcsb: 9
essential_grid: 22
frm_form_actions: 29
frm_styles: 1
give_forms: 2
give_payment: 82
give_pdf_template: 1
go_pricing_tables: 1
kscf_faq: 24
mc4wp-form: 1
nav_menu_item: 68
oembed_cache: 199
page: 78
phoe_badge: 3
portfolio: 4
post: 232
postman_sent_mail: 612
product: 250
product_variation: 60
revision: 57
seedprod: 1
shop_coupon: 1
shop_order: 62348
shop_order_refund: 45
shop_subscription: 3158
snp_popups: 1
templatera: 22
testimonial: 1
w4pl: 1
wplp-news-widget: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.19.11
ActiveCampaign for WooCommerce: by ActiveCampaign – 1.7.9
Advanced Custom Fields: by Delicious Brains – 5.12.3
Akismet Anti-Spam: by Automattic – 4.2.5
Bookly Group Booking (Add-on): by Bookly – 2.6
Bookly Pro (Add-on): by Bookly – 4.9
Bookly: by Bookly – 20.9
Breeze: by Cloudways – 2.0.7
Candy FAQ: by KonstruktStudio – 1.1.0
Classic Editor: by WordPress Contributors – 1.6.2
Classic Widgets: by WordPress Contributors – 0.3
Convert Plus: by Brainstorm Force – 3.5.24
Export Subscriptions to CSV: by Nenad Joldeski – 1.1.0
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
Envato Market: by Envato – 2.0.7
EventON: by AshanJay – 4.1.1
WP OPcache: by nierdz – 4.1.4
Formidable API: by Strategy11 – 1.11
Formidable Forms Pro: by Strategy11 – 5.4.1
Formidable Digital Signatures: by Strategy11 – 2.07
Formidable Views: by Strategy11 – 4.0.05
Formidable Zapier: by Strategy11 – 2.01
Formidable Forms: by Strategy11 – 5.4.1
Go Pricing - WordPress Responsive Pricing Tables: by Granth – 3.3.19
Smash Balloon Instagram Feed: by Smash Balloon – 6.0.6
WPBakery Page Builder: by Michael M - WPBakery.com – 6.9.0
Loco Translate: by Tim Whitlock – 2.6.2
Media Cleaner: by Jordy Meow – 6.4.0
Payment Gateways per Products for WooCommerce: by WPWhale – 1.7.1
PixelYourSite: by PixelYourSite – 9.1.1
Redirection: by John Godley – 5.2.3
Saragna : Visual Composer Addons: by Hitesh Khunt – 1.0
ShiftNav Pro - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.5

Shopkeeper Deprecated Features: by GetBowtied – 1.1.6
Shopkeeper Extender: by GetBowtied – 1.6.9
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.7.8

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.22.14

User Switching: by John Blackbourn & contributors – 1.6.0
Widget Logic: by WPChef – 5.10.4
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.6.1
Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.1
WooCommerce Email Test: by RaiserWeb – 1.2.2
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.19
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.6.5
WooCommerce Name Your Price: by Kathy Darling – 3.3.9
WOOF - WooCommerce Products Filter: by realmag777 – 2.1.5.1
WooCommerce Subscriptions: by WooCommerce – 4.4.0
WooCommerce: by Automattic – 6.7.0
Wordfence Security: by Wordfence – 7.5.11
Yoast SEO: by Team Yoast – 19.3
WP Crontrol: by John Blackbourn & contributors – 1.14.0
WP Latest Posts: by JoomUnited – 4.8.10
WP Mail SMTP: by WPForms – 3.5.1

### Inactive Plugins (13) ###

Facebook for WooCommerce: by Facebook – 2.6.18
Give - GoCardless Gateway: by GiveWP – 1.3.2
Maintenance: by WebFactory Ltd – 4.06
Post SMTP: by Post SMTP – 2.1.3
Query Monitor: by John Blackbourn – 3.9.0
Raffle Ticket Generator Gold - Woocommerce: by Web Services Ventures and wpraffle.com – 3.2.5.1
Really Simple SSL: by Really Simple Plugins – 5.3.2
Relevanssi: by Mikko Saari – 4.16.0
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.2.9
WP All Export - User Export Add-On Pro: by Soflyy – 1.0.7
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.5
WP All Export Pro: by Soflyy – 1.7.3
WP Debugging: by Andy Fragen – 2.11.14

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: donation (donation)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #9372 - /shop/
Basket: #9373 - /donation-totals/
Checkout: #9374 - /checkout/
My account: #9375 - /my-account/
Terms and conditions: #9860 - /terms-conditions/

### Theme ###

Name: Shopkeeper Child
Version: 1.4
Author URL: http:%20//www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: Shopkeeper
Parent Theme Version: 2.9.91
Parent Theme Author URL: https://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-single-product.php
shopkeeper-child/woocommerce/emails/customer-completed-order.php
shopkeeper-child/woocommerce/emails/customer-new-account.php
shopkeeper-child/woocommerce/emails/customer-note.php
shopkeeper-child/woocommerce/emails/customer-on-hold-order.php
shopkeeper-child/woocommerce/emails/customer-processing-order.php
shopkeeper-child/woocommerce/emails/customer-refunded-order.php
shopkeeper-child/woocommerce/emails/customer-reset-password.php
shopkeeper/woocommerce/global/quantity-input.php
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/myaccount/form-login.php
shopkeeper/woocommerce/single-product/add-to-cart/simple.php
shopkeeper/woocommerce/single-product/product-image.php
shopkeeper/woocommerce/single-product/product-thumbnails.php
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://oxfordshireanimalsanctuary.org.uk
Subscriptions Template Theme Overrides: shopkeeper-child/woocommerce/emails/cancelled-subscription.php
shopkeeper-child/woocommerce/emails/customer-completed-renewal-order.php
shopkeeper-child/woocommerce/emails/customer-on-hold-renewal-order.php
shopkeeper-child/woocommerce/emails/customer-payment-retry.php
shopkeeper-child/woocommerce/emails/customer-processing-renewal-order.php

Subscription Statuses: trash: 2
wc-active: 1554
wc-pending-cancel: 2
wc-pending: 269
wc-on-hold: 165
wc-cancelled: 1166

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ❌ No
Cache Update Failures: ❌ 3 failure

### Store Setup ###

Country / State: United Kingdom (UK)

### Subscriptions by Payment Gateway ###

Direct Debit (GoCardless): trash: 2
wc-active: 1553
wc-cancelled: 1159
wc-on-hold: 165
wc-pending: 269
wc-pending-cancel: 2

### Payment Gateway Support ###

Direct Debit (GoCardless): products
refunds
tokenization
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_date_changes
subscription_amount_changes
multiple_subscriptions
pre-orders

Braintree (Credit Card): products
card_types
payment_form
tokenization
charge
charge-virtual
authorization
capture_charge
customer_decline_messages
refunds
voids
customer_id
add_payment_method
token_editor
apple_pay
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin

Braintree (PayPal): products
card_types
payment_form
tokenization
charge
charge-virtual
authorization
capture_charge
customer_decline_messages
refunds
voids
customer_id
add_payment_method
token_editor
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-21 10:11:05 +01:00
Options: ✔
Notes: 90
Onboarding: completed

### Action Scheduler ###

Complete: 18,970
Oldest: 2022-07-12 17:35:06 +0100
Newest: 2022-07-20 14:10:02 +0100

Failed: 1,021
Oldest: 2022-02-24 15:07:08 +0000
Newest: 2022-07-19 19:15:24 +0100

Pending: 1,910
Oldest: 2022-07-20 14:20:18 +0100
Newest: 2022-08-20 14:07:51 +0100

### Name Your Price ###

Version: 
Template overrides: –

### Status report information ###

Generated at: 2022-07-20 14:14:30 +01:00
`
</details>

**Comment by rawdreeg** [comment]
It seems to be the same issue, or related to #2127 and #2145
