### ISSUE TITLE
Product Sync - Old price remains on the Facebook catalog/shop

### ISSUE THREAD

**Issue by rawdreeg** [woocommerce/facebook-for-woocommerce#2261]
## 🔎 Isolate the bug

- [ x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
If a user sets a sales price, the sale price is not cleared from FB when the sales price is removed  from the product on the Woo store
## 🚶‍♀️ Steps to reproduce

1. Create/edit a product and sets a sale price for the product. Observe that the product is synced to FB and the sale price is displayed correctly on the FB store.
2. Update the product, removing the sale price.
3. Go to FB, and the old sale price displays still.

## ✔️ Expected behavior

The price should be correctly synced.

**Comment by sukafia** [comment]
5433931-zen
