### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Klausdks** [woocommerce/facebook-for-woocommerce#2266]
Hi
I tried to update facebook for woocommerce plugin in my wordpress. Now my hole webshob and website is locked.

This is the message: Fatal error: Uncaught Error: Class 'SkyVerge\WooCommerce\Facebook\Products\Feed' not found in /var/www/freedivingdenmark.com/public_html/wp-content/plugins/facebook-for-woocommerce/class-wc-facebookcommerce.php:160 Stack trace: #0 /var/www/freedivingdenmark.com/public_html/wp-content/plugins/facebook-for-woocommerce/class-wc-facebookcommerce.php(119): WC_Facebookcommerce->init() #1 /var/www/freedivingdenmark.com/public_html/wp-content/plugins/facebook-for-woocommerce/class-wc-facebookcommerce.php(1141): WC_Facebookcommerce->__construct() #2 /var/www/freedivingdenmark.com/public_html/wp-content/plugins/facebook-for-woocommerce/class-wc-facebookcommerce.php(1207): WC_Facebookcommerce::instance() #3 /var/www/freedivingdenmark.com/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-for-woocommerce.php(129): facebook_for_woocommerce() #4 /var/www/freedivingdenmark.com/public_html/wp-includes/class-wp-hook.php(307): WC_Facebook_Loader->init_plugin('') #5 /var/www/freedivingdenmark.com/public_html/wp-includes/class- in /var/www/freedivingdenmark.com/public_html/wp-content/plugins/facebook-for-woocommerce/class-wc-facebookcommerce.php on line 160

Elementor and my host will not help they write that its a plugin issue.

Can you please help me ASAP?

Best from
Klaus

## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## 🚶‍♀️ Steps to reproduce

1. The first step
1. The next step… 

## 🗃 Logs

<details>
	
</details>

**Comment by Klausdks** [comment]
![Fatal_Error](https://user-images.githubusercontent.com/110555076/182659205-b0d8442f-542c-453a-bfdc-eaa36249351a.jpg)
![Fatal_Error_Dashboard](https://user-images.githubusercontent.com/110555076/182659229-d552da8b-1092-46b2-b9de-d9740cfd3e8e.jpg)

**Comment by jconroy** [comment]
Hi @Klausdks so sorry to hear of your difficulties - please contact [Woo support](https://woocommerce.com/my-account/create-a-ticket/) straight away to get access to our Happiness Team - they will be able to help you out.
