### ISSUE TITLE
Update WP compatibility version (6.0+)

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/facebook-for-woocommerce#2268]
## Isolate the bug
not really a bug, but this can prevent from plugin adoption for those running WP 6.0+

![image](https://user-images.githubusercontent.com/919332/183617539-df63d9ac-d199-45b4-88a6-4caa6daae11a.png)

## Describe the bug
just update the WordPress compat version, should be 6.0.1 at least

## Steps to reproduce
Search for the plugin in WP repository, check the version compatbility field / info

## Expected behavior
The plugin is compatible with WP 6.0+

**Comment by rawdreeg** [comment]
Thanks for raising this @Marc-pi. We fixed this in our latest release:
![Screenshot 2022-08-16 at 16 31 54](https://user-images.githubusercontent.com/4209011/184905984-69dd560c-1741-4699-953b-5e7f2613d44e.jpg)
