### ISSUE TITLE
Plugin is Auto Posting a Draft Post

### ISSUE THREAD

**Issue by robertgranlund** [woocommerce/facebook-for-woocommerce#2272]
Has anyone ever experienced the plugin making a draft post?  It seems as if a draft post was created a while back and now the post randomly shows up after it has been repeatedly deleted.  The only thing I can tell is that <html>
facebook_for_woocommerce_daily_heartbeat runs at about the same time the phantom post appears.

**Comment by rawdreeg** [comment]
Hi @robertgranlund,
We haven't seen reports of draft post resurfacing. As far as I know, we do not alter post status. `facebook_for_woocommerce_daily_heartbeat` is used primarily to [store Facebook feed config for tracking](https://github.com/woocommerce/facebook-for-woocommerce/blob/e33aa7b9e2403fd74eb5468d1661dedd24afd4bf/includes/Feed/FeedConfigurationDetection.php#L22), [refresh_installation_data](https://github.com/woocommerce/facebook-for-woocommerce/blob/e33aa7b9e2403fd74eb5468d1661dedd24afd4bf/includes/Handlers/Connection.php#L115), and clean up background sync jobs from the options table.

I suggest you contact our support [via the forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) which we monitor, or on [WooCommerce.com > Dashboard > Support and create a ticket.](https://woocommerce.com/support/).

I will close this issue, please feel free to reopen if you have steps to reproduce, and we'll investigate the bug.
