### ISSUE TITLE
Allow for a section of products to be chosen to not sync prior to syncing

### ISSUE THREAD

**Issue by nixiack** [woocommerce/facebook-for-woocommerce#2275]
## Feature requests

Currently you have to sync Facebook initially, and then remove products retroactively that you might not want to sync.  

It would be good to have an initial 'non-sync' option that does not involve the products being initially out of stock, virtual or variation dependent to not sync.  Perhaps have the area under **Marketing > Facebook > Sync** for excluded categories, etc. be available prior to the initial sync.

**Comment by jconroy** [comment]
Lets add to the ideas board / feature request system
