### ISSUE TITLE
Messenger error

### ISSUE THREAD

**Issue by qertis** [woocommerce/facebook-for-woocommerce#2286]
## 🔎 Isolate the bug
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/3893228/188269549-f5b755ad-8ae1-4148-8b8f-851426cc557d.png">

**Comment by rawdreeg** [comment]
Hi @qertis,

Could you provide more information on this issue?

Please go to the Facebook for WooCommerce settings page (Marketing > Facebook) and check the "Enable debug mode."

![Screenshot 2022-09-05 at 10 30 39](https://user-images.githubusercontent.com/4209011/188405020-b51a3764-72a4-4282-8e3f-a31230e9339d.jpg)

You should be able to find the API error in the WC logs: WooCommerce > Status > Logs.

Also, please include logs, details about your WordPress environment (from [**WooCommerce Status Report**](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/)), and any other relevant information about your site.
