### ISSUE TITLE
Reset catalog / metadata 

### ISSUE THREAD

**Issue by mitchellkrogza** [woocommerce/facebook-for-woocommerce#2309]
## Feature requests

Why not add these snippets as actual options in your plugin with a proper progress bar? https://woocommerce.com/document/facebook-for-woocommerce-delete-or-reset-all-facebook-products/ neither snippet even works.

**Comment by rawdreeg** [comment]
Thanks for the reports. We're currently investigating other approaches to this issue.

If you have a specific issue for which you require help, please follow the [recommended support channels listed here](https://github.com/woocommerce/woocommerce#support).

I'll close this issue.
