### ISSUE TITLE
price and/or sale price is 0 in Facebook Commerce after sync

### ISSUE THREAD

**Issue by davidhefti** [woocommerce/facebook-for-woocommerce#2313]
Every few days we do have some products and/or variations in Facebook Commerce with Price 0 and/or Sale price 0. But in the product settings and variation settings it is all good.

![762bc5fd-4d8e-4308-bdb0-15fa4d8d2760](https://user-images.githubusercontent.com/114758203/194144436-339d06a3-4f5b-480d-bf59-01ea54090ec7.jpg)

**Comment by rawdreeg** [comment]
Thank you for reporting this, @davidhefti . 

The issue that you've raised is not reproducible as is. It now requires isolation and further investigation. Unfortunately, the GitHub issue tracker is not suitable for support. We've appropriate channels for this. Please follow the [recommended support channels listed here](https://github.com/woocommerce/woocommerce#support).

I'll close this issue as a support request.
