### ISSUE TITLE
facebook-for-woocommerce

### ISSUE THREAD

**Issue by hmjubaer** [woocommerce/facebook-for-woocommerce#2319]
![image](https://user-images.githubusercontent.com/62762172/195347841-9efa5828-f667-4642-a4cf-48a7fdcb91c9.png)

**Comment by rawdreeg** [comment]
Thank you for reporting this, @hmjubaer  .

We're not able to help without more details about the issue. Unfortunately, the GitHub issue tracker is not suitable for support. We've appropriate channels for this. Please follow the [recommended support channels listed here](https://github.com/woocommerce/woocommerce#support).

I'll close this issue as a support request.
