### ISSUE TITLE
We're experiencing a Fatal error with the Facebook for Woocommerce plugin, PLEASE HELP

### ISSUE THREAD

**Issue by Fidget656** [woocommerce/facebook-for-woocommerce#2322]
Hello there,
We're experiencing a Fatal error with the Facebook for Woocommerce plugin.

Fatal error: Uncaught Error: Call to a member function get_facebook_id() on null in /home/customer/www/fidget.bg/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php:3575 Stack trace: #0 /home/customer/www/fidget.bg/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Admin/Product_Sync_Meta_Box.php(68): WC_Facebookcommerce_Integration->get_product_fbid('fb_product_grou...', 19845, Object(WC_Facebook_Product)) #1 /home/customer/www/fidget.bg/public_html/wp-admin/includes/template.php(1401): SkyVerge\WooCommerce\Facebook\Admin\Product_Sync_Meta_Box::output(Object(WP_Post), Array) #2 /home/customer/www/fidget.bg/public_html/wp-admin/edit-form-advanced.php(688): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post)) #3 /home/customer/www/fidget.bg/public_html/wp-admin/post.php(206): require('/home/customer/...') #4 {main} thrown in /home/customer/www/fidget.bg/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 3575

Can you please assist how to sort this issue out?

**Comment by arsh7023** [comment]
We are getting the same issue.
Fatal error: Uncaught Error: Call to a member function get_facebook_id() on null in /home/customer/www/solarlightingoutdoor.com.au/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php:3575 Stack trace: #0 /home/customer/www/solarlightingoutdoor.com.au/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Admin/Product_Sync_Meta_Box.php(68): WC_Facebookcommerce_Integration->get_product_fbid('fb_product_grou...', 2789, Object(WC_Facebook_Product)) #1 /home/customer/www/solarlightingoutdoor.com.au/public_html/wp-admin/includes/template.php(1401): SkyVerge\WooCommerce\Facebook\Admin\Product_Sync_Meta_Box::output(Object(WP_Post), Array) #2 /home/customer/www/solarlightingoutdoor.com.au/public_html/wp-admin/edit-form-advanced.php(681): do_meta_boxes(Object(WP_Screen), 'side', Object(WP_Post)) #3 /home/customer/www/solarlightingoutdoor.com.au/public_html/wp-admin/post.php(206): require('/home/customer/...') #4 {main} thrown in /home/customer/www/solarlightingoutdoor.com.au/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 3575

**Comment by rawdreeg** [comment]
Thanks for your report. Currently investigating

**Comment by rv8820** [comment]
I am getting the same error.

2022/10/14 08:44:44 [error] 38919#38919: *1103618 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to a member function get_facebook_id() on null in /www/huijisg_124/public/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php:3575
Stack trace:
#0 /www/huijisg_124/public/wp-content/plugins/facebook-for-woocommerce/includes/Admin/Product_Sync_Meta_Box.php(68): WC_Facebookcommerce_Integration->get_product_fbid('fb_product_grou...', 18802, Object(WC_Facebook_Product))
#1 /www/huijisg_124/public/wp-admin/includes/template.php(1401): SkyVerge\WooCommerce\Facebook\Admin\Product_Sync_Meta_Box::output(Object(WP_Post), Array)
#2 /www/huijisg_124/public/wp-admin/edit-form-advanced.php(681): do_meta_boxes(Object(WP_Screen), 'side', Object(WP_Post))
#3 /www/huijisg_124/public/wp-admin/post.php(206): require('/www/huijisg_12...')
#4 {main}
thrown in /www/huijisg_124/public/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 3575" while reading response header from upstream, client: 151.192.190.227, server: huiji.com.sg, request: "GET /wp-admin/post.php?post=18802&action=edit HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.4-fpm-huijisg.sock:", host: "huiji.com.sg:57949", referrer: "https://huiji.com.sg/wp-admin/edit.php?post_type=product"

**Comment by rawdreeg** [comment]
Thanks for reporting. We've made some changes to our class autoloader that seemed to result in the issue. We're preparing a release that will fix the issue. We will update you as soon as we have published the release

**Comment by Fidget656** [comment]
Hello Rodrigue,  
  Thank you for your email!  
  As we're experiencing a huge difficulties currently to work with our site due to this error, can you please let me know when can we expect the fix?  
  Regards,  
  Nikolay
 





 >-------- Оригинално писмо --------

 >От: Rodrigue ***@***.***

 >Относно: Re: [woocommerce/facebook-for-woocommerce] We're experiencing a Fatal
 error with the Facebook for Woocommerce plugin, PLEASE HELP (Issue #2322)

 >До: woocommerce/facebook-for-woocommerce  

 >Изпратено на: 14.10.2022 12:54



 
 
  
  
  
Thanks for reporting. We've made some changes to our class autoloader that seemed to result in the issue. We're preparing a release that will fix the issue. We will update you as soon as we have published the release

**Comment by rawdreeg** [comment]
A new update of the plugin has been released. Plugin update the Facebook for WooCommerce plugin version 2.6.27 to fix the issue

**Comment by Fidget656** [comment]
You're great, appreciated! All working smoothly as before.

**Comment by rawdreeg** [comment]
Thanks, @Fidget656.
