### ISSUE TITLE
Social auto poster : wordpress to facebook posts 

### ISSUE THREAD

**Issue by HashR28** [woocommerce/facebook-for-woocommerce#2332]
Hello guys, 

I have this error out of logs from the WordPress plugin  : Unsupported post request. Object with ID '1' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

I am not able to clear this out, I have everything in place regarding the configuration app idd, app secret, user access token and also the permissions . Where to go ?

**Comment by rawdreeg** [comment]
Hi @HashR28,
 Looking at your issue, I don't this is related to the [www.woocommerce.com/products/facebook](https://www.woocommerce.com/products/facebook). I would suggest you direct this question to the Social auto poster plugin support.
