### ISSUE TITLE
WooCommerce requests impact our servers, PLEASE HELP

### ISSUE THREAD

**Issue by Fidget656** [woocommerce/facebook-for-woocommerce#2333]
Hello team,
As our loading speed of our website fidget.bg is too slow recently I've contacted the Hosting provider - Siteground and they advised a lot of traffic is coming from the WooCommerce plugins after the last update of the plugin. Can you please review their report below and help me, please:

Hello,
I've reviewed the website and I can see the site is receiving a lot of traffic. Many of the requests towards the site appear to come from WooCommerce plugins:

Top 10 Visits, sorted by URL:

---------------------------------

   2252 fidget.bg /?wc-ajax=xoo_wsc_refresh_fragments

   1620 fidget.bg /?wc-ajax=get_refreshed_fragments

   1104 fidget.bg /wp-content/themes/Divi/js/scripts.min.js?ver=4.18.0

   1103 fidget.bg /wp-includes/js/jquery/jquery.min.js?ver=3.6.0

   1095 fidget.bg /wp-content/plugins/woocommerce-econt/inc/js/select2.min.js?ver=4.0.13

   1087 fidget.bg /wp-content/plugins/woocommerce-econt/inc/js/tooltipster.bundle.min.js?ver=1.6.1

   1086 fidget.bg /wp-content/plugins/woocommerce-econt/inc/js/colorbox/jquery.colorbox-min.js?ver=1.6.1

   1084 fidget.bg /wp-content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js?ver=2.7.0-wc.7.0.0

   1079 fidget.bg /wp-includes/js/jquery/ui/autocomplete.min.js?ver=1.13.1

   1077 fidget.bg /wp-includes/js/jquery/ui/core.min.js?ver=1.13.1

I would advise consulting with the plugin creators how to reduce the amount of requests generated by the plugins, as excessive requests impact your resource usage and the server load. For reducing ?wc-ajax=get_refreshed_fragments requests:

https://www.webnots.com/fix-slow-page-loading-with-woocommerce-wc-ajaxget_refreshed_fragments/ 

Thank you in advance,

Nikolay

**Comment by rawdreeg** [comment]
Hi @Fidget656,

Looking at the info provided, nothing seems to indicate that these issues are coming from the Facebook-for-WooCommerce plugin. For support queries, please contact the [WooCommerce support](https://github.com/woocommerce/woocommerce#support).
