### ISSUE TITLE
Products in excluded categories remain at do not sync status after being removed from excluded categories

### ISSUE THREAD

**Issue by sukafia** [woocommerce/facebook-for-woocommerce#2343]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Generally, products default to sync and show. Excluding a category from sync in Marketing > Facebook > Product sync “Exclude categories from sync” sets products in that category to “Do not sync”, preventing the products in specified categories from syncing as expected. 

However, if the category is later removed from excluded categories, products in that category remain at the “Do not sync” sync status. Instead of returning to the default status of "Sync and show"

This means merchants have to edit individual products in the category and set their Facebook status to "sync and show" before they'll be synced to Facebook. Since several products are usually in a category, this can be a pain for merchants. (Updating the products via CSV can help but most merchants aren't familiar with this process)

## 🚶‍♀️ Steps to reproduce

1. Exclude a product category from syncing
2. Check to confirm that products in that category are excluded on Facebook
3. Remove the category from the excluded categories
4. Notice that products in that category still have the "Do not sync" status

**Comment by rawdreeg** [comment]
Thanks, @sukafia, for raising this. This has been previously reported in #2317. I will close this.
