### ISSUE TITLE
Deprecated notice in PHP 8.1

### ISSUE THREAD

**Issue by cena** [woocommerce/facebook-for-woocommerce#2346]
## 🔎 Isolate the bug

- [ X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme. (+ Query Monitor)

## ✍️ Describe the bug

With PHP 8.1 enabled, Query Monitor shows a deprecated notice:

```
Return type of SkyVerge\WooCommerce\PluginFramework\v5_10_0\SV_WC_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

In wp-content/plugins/facebook-for-woocommerce/vendor/skyverge/wc-plugin-framework/woocommerce/compatibility/class-sv-wc-datetime.php:85

## 🚶‍♀️ Steps to reproduce
- Set server PHP version to 8.1.
- Enable latest versions of WordPress, WooCommerce and Facebook for WooCommerce.
- Turn on Query Monitor.
- Note deprecated notices in QM.

## ✔️ Expected behavior

In PHP 8.0 and 7.4, the above notice does not appear.

## Possibly related:

https://github.com/woocommerce/facebook-for-woocommerce/pull/2315

Reported in https://wordpress.org/support/topic/deprecated-code-for-php-8-1/

**Comment by Camilo517** [comment]
The plugin has code marked as deprecated in php 8.1 and 8.2
