### ISSUE TITLE
Extra backlashes (\) are added to the Facebook Category Specific attributes value

### ISSUE THREAD

**Issue by rawdreeg** [woocommerce/facebook-for-woocommerce#2353]
## 🔎 Isolate the bug

- [ x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
A user reported post_meta row filled with backslashes (\\). Upon investigation, we notice that if the category attribute value contains a special char (",\) such as quotes or backslashes, the value is escaped causing the backslashes to duplicate indefinitely.

## 🚶‍♀️ Steps to reproduce

1. Edit a variable product
2. Open the Facebook tab
3. Select Google product categories. Eg.: Apparel & Accessories -> Clothing -> Shirts & Tops
4. Set one of the Category Specific Attributes attributes. Eg. Size -> Large (40\41)
5. Save and notice a backslash has been added to the attribute value. Eg. Large (40\\41)

![Screenshot 2022-11-04 at 07 39 10](https://user-images.githubusercontent.com/4209011/199899873-abd33804-e278-422e-aedb-fa2d3d20ba53.jpg)

## ✔️ Expected behavior
The value should remain exactly as the user saved.

**Comment by rawdreeg** [comment]
True @ibndawood. Initially, the quotes are escapes then the backslashes are subsequently escaped with every save.  Thanks, I have updated the issue description

**Comment by sukafia** [comment]
Hi @rawdreeg could you help check that [this thread](https://wordpress.org/support/topic/_wc_facebook_enhanced_catalog_attributes_size-over-50mb) isn't a reoccurrence of this issue? Thanks

**Comment by rawdreeg** [comment]
It seems the user was experiencing a remnant of this bug (before the [v2.6.29](https://github.com/woocommerce/facebook-for-woocommerce/releases/tag/2.6.29) release).

I will keep this close.
