### ISSUE TITLE
Taxonomy assignment to Facebook ones

### ISSUE THREAD

**Issue by Secy23** [woocommerce/facebook-for-woocommerce#2360]
Hi,
ive read something about the "Brands" assignement on the plugin but it was maybe discontinued or whatever ?
For the Plugin i would wish u can select in the plugin Page, which taxonomy is assigned to a facebook category:
like:
"Producer" -> "brand" on facebook
"colour" -> "color" on facebook

and so on, so you can have your cataloge so individual as possible
and tbh, i thought this would be as a Facebook Product.

or is there any workaround ?
also ive read in another Issue about it with Affiliate / external product .
cant u implement any "bulk" actions for that ? cause, i dont get it, is that plug in only for shops with 20 items ? how is it when u have 100K articles ? add all the stuff manually for each item ?

thanks in advance :)
![2022-11-07 19_22_37-Facebook for WooCommerce ‹ WildStyle — WordPress – Mozilla Firefox](https://user-images.githubusercontent.com/117676761/200386759-4d2bda47-07d5-4b4e-8582-64c12e5c4bf5.png)

**Comment by Secy23** [comment]
"For the Plugin i would wish u can select in the plugin Page, which taxonomy is assigned to a facebook **category**:"

sorry, i mean "product"

**Comment by rawdreeg** [comment]
Hi @Secy23,

Thanks for reaching out with your questions.

Normally, this repository is not suitable for support. Please don't use our issue tracker for support requests, but for issues related to the plugins only. Support can take place through the appropriate channels:

The [WooCommerce.com premium support portal](https://woocommerce.com/contact-us/) for customers who have purchased themes or extensions.
[Our community forum on wp.org](https://wordpress.org/support/plugin/facebook-for-woocommerce) which is available for all WooCommerce users.
For customizations, you may want to check our list of [WooExperts](https://woocommerce.com/experts/) or [Codeable](https://codeable.io/).

But I'll see if I can provide some answers here:

> ive read something about the "Brands" assignement on the plugin but it was maybe discontinued or whatever ?


The brand feature works with the [WooCommerce Brands](https://woocommerce.com/products/brands/) extension. This should provide a brand taxonomy that you assign to multiple products or categories. 

> For the Plugin i would wish u can select in the plugin Page, which taxonomy is assigned to a facebook category

Currently, we don't have an attribute mapping but this is a planned enhancement. Unfortunately, I can't tell you when this will be available.

Thanks
