### ISSUE TITLE
Products in excluded categories aren't automatically synced when the category is no longer excluded

### ISSUE THREAD

**Issue by message-dimke** [woocommerce/facebook-for-woocommerce#2366]
### Products in excluded categories aren't automatically synced when the category is no longer excluded

If a category (e.g Shirts) is excluded from product sync and later removed from excluded categories, the products in the category are not automatically synced to Facebook even when products are edited and the Facebook sync status is updated to "Sync and show in catalog"

**Steps to replicate**

1. Go Marketing > Facebook > Product sync and exclude a category from sync (e.g Shirts)
2. Products in that category are removed from Facebook if already synced or aren't sycned if they're newly added
3. Go back to the "Exclude categories from sync" setting and remove the category so its products can be synced to Facebook
4. Notice the Facebook status remains at "Do not sync" - This is same on SV framework version so I'll be creating an enhancement request for this as manually editing product sync status can be a pain if several products are in the category. (Updating via CSV can be a pain for some users) 
5. Edit the product, update the Facebook sync status to "Sync and show in catalog" and then update the product
![vAjZMI.png](https://user-images.githubusercontent.com/60121732/197328577-221feb8a-2f4b-41d5-80b0-bf77f558dc3b.png)
6. Updating the product is supposed to automatically sync it but it doesn't get synced (This issue only exists on this version, updating Facebook sync status in SV version automatically syncs the product)
7. You have to use the product sync button in Marketing > Facebook > Product Sync > Sync products to force a manual sync before products in the category are synced (Updating the product on the editing page should push a sync)

_Originally posted by @sukafia in https://github.com/woocommerce/facebook-for-woocommerce/issues/2329#issuecomment-1287674070_

**Comment by rawdreeg** [comment]
Thanks, @message-dimke. But this issue has been previously reported here: https://github.com/woocommerce/facebook-for-woocommerce/issues/2317.

Closing in favor of #2317
