### ISSUE TITLE
Add unit tests using WordPress core unit tests

### ISSUE THREAD

**Issue by ibndawood** [woocommerce/facebook-for-woocommerce#2380]
With the `v3.0.0` release, the plugin moved away from `Codeception` for unit tests. The code should now use WordPress core unit testing framework which uses `PHPUnit` for unit testing PHP.

References:
1. https://developer.woocommerce.com/testing-extensions-and-maintaining-quality-code/setting-up-a-local-environment-for-testing/
2. https://make.wordpress.org/cli/handbook/misc/plugin-unit-tests/

**Comment by rawdreeg** [comment]
Hi @ibndawood,

I believe we have WP Unit setup for this project. Are there any pending actions on this topic?

**Comment by ibndawood** [comment]
Hey @rawdreeg,

Yes, the WP unit test is set up. @message-dimke sneaked the unit tests into the codebase. This issue can be closed.
