### ISSUE TITLE
feedURL CSV data does not reflect new products

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/facebook-for-woocommerce#2392]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When viewing the page source of the Facebook settings the **feedPrepared > feedURL** downloads a CSV of the product feed. The contents of this CSV do not change after adding products, even with those products showing on Facebook as expected. The samples: does reflect the most recent data ( products ) added. 

## 🚶‍♀️ Steps to reproduce

1. Navigate to the Facebook settings page under Marketing > Facebook `/wp-admin/admin.php?page=wc-facebook&tab=connection`
2. View the page source to see the feed script.
3. Copy the URL from the `feedUrl:` object.
4. Paste that URL into a new browser window to download the feed CSV
5. Add a new product(s)
6. Repeat steps 1-4
7. See the newly download CSV does not reflect new data.
8. View the Catalog > Items for this Facebook connection to see the newly created product showing as expected.

![Screenshot](https://d.pr/i/sCBCst+)
Screenshot link: https://d.pr/i/sCBCst

## ✔️ Expected behavior

The expected behavior is for the CSV to reflect the most recent data sent to Facebook.

**Comment by rawdreeg** [comment]
The feed file is regenerated daily. The newly created product would only appear after the feed can be regenerated. I would advise against triggering a feed regeneration every time a product is created or updated as this is resource intensive operation

However, the feed regeneration process can be manually triggered by running the wc_facebook_regenerate_feed job. For that, you go to WooCommerce -> Status -> Scheduled Actions, then click on the "pending" tab and run the wc_facebook_regenerate_feed hook:
![Screenshot 2022-11-28 at 15 07 55](https://user-images.githubusercontent.com/4209011/204285491-ead01694-3d4d-4d76-bf35-3fd871a61f55.jpg)

**Comment by rawdreeg** [comment]
Based on my previous reply. I will close this thread
