### ISSUE TITLE
Facebook synced Simple product can not be set to 'Do not sync' and deleted from Facebook.

### ISSUE THREAD

**Issue by message-dimke** [woocommerce/facebook-for-woocommerce#2441]
## Description

Simple product can not be removed and set not to sync to Facebook once it was synced. There are no error log messages.

## 🚶‍♀️ Steps to reproduce

1. Edit a synced Simple product and set 'Do not sync'.

<img width="1248" alt="Edit_product_“New_Accessory__edited_”_‹_WordPress_Facebook_—_WordPress" src="https://user-images.githubusercontent.com/9010963/211322066-cf5a8dba-b9c0-4647-bb14-a987811d2f17.png">

2. Observe the popup appear. Press 'Remove from sync and delete' button.

<img width="1247" alt="Edit_product_“New_Accessory__edited_”_‹_WordPress_Facebook_—_WordPress" src="https://user-images.githubusercontent.com/9010963/211322326-6913df0d-0ee2-48e2-8a64-d14ad9762eec.png">

3. Update the product and observe the Facebook tab. It stayed like nothing happened and the product is still synced to Facebook.

<img width="1247" alt="Edit_product_“New_Accessory__edited_”_‹_WordPress_Facebook_—_WordPress" src="https://user-images.githubusercontent.com/9010963/211322667-3043ddef-9470-420f-aac3-b13d4ac7a18c.png">

## ✔️ Expected behavior

Product Facebook sync status set to 'Do not sync'. Product removed from Facebook.

**Comment by sukafia** [comment]
5866192-zen
