### ISSUE TITLE
There seems to be some error in the documentation pages. 

### ISSUE THREAD

**Issue by kosakk** [woocommerce/facebook-for-woocommerce#2450]
Towards the end of the [sync products to facebook](https://woocommerce.com/document/facebook-for-woocommerce/#sync-products-to-facebook) section, in the plugin documentation page, at the first list item of the instructions ordered list, where it reads: "_Enable product sync – Use this to disable product syncing entirely. If this option is selected, an alternate data source must be provided to ensure your catalog has all of the fields required for Checkout, e.g. GPC, inventory, and variant attributes._" the content is confusing. 

Perhaps the part that reads "[...] _Use this to disable product syncing entirely. If this option is selected,_ [...]" at the beginning of the block would be more accurate if it was phrased as "[...] **Unselect** this to disable product syncing entirely. If this option is **unselected** [...]" or something along these lines. After all the checkbox label reads "Enable product sync".

**Comment by rawdreeg** [comment]
Thanks for reporting this. I have submitted the edit. This will be live soon. 

![Screenshot 2023-01-18 at 12 16 39](https://user-images.githubusercontent.com/4209011/213145517-1caa6513-e69e-4325-9478-eb1c968d89c8.jpg)
