### ISSUE TITLE
Web Loading Issue - Javascript event failure

### ISSUE THREAD

**Issue by Mohamed-Zumry** [woocommerce/facebook-for-woocommerce#2451]
My website keeps loading even after the website is loaded. When I inspected the network tab I saw a facebook javascript event request is failing, So it keeps loading. When I deactivated the plugin, my issue was solved. So temporarily I have deactivated the plugin. Hope for a update or a solution asap.

I think this is a issue from a recent update, because earlier I did not face such a situation

**Comment by rawdreeg** [comment]
Thanks, @Mohamed-Zumry. Could you share more details with us? Would you happen to have a screenshot of the error message?

Please also include logs, details about your WordPress environment (from [**WooCommerce Status Report**](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/)), and any other relevant information about your site.

**Comment by Mohamed-Zumry** [comment]
I think now its ok, as per the issue analysed by me, it was because of I had another wordpress installation in a folder in my domain

**Comment by rawdreeg** [comment]
Thanks for looking into this. We're glad the issue is solved.
