### ISSUE TITLE
Problem while using SiteGround Optimizer plugin

### ISSUE THREAD

**Issue by micolf** [woocommerce/facebook-for-woocommerce#2456]
When i click su frontend .... in Optimizer Siteground Plugin

20-Jan-2023 12:31:58 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/customer/www/rosannacattolico.it/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php:748
Stack trace:
#0 /home/customer/www/rosannacattolico.it/public_html/wp-includes/class-wp-hook.php(308): WC_Facebookcommerce_EventsTracker->set_last_product_added_to_cart_upon_redirect('https://rosanna...', NULL)
#1 /home/customer/www/rosannacattolico.it/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('https://rosanna...', Array)
#2 /home/customer/www/rosannacattolico.it/public_html/wp-content/plugins/woo-variation-swatches/includes/class-woo-variation-swatches-product-page.php(310): apply_filters('woocommerce_add...', 'https://rosanna...', NULL)
#3 /home/customer/www/rosannacattolico.it/public_html/wp-content/plugins/woo-variation-swatches/includes/class-woo-variation-swatches-product-page.php(224): Woo_Variation_Swatches_Product_Page->js_options()
#4 /home/customer/www/rosannacattolico.it/public_html/w in /home/customer/www/rosannacattolico.it/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php on line 748

**Comment by ecgan** [comment]
The fix for this issue has been released in https://github.com/woocommerce/facebook-for-woocommerce/releases/tag/3.0.13 and in https://wordpress.org/plugins/facebook-for-woocommerce/.
