### ISSUE TITLE
New product gets "Do not sync" by default

### ISSUE THREAD

**Issue by rashedripon** [woocommerce/facebook-for-woocommerce#2470]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

[According to our doc](https://woocommerce.com/document/facebook-for-woocommerce/#facebook-product-data):

> By default, when you’re creating a new product, “Sync and show in catalog” will be selected.

However, in the new 3.0.9 version, it stays "Do not sync" when you create and publish the product. It creates an additional step for the admin to change sync settings for each product.

## 🚶‍♀️ Steps to reproduce

1. Update Facebook for WooCommerce to 3.0.9 version
2. Create a new product
3. Publish the product
4. Check the Facebook sync settings in the "Facebook" tab

## ✔️ Expected behavior

By default, when you’re creating a new product, “Sync and show in catalog” should be selected.

## Possible reason

Check the fix from the last version: https://github.com/woocommerce/facebook-for-woocommerce/pull/2455

**Comment by rashedripon** [comment]
Reported: https://wordpress.org/support/topic/setting-up-sync-and-show-in-catalog-by-default/
https://wordpress.org/support/topic/change-default-back-to-sync-and-show-in-catalog/

**Comment by xue28** [comment]
https://wordpress.org/support/topic/setting-up-sync-and-show-in-catalog-by-default-2/
