### ISSUE TITLE
Product status change issue

### ISSUE THREAD

**Issue by jezzvaliyatt** [woocommerce/facebook-for-woocommerce#2477]
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When a product's status is changed to a different status or a custom status, Facebook's product catalogue does not hide or remove the product.

### What I found: 
facebook-for-woocommerce/facebook-commerce.php  `fb_change_product_published_status ` line:966
It is currently checking the visibility. But in this instance, it ought to be verifying the product status, and it's especially important if your product statuses are custom.

### Suggestion:
CURRENT CODE: 
`$visibility = $product->is_visible() ? self::FB_SHOP_PRODUCT_VISIBLE : self::FB_SHOP_PRODUCT_HIDDEN;`
SUGGESTED CODE: 
`$visibility = ($product->get_status() == 'publish')?self::FB_SHOP_PRODUCT_VISIBLE : self::FB_SHOP_PRODUCT_HIDDEN;`
## 🚶‍♀️ Steps to reproduce

1. Change product status to a custom status and save the product. 

## ✔️ Expected behavior

It should hide the product on fb meta. But it is staying as published

## 🗃 Logs

<details>
	
sdsd
</details>

**Comment by rawdreeg** [comment]
Thanks for taking the time to raise this issue, @jezzvaliyatt.

In this case, I do not agree with the conclusion taken here. Is $product->is_visible() tells us whether a product is visible in the catalog regardless of the status value. This is to handle different visibility rules, for instance. A product can be "published" but hidden from their catalog by the user, in which case, the user wouldn't want the product synced to their Facebook shop.

WooCommerce core provides the `woocommerce_product_is_visible` filter. I suggest using it if you want to change the behavior of $product->is_visible() based on the status value. See https://woocommerce.github.io/code-reference/files/woocommerce-includes-abstracts-abstract-wc-product.html#source-view.1537

**Comment by jezzvaliyatt** [comment]
I agree with your answer. Nevertheless, I was confused by the fact that the function was connected to the action `transition_post_status ` and just checked the product's visibility when it should have checked the product status. Since I'm using a custom status and it was returning true when I checked its visibility, so the plugin was not actually altering the listing's visibility on Facebook  in that case.

I appreciate your suggestion and thank you for it.

**Comment by rawdreeg** [comment]
Thanks, @jezzvaliyatt. Feel free to reopen if you still need help on this. I will close.
