### ISSUE TITLE
Out of stock products not syncing to Facebook when "Hide out of stock items from the catalog" is enabled

### ISSUE THREAD

**Issue by sukafia** [woocommerce/facebook-for-woocommerce#2478]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When "Hide out of stock items from the catalog" is enabled in WooCommerce > Settings > Products > Inventory (tab), it prevents "out of stock" products in WooCommerce from being synced to the Facebook catalog to update the Facebook Shop inventory. This means out of stock products are promoted in Facebook ads but when potential shoppers click on them, they are out of stock when redirected to the WooCommerce site.

## 🚶‍♀️ Steps to reproduce

1. Navigate to WooCommerce > Settings > Products > Inventory (tab) and enable "Hide out of stock items from the catalog":
![UHanTn.png](https://user-images.githubusercontent.com/60121732/218873338-126b5557-ab05-4c55-afbe-29489beed1b2.png)
2. Create a product with a stock quantity (e.g 5)
3. Purchase the available product quantity 
4. Edit the product and check the Facebook Product Sync widget, notice it says "Product must be in stock". 
![7DcYeM.png](https://user-images.githubusercontent.com/60121732/218871958-df92f4fd-2781-4a41-ae5b-62103f0b0d4a.png)
5. Check the product on your Facebook Catalog/Shop and you'll find it's still in stock. 

## ✔️ Expected behavior

While it's expected that enabling "Hide out of stock items from the catalog" would prevent sync, out of stock products should be hidden from the Facebook catalog/shop just like on WooCommerce. 

**Related interactions:**

5935573-zen
https://wordpress.org/support/topic/out-of-stock-not-always-syncing/
[Feature request](https://woocommerce.com/feature-request/products-that-go-out-of-stock-will-continue-to-be-shown-in-the-facebook-feed/)

**Comment by sukafia** [comment]
After further investigations, I found the behaviour also prevents deleted products from being removed from Facebook.

**STEPS TO REPLICATE**

1. Navigate to WooCommerce > Settings > Products > Inventory (tab) and enable "Hide out of stock items from the catalog".
2. Create a product with a stock quantity (e.g 5)
3. Purchase the available product quantity
4. Deleted the product from the store
5. Check the Facebook catalog/shop and notice the product is still available.

Since "out of stock "products aren't synced when "Hide out of stock items from the catalog" is enabled, they also don't get synced when deleted so the product isn't updated on Facebook. This means a deleted product in WooCommerce is still promoted in Facebook ads. 

✔️ Expected behavior

Despite "Hide out of stock items from the catalog" being enabled, the stock status should be synced to Facebook or the product hidden from the Facebook catalog. Additionally, the product should be removed from Facebook when deleted. 

**Related interactions:**

5953327-zd-woothemes
https://wordpress.org/support/topic/how-to-change-behavior-of-out-of-stock-is-set-automatically-to-not-sync/
https://wordpress.org/support/topic/old-items-deleted-from-woocommerce-still-appear-in-catalog-after-sync/

**Comment by sukafia** [comment]
5945780-zen

**Comment by rawdreeg** [comment]
@sukafia,

https://github.com/woocommerce/facebook-for-woocommerce/pull/2481 fixes the issue. We'll include this on next planned release. Thanks

**Comment by sukafia** [comment]
That was fast! Thank you @rawdreeg.
