### ISSUE TITLE
Bug/feature - Ability to change attachment image size

### ISSUE THREAD

**Issue by seldimi** [woocommerce/facebook-for-woocommerce#2503]
## Feature requests

It would be very handy if we could change the image size url on product feed:
https://github.com/woocommerce/facebook-for-woocommerce/blob/6dbe0634fb56f5bca09db2c312800d8aedabac32/includes/fbproduct.php#L171

Currently, we can only add custom image via meta values. But a filter would be handy if we could affect the printed product image (eg different dimensions) via **wp_get_attachment_image_url** and replace the current **wp_get_attachment_url**

**Comment by rawdreeg** [comment]
Thanks for reaching out, @seldimi.

wp_get_attachment_url() applies the filter [wp_get_attachment_url](https://developer.wordpress.org/reference/hooks/wp_get_attachment_url/) . You should be able to affect the printed output by using this filter. Example:

``` PHP
add_filter('wp_get_attachment_url', 'modify_attachment_url', 10, 2);

function modify_attachment_url($url, $attachment_id) {
   // Do what you want to $url
   return $url;
}
```

I will close this issue with this comment. Feel free to re-open if you have further questions.

**Comment by rawdreeg** [comment]
Thanks for clarifying. We'll investigate further and revert to you.

**Comment by rawdreeg** [comment]
Thanks, 

A possible solution would be to use `wp_get_attachment_image_url` and filter the dimension as suggested by @seldimi. Eg:

``` PHP
 $product_image_url        = wp_get_attachment_image_url( $this->woo_product->get_image_id(), apply_filters( 'facebook_for_woocommerce_fb_product_image_size', 'full' ) ); 
```
