### ISSUE TITLE
facebook shop catalog - duplicate items

### ISSUE THREAD

**Issue by shaydevel** [woocommerce/facebook-for-woocommerce#2510]
## 🔎 Isolate the bug
- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Hi,
I have a duplicated item on my Facebook catalog, and can't erase it because: "This item was added to your catalog using a data feed. To avoid your manually made edits being overwritten in the future, update it in your data feed. [Go to data feed]"

the first item with the right id
the second item is with this id: <wc_post_id_<product/variation_id>

I read that that the <wc_post_id_<product/variation_id> is given to a product without an id, I am guessing the item was without an id until I fixed it, and that it was uploaded to the catalog as another item.

How can I get rid of the duplicate item?
I tried resyncing
cleared cash and resynced again
nothing happens

Dont want to delete the catalog since it is all set on my facebook and IG shops

Thanks

**Comment by shaydevel** [comment]
one item

**Comment by rawdreeg** [comment]
The only way around this is to Edit the item from within Facebook, make a minor change to the product, then manually delete it from within Facebook:

![Screenshot](![8Nw-T9pg2f.gif](https://user-images.githubusercontent.com/4209011/228504687-69e75c76-0d04-45d7-ae31-7d3f5c1b4c0a.gif)+)
Screenshot link: ![8Nw-T9pg2f.gif](https://user-images.githubusercontent.com/4209011/228504687-69e75c76-0d04-45d7-ae31-7d3f5c1b4c0a.gif)

**Comment by shaydevel** [comment]
GENIUS
Thanks it worked!

**Comment by rawdreeg** [comment]
Thanks, @shaydevel. Glad we could help.
