### ISSUE TITLE
PHP 8.1 fatal error with Facebook Pixel Event

### ISSUE THREAD

**Issue by drwpcom** [woocommerce/facebook-for-woocommerce#2516]
In checking a website with query monitor, a merchant found sound issues after upgrading to PHP 8.1.17, reported in 6082196-zen. The exact text of the error is available in 2fb1b-pb/#php

They found the following:

- The code causing the exception is: `$fb_options[ self::PIXEL_ID_KEY ] = $pixel_id;`
- The data it is trying to access with the $fb_options offset is there but it's being returned serialized and isn't being unserialized

They applied the following fix on their site in file facebook-commerce-pixel-event.php

line 536, method set_pixel_id()

// Throws error
$fb_options = self::get_options();

// No error
$fb_options = unserialize(self::get_options());

The suggest that maybe the data needs unserializing somewhere else and hence this report.

**Comment by ecgan** [comment]
The fix for this issue (PR https://github.com/woocommerce/facebook-for-woocommerce/pull/2517) has been released in https://github.com/woocommerce/facebook-for-woocommerce/releases/tag/3.0.18.

**Comment by sukafia** [comment]
6558379-zen (Adding for reference)
