### ISSUE TITLE
wrong font color when editing products in Woo

### ISSUE THREAD

**Issue by Tastybbqde** [woocommerce/facebook-for-woocommerce#2518]
Facebook for WooCommerce Version 3.0.17
WooCommerce Version 7.5.1
Foodica Pro 4.0.0
ZOOM Framework 1.9.16
Wordpress 6.2

Problem:
With Facebook for WooCommerce enabled, when editing the products, the description text is in white color on white background and with HTML-Tags.

![Bug1](https://user-images.githubusercontent.com/130467689/231169097-00d676fa-3eab-42fd-82b6-0e971f1af65c.PNG)

If the plugin is deactivated, you can edit the products again

![Bug2](https://user-images.githubusercontent.com/130467689/231169094-e29dcd32-c0e4-4a0e-b406-fa839b91edcf.PNG)

**Comment by budzanowski** [comment]
Hi @Tastybbqde,
Is this problem reproducible with Facebook For WooCommerce 3.0.18 ( latest version ) and 3.0.16 ( one before )

**Comment by Tastybbqde** [comment]
Hi,
yes, the problem was already in the previous versions and can also be reproduced in 3.0.18

**Comment by Tastybbqde** [comment]
Actually, the Facebook chat plugin was disabled, but still it was displayed and then also brought an error when using it. I have now activated it - but the display when editing the products has not changed. The chat mudul works now fine.
