### ISSUE TITLE
Forms Lead Event via Conversion API ?

### ISSUE THREAD

**Issue by torlior** [woocommerce/facebook-for-woocommerce#2540]
Hi, My issue is described in more detail here:

https://stackoverflow.com/questions/76194069/how-can-i-send-lead-event-to-both-pixel-and-conversion-api-via-an-elementor-form

I want to "hook in" to the plugin and send a lead event via a form, through conversion API. Is that possible at all? 
The reason is that the plugin can take care of deduplication (event id), string normalization, and hashing, and already has a good working connection to the conversion API. 

I used the: fbq ('track','Lead',{user data}) syntax upon successful form submission, but that worked only via the browser, I don't think it was handled by the plugin.

I noticed the plugin code has a contact form 7 integration, but that requires having specifically Contact Form 7 which is not the case, and I saw the code only collects email. 

Help! Thank you!

**Comment by Aminadav** [comment]
Why are you looking to do it from the server and not from the browser?

**Comment by torlior** [comment]
Lead conversion is very important for most of my clients, as this is the goal of their campaign, and we want to optimize the quality of the data we are getting from the website. CAPI is important for that.

**Comment by torlior** [comment]
Thank you so much for that response!
Would that send both CAPI and Pixel events with deduplication handling, or is that pixel event only?

**Comment by rawdreeg** [comment]
> Would that send both CAPI and Pixel events with deduplication handling, or is that pixel event only?

It should handle CAPI as well. The [event class constructor](https://github.com/woocommerce/facebook-for-woocommerce/blob/develop/includes/Events/Event.php#L70-L72) should prepare the data appropriately, which should allow FB to do deduplication.

**Comment by rawdreeg** [comment]
Based on the previous answer, I will close this issue.
