### ISSUE TITLE
Hello, I would like to ask a question about Facebook and WooCommerce product synchronization

### ISSUE THREAD

**Issue by suijishengcheng** [woocommerce/facebook-for-woocommerce#2559]
I have deleted the wrong product on WooCommerce and canceled the synchronization, but the Facebook store still cannot delete the product, and it shows that the product is uploaded through the repository and needs to be produced on WooCommerce.

So, what should I do with this product now?  Thank you so much for helping me out~

**Comment by rawdreeg** [comment]
Hi @suijishengcheng,

Archiving the product in your Facebook is one option. The only other way around this is to Edit the item from within Facebook, make a minor change to the product, then manually delete it from within Facebook:

Screenshot link: ![8Nw-T9pg2f.gif](https://user-images.githubusercontent.com/4209011/228504687-69e75c76-0d04-45d7-ae31-7d3f5c1b4c0a.gif)

**Comment by budzanowski** [comment]
Closing as suggestion from @rawdreeg solves the problem.
