### ISSUE TITLE
Because of UPPERCASE LETTER Topic, synchronization is not working

### ISSUE THREAD

**Issue by kuleramazan** [woocommerce/facebook-for-woocommerce#2562]
## 🔎 Isolate the bug

- [ x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

I have lots of product that has Uppercase Letter Topic. When all Letters are uppercase, synchronization is not working. I attached an image to this report.

<details>
	Product title is all capital letters. Please change the title to sentence case in order to allow synchronization of your product.
</details>

![1](https://github.com/woocommerce/facebook-for-woocommerce/assets/137447430/1a23a2bb-5ccc-499f-ac17-2b3c6b4198df)

**Comment by budzanowski** [comment]
The plugin behavior is correct given the FB guidelines. In case someone really wants to sync then there is a workaround posted by @rawdreeg. Closing as we don't consider this a bug. We will have more sophisticated checks in the future but this will be handled using a different Issue.
