### ISSUE TITLE
voocommerce facebook sorunu

### ISSUE THREAD

**Issue by uguryagiz51** [woocommerce/facebook-for-woocommerce#2572]
The problem is that our prices are constantly increasing and decreasing. I can handle this with a plugin in woocommerce. I can add or decrease the price of all products. but I can’t interfere with facebook price. The result remains the same price. In order to send the price to our catalog, we enter the Facebook price in the product separately. I can increase or decrease the woocommerce discounted price and sales price with one click. but facebook price remains the same. the result is the price in my facebook store catalog does not change.
product page with variation facebook price
[screenshot 1] (https://snipboard.io/oeELUv.jpg)

[screenshot 2] (https://snipboard.io/1EukDz.jpg)

I hope the screenshots help. The facebook catalog needs to get the prices from the voocommerce sales price and the discounted price. Entering a price in a different place is ridiculous and time consuming.

**Comment by ibndawood** [comment]
Hello there,

Thank you for reaching us. Please note that GitHub issues are not suitable for plugin support. I see that you've already created an issue in WordPress.org forums. Our support engineer shall assist you via forums soon.
