### ISSUE TITLE
WPML + Facebook for WooCommerce can trigger a fatal error on PHP 8+

### ISSUE THREAD

**Issue by JPry** [woocommerce/facebook-for-woocommerce#2584]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

As described in [this support request](https://wordpress.org/support/topic/backend-fatal-error-php-fatal-error-uncaught-typeerror-illegal-offset-type/), there are circumstances where the `WC_Facebook_WPML_Injector::should_hide()` method generates a fatal error.

Looking in the code for this method, we're relying on the results of calling:

```php
$product_lang = apply_filters( 'wpml_post_language_details', null, $wp_id );
```

In WPML, I found that the `wpml_get_language_information()` function is hooked to this filter, and it has two possible return values:

1. An instance of `WP_Error`. This happens when the post ID is not provided, or when the post object cannot be retrieved using `get_post()`. 
2. An array, like this:

```php
	return [
		'language_code'      => $language,
		'locale'             => $sitepress->get_locale( $language ),
		'text_direction'     => $sitepress->is_rtl( $language ),
		'display_name'       => $sitepress->get_display_language_name( $language, $current_language ),
		'native_name'        => isset( $language_information['display_name'] ) ? $language_information['display_name'] : '',
		'different_language' => $language !== $current_language,
	];
```

Considering that the default value of `null` is passed to the filter, it is also possible that the return value is `null`.

## Discussion needed

The main question is this: what should the `should_hid()` method return in each of the above scenarios?

## 🚶‍♀️ Steps to reproduce

Pending response to [this comment](https://wordpress.org/support/topic/backend-fatal-error-php-fatal-error-uncaught-typeerror-illegal-offset-type/#post-16901967)

## 🗃 Logs

The status report can be seen in the WordPress.org forum thread above.

**Comment by budzanowski** [comment]
FB with WPML shouldhide(). Assumes an array will be provided, but in some cases the $product_lang variable is WP_Error, null, etc. The logic can be fixed, but determining the ramifications of different return values given different circumstances is not easy.
No clear consensus reached on how we should work on it, but probably hide by default. 
@JPry  mentions that adding a filter would probably be a good approach so our chosen default can still be modified by 3pd.
