### ISSUE TITLE
Replace single requests with Batch requests

### ISSUE THREAD

**Issue by ibndawood** [woocommerce/facebook-for-woocommerce#2592]
The plugin uses a single request for publishing and updating simple products and uses batch requests for variable products. The parameters are different for single requests and batch requests appear different, causing a lot of redundant code. By replacing the single request with a batch request for simple products, we can get rid of redundant code.

**Comment by rawdreeg** [comment]
I belied this was resolved by https://github.com/woocommerce/facebook-for-woocommerce/pull/2672. I will close this.
