### ISSUE TITLE
Plugin Activation Error with PHP8.2: generated x characters of unexpected output

### ISSUE THREAD

**Issue by krutidugade** [woocommerce/facebook-for-woocommerce#2607]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

On activating Facebook for WooCommerce plugin, you see one error notice in the header. I noticed this error while doing PHP8.2 compatibility testing. This issue

`The plugin generated 31112 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.`

## 🚶‍♀️ Steps to reproduce

1. Change your site's PHP version to 8.2
2. Install and activate Facebook for WooCommerce plugin

## ✔️ Expected behavior
The plugin should be activated without any errors.

## Actual behavior
The plugin is activated with the following error.

<img width="2390" alt="Fb activate error" src="https://github.com/woocommerce/facebook-for-woocommerce/assets/33723519/2f6903b1-9743-4099-96d1-9ecd26ce3f6a">

## 🗃 Logs

<details>

### WordPress Environment ###

WordPress address (URL): https://ddev-sandbox.ddev.site
Site address (URL): https://ddev-sandbox.ddev.site
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.2.8
PHP Post Max Size: 100 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.30-MariaDB-1:10.4.30+maria~ubu2004-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: wp_
Total Database Size: 4.96MB
Database Data Size: 3.36MB
Database Index Size: 1.60MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
connect_woo_connections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
connect_woo_facebook_webhook_merchants: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
connect_woo_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
connect_woo_variables: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 11
customize_changeset: 1
page: 7
post: 4
product: 21
product_variation: 3
shop_order: 1
wcpf_item: 5
wcpf_project: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Facebook for WooCommerce: by Facebook – 3.0.30
WooCommerce: by Automattic – 7.9.0

### Inactive Plugins (2) ###

Product Filters for WooCommerce: by WooCommerce – 1.4.9
WooCommerce Coupon Campaigns & Tracking: by WooCommerce – 1.2.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.4.1 (update to version 4.5.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-08 17:26:58 +01:00
Options: ✔
Notes: 78
Onboarding: completed

### Action Scheduler ###

Complete: 299
Oldest: 2023-07-20 17:28:08 +0000
Newest: 2023-08-08 11:30:41 +0000

Failed: 18
Oldest: 2023-07-20 22:08:59 +0000
Newest: 2023-08-08 11:32:06 +0000

Pending: 2
Oldest: 2023-08-08 15:29:56 +0000
Newest: 2023-08-08 15:29:56 +0000

### Status report information ###

Generated at: 2023-08-08 12:48:28 +01:00

</details>

**Comment by ecgan** [comment]
Note that this issue only happens when we have debug mode enabled:

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', true );
```

Also, this issue happens in PHP 8.2 only. It does not happen when we test it with PHP 7.4, 8.0 and 8.1.

**Comment by ecgan** [comment]
I think this issue might be coming from WooCommerce core plugin, not specific to Facebook extension, because I'm seeing the same issue with WC Brands extension as well.

**Comment by krutidugade** [comment]
You're right Gan. I got the same error while testing Pinterest with PHP8.2. If debug mode is disabled, then I no longer see the error notice. Tested with latest WC8.0.1.

>I think this issue might be coming from WooCommerce core plugin, not specific to Facebook extension, because I'm seeing the same issue with WC Brands extension as well.

That makes sense. It is worth noting that we don't get this error on WooCommerce plugin activation.

**Comment by budzanowski** [comment]
We can actually see what the unexpected characters are: https://stackoverflow.com/a/57908083

**Comment by krutidugade** [comment]
Thank you @budzanowski  for sharing the post. I generated the unexpected characters output and they are a bunch of `Deprecated: Creation of dynamic property` warnings coming from WooCommerce. @ecgan was right that this is coming from WooCommerce so I'll go ahead and close this issue.

**Comment by ecgan** [comment]
> Would it be fine to report this bug in Woo repo? I'm checking as it is advised to file confirmed bugs only on Woo repo.

Yes, I actually have it in my own task list to report this in the WooCommerce repo. To me, it is a confirmed bugs that affects WooCommerce extensions, and it should be fixed in WooCommerce.

As per conversation in p1692007256645979-slack-CK365S85V, @mikkamp pointed out that there is already an open PR https://github.com/woocommerce/woocommerce/pull/38774 in the WooCommerce repo that seems to address this issue. I shall test with that PR and see if it works, and push to get that PR merged.

**Comment by ecgan** [comment]
> I shall test with that PR and see if it works, and push to get that PR merged.

Adding a note of my testing here.

When I use WooCommerce trunk branch (at https://github.com/woocommerce/woocommerce/commit/e8d0a081ad32d39b742bc470103c176cde7e1821), with debug enabled, and activate Facebook and WC Brands extension, I can see the error message at the top of the plugin page:

> The plugin generated 31760 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

When I use the https://github.com/woocommerce/woocommerce/tree/fix/wc-admin-php-dynamic-prop-warnings branch from PR https://github.com/woocommerce/woocommerce/pull/38774, I do not see the error message. 

I'll follow up in PR https://github.com/woocommerce/woocommerce/pull/38774.

**Comment by krutidugade** [comment]
Thank you for following up @ecgan. The PR is merged so we should no longer see the notice.
