### ISSUE TITLE
Dynamic property deprecation warnings with PHP8.2 under Facebook tab on Edit Products page

### ISSUE THREAD

**Issue by krutidugade** [woocommerce/facebook-for-woocommerce#2611]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Found as a result of PHP8.2 compatibility testing. I see following deprecation warnings on Edit Product page under Facebook tab. The warnings can be seen at the bottom.

## 🚶‍♀️ Steps to reproduce

1. Change your site's PHP version to 8.2
2. Install and activate Facebook for WooCommerce plugin
3. Go to Products > Add New
4. Scroll down to Facebook tab

## ✔️ Expected behavior
No warnings under the Facebook tab.

## Actual Behaviour
You see the following warnings under the Facebook tab on Edit or Add New Product page.
```
Deprecated: Creation of dynamic property WooCommerce\Facebook\Admin\Enhanced_Catalog_Attribute_Fields::$page_type is deprecated in /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/Admin/Enhanced_Catalog_Attribute_Fields.php on line 31

Deprecated: Creation of dynamic property WooCommerce\Facebook\Admin\Enhanced_Catalog_Attribute_Fields::$term is deprecated in /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/Admin/Enhanced_Catalog_Attribute_Fields.php on line 32

Deprecated: Creation of dynamic property WooCommerce\Facebook\Admin\Enhanced_Catalog_Attribute_Fields::$product is deprecated in /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/Admin/Enhanced_Catalog_Attribute_Fields.php on line 33

Deprecated: Creation of dynamic property WooCommerce\Facebook\Admin\Enhanced_Catalog_Attribute_Fields::$category_handler is deprecated in /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/Admin/Enhanced_Catalog_Attribute_Fields.php on line 34
```

## Screenshot

<img width="614" alt="Screenshot 2023-08-08 at 5 02 49 PM" src="https://github.com/woocommerce/facebook-for-woocommerce/assets/33723519/476509e1-fa0d-47ab-aa28-5e7053043085">

**Comment by ecgan** [comment]
Fixed in PR https://github.com/woocommerce/facebook-for-woocommerce/pull/2606, closing this issue.
