### ISSUE TITLE
Lost access to my business page while installing Facebook for WooCommerce plugin

### ISSUE THREAD

**Issue by SunnyDawn** [woocommerce/facebook-for-woocommerce#2615]
## 🔎 Isolate the bug

- [X ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

While installing the plugin Facebook for WooCommerce on my WordPress website I was asked to confirm settings. 

WooCommerce integration will be connected to: 
business manager: Sunny;Freeman
Facebook Page: Sunny Dawn - Fine Art
Instagram profile: @sunnydawnfineart
Catalog: Sunny Dawn Fine Art - Catalog
Commerce account: Sunny Dawn Fine Art
Meta pixel: Sunny Dawn Fine Art – meta pixel

I clicked “continue”

Next screen:

What is Woo commerce integration allowed to do?

Manage ads for add accounts that you have access to. 
Access your Facebook ads and related stats. 
Manage your product catalogs. 
Manage business extension. 
Read content posted on the page. Showing list of pages you manage.

I selected yes for all of these integrations.

I hit “next”

The response said, “ Linking WooCommerce integration to Facebook”

I received a message that said I lost access to my page!!

I also received an email from [security@facebookmail.com](mailto:security@facebookmail.com) with the subject:
“You no longer have full control of Sunny Dawn - Fine Art”

It read:
Hi Sunny, you’re getting this email to confirm that you no longer have full control of Sunny Dawn Fine Art. If you still want a roll on Sunny Dawn Fine Art:

You can ask one of the page owners to add you again.
If you think you were removed because your account or another page owner’s account was hacked, let us know.

Thanks,
The Facebook Security Team

This happened on July 16, 2022 and I still do not have access to my business page.  

My page no longer shows up when I sign into Meta.

I get the message: No Facebook pages or Instagram accounts.
You don’t have access to manage any Facebook pages or Instagram accounts for Sunny Dawn Freeman in this tool. You can contact a business admin to request access to an existing page or Instagram account in business settings.

## 🚶‍♀️ Steps to reproduce

1. Use the plugin Facebook for WooCommerce to attempt to integrate store catalog.

## ✔️ Expected behavior

The store catalog on my WooCommerce website should have been integrated with my Facebook Page.

## 🗃 Logs

<details>
	
</details>

</screen shots of the problem>
![Screen Shot 2022-07-16 at 2 06 37 PM](https://github.com/woocommerce/facebook-for-woocommerce/assets/27979069/3e42db20-005f-4ed9-9160-3ec5b07637db)
![Screen Shot 2022-07-16 at 2 07 39 PM](https://github.com/woocommerce/facebook-for-woocommerce/assets/27979069/0581ee21-a490-47a0-a3e6-42b43bb97611)
![Screen Shot 2022-07-16 at 2 18 20 PM](https://github.com/woocommerce/facebook-for-woocommerce/assets/27979069/2612235a-dfd2-44ef-bb35-ce8ef0ec641c)
![Screen Shot 2022-07-16 at 2 31 04 PM](https://github.com/woocommerce/facebook-for-woocommerce/assets/27979069/8de077a3-33d3-48df-8a53-3354d73a9bf6)
![Screen Shot 2022-07-16 at 2 32 47 PM](https://github.com/woocommerce/facebook-for-woocommerce/assets/27979069/f5a847f7-32b4-4106-b98e-ad92eada4d9c)
![Screen Shot 2022-07-16 at 2 37 46 PM](https://github.com/woocommerce/facebook-for-woocommerce/assets/27979069/2ab928dc-7945-4a23-b8f7-4a24f8104806)

**Comment by ibndawood** [comment]
Hello @SunnyDawn, thank you for reaching us. I understand that you've lost access to your page. Please note that the plugin does not have the access to modify a page behavior. The issue is best addressed through Facebook support. I am closing this issue as this cannot be addressed by making changes to the plugin.
