### ISSUE TITLE
PHP 7.4.0 required - No warnings

### ISSUE THREAD

**Issue by sterenas** [woocommerce/facebook-for-woocommerce#2630]
Upgraded from 3.0.32 to 3.0.33, release notes don't mention you need PHP 7.4.0. We have PHP 7.3.18 on Amazon (not really easy to upgrade PHP).
Now the plugin won't start.
Is the new PHP requirement a bug? Is there a way of downgrading to 3.0.32? Didn't find where I can download it from.
Thanks!
Sergio

**Comment by rawdreeg** [comment]
Hi @sterenas,

You can download our previous releases from the release page: https://github.com/woocommerce/facebook-for-woocommerce/releases.

If you have any more issues, the best place to get support is the [WordPress.org Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/).

If you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).
