### ISSUE TITLE
Unable to create new product in excluded category

### ISSUE THREAD

**Issue by layoutd** [woocommerce/facebook-for-woocommerce#2636]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
If a category has been added to Marketing > Facebook > Product sync > **Exclude categories from sync**, and I try to create a new product in that category (that I don't care if it doesn't sync), the resulting warning only tells me to either remove the category from excluded categories, or remove it from the product.

It should also mentioned that if I mark the product as "Do not sync", I can create it. 

![kB7fLA.gif](https://github.com/woocommerce/facebook-for-woocommerce/assets/228780/96cb2a42-a0bd-4ae8-84e0-6c8a13e0b09c)

## 🚶‍♀️ Steps to reproduce

1. Add a category to **Exclude categories from sync**.
1. Create a new product and use the excluded category.
2. See that it's impossible to create the product in the category I want (unless I enable sync for the category, which I don't want).

## ✔️ Expected behavior
The message should indicate, "To create this product anyway, please disable sync in the Facebook details section"

**Comment by sukafia** [comment]
https://wordpress.org/support/topic/excluding-a-category-becomes-a-pain

**Comment by sukafia** [comment]
@layoutd @budzanowski I think we need to increase the priority of this issue. Adding a notice for the merchant to disable sync is a good first step. 

The real solution could be automatically setting products in categories that are excluded from sync to "Do not sync"? Products are set to "Sync and show in catalog" by default - meaning merchants with products in product categories that are excluded from sync would have to manually disable sync for several products. 

We should be able to automatically set products that are in the excluded category to "Do not sync" and indicate on the product page that it was excluded on the category level.

**Comment by camilolunacom** [comment]
@sukafia thanks for posting this. I would like to add that blocking users from creating or updating products feels like a very wrong thing to do. I suggest adding an "Ignore"  button of sorts to the modal, so that you're warned but can proceed. Or maybe even a "Do not sync this product" that changes the setting for you and continues with publishing/updating the product.
