### ISSUE TITLE
Critical Error on OrderAttributionMeta.php

### ISSUE THREAD

**Issue by angelosleebos** [woocommerce/facebook-for-woocommerce#2687]
Sorry, this bug report is not intended for Facebook for Woocommerce. This report may be closed.

**Comment by angelosleebos** [comment]
Sorry, this bug report is not intended for Facebook for Woocommerce. This report may be closed.

**Comment by ibndawood** [comment]
Hello @angelosleebos. Thank you for reaching us. I'll close this issue as the error is related to WooCommerce core and not Facebook for WooCommerce.
