### ISSUE TITLE
$data['condition'] = 'new'; Hard coded with no way to change it.

### ISSUE THREAD

**Issue by digilica** [woocommerce/facebook-for-woocommerce#2700]
I am using the filter facebook_for_woocommerce_integration_prepare_product to adjust values for my products during the synchronisation with Facebook and I need to be able to specify if the item is new or used.  But I am unable to do this.

I looked through the code and noticed that in the file fbutils.php on line 733 you are hardcoding the following:
`$data['condition'] = 'new';`

As this line is called during the function normalize_product_data_for_items_batch, it is happening after the facebook_for_woocommerce_integration_prepare_product is applied so my value is being overwritten.

There is no way for me to override this hard coded value. The only way for me to fix this is to change the code of the plugin which is not ideal as it would be overwritten on next update.

My plan is to change the code at line 733 of fbutils.php to read the following:

```
if(!isset($data['condition'])||!in_array($data['condition'],['refurbished','used','new'])){
                $data['condition'] = 'new';
            }
```

With this new code, the 'new' value will still be used as default but valid alternative values will not be overwritten.

Could you please update the codebase for the next release to include the above change or something which would achieve the same results?

Also it would be very helpful to see more documentation about all of the options that can be used with the 'facebook_for_woocommerce_integration_prepare_product' filter generally. 

Thank you for your help.

```[tasklist]
### Tasks
```

**Comment by rawdreeg** [comment]
Hi @digilica,

Thanks for reporting this.

I submitted a PR with your proposed solution. Feel free to create a PR next time, we always welcome community contribution to the pugin.

Thanks,
R
