### ISSUE TITLE
Facebook Messenger - address PageSpeed Insights to lazy-load Messenger with facade before connecting.

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/facebook-for-woocommerce#2713]
## Feature requests

For sites running messages on the home page, [PageSpeed Insights](https://pagespeed.web.dev/) is suggesting to consider replacing third-party embeds with a facade until they are required. In this case, do not connect to Facebook until the messenger chat icon is clicked.

https://developer.chrome.com/docs/lighthouse/performance/third-party-facades/?utm_source=lighthouse&utm_medium=lr

**Comment by rawdreeg** [comment]
Hello @johndcoy,

Thanks for reporting this to us.

Unfortunately, we'll not be able to work on this feature.

[Meta will be sunsetting the Chat plugin on May 9, 2024](https://www.facebook.com/business/help/1524587524402327). So we're also slowly dropping Messenger support from the plugin https://github.com/woocommerce/facebook-for-woocommerce/pull/2708#issue-2202146491.
