### ISSUE TITLE
Documentation cleanup.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/facebook-for-woocommerce#2721]
With the #2719 merge we need to cleanup the plugin documentation: https://woocommerce.com/document/facebook-for-woocommerce/

1. Modify the notice to state that the chat is no longer supported since version x.x.x
https://woocommerce.com/document/facebook-for-woocommerce/

2. Remove chat mentions from other parts of the documentation.

**Comment by layoutd** [comment]
✅  **Done**
- All references to Messenger removed in https://woocommerce.com/document/facebook-for-woocommerce/, except for one section explaining it's removal in May 2024 with the release of [v3.2.0](https://github.com/woocommerce/facebook-for-woocommerce/releases/tag/3.2.0).
- Removed Messenger smoke tests from https://github.com/woocommerce/facebook-for-woocommerce/wiki/Smoke-tests

👉🏻 **Note** 
Removing a few remaining Messenger code references will be tracked in #2724:
![image](https://github.com/woocommerce/facebook-for-woocommerce/assets/228780/33d42f29-56ad-4636-9d45-612b96c07169)
