### ISSUE TITLE
Products in multiple languages

### ISSUE THREAD

**Issue by NicolaModugno** [woocommerce/facebook-for-woocommerce#2761]
Hello everyone,
It would be VERY useful to be able to separate the products list into several languages (either manually or by following the languages set via PolyLang or WPML).
(I refer to this functionality of the Meta catalogue: https://www.facebook.com/business/help/127019799344394)

Are there any plans to implement this functionality?

Managing the division of products by hand can become cumbersome for large catalogues.

Thank you all!
Nicola

**Comment by layoutd** [comment]
Hi @NicolaModugno, thanks for bringing this issue to our attention. Product lists by language isn't a feature that is currently planned for the extension, but you can add a request for the feature, and our team will review: https://woocommerce.com/feature-requests/facebook/
