### ISSUE TITLE
Event Parameters Blocked by Meta - Need Assistance with Removal

### ISSUE THREAD

**Issue by ricardoaraujo330** [woocommerce/facebook-for-woocommerce#2771]
Hello,

I received a notification email regarding blocked event parameters for my Facebook for WooCommerce integration. The message indicated that some parameters in my data may contain information that violates Meta's Business Tools Terms. As a result, these parameters have been blocked.

Here is the content of the notification:

"4 parameters blocked

Some event parameters in your data, may contain information that violates Meta's Business Tools Terms. The parameters are blocked. Please review and correct the parameters. By resolving these issues, you are helping us protect your users and your business.

Further issues may result in data restrictions and limited functionality in certain advertising features, such as custom conversions and custom audiences.

**Blocked parameters by Meta**

These parameters need to be removed from your integration setup.

last_name
first_name
and 2 more
Learn more
Troubleshooting issues related to Meta Business Tools Data Policy violations
"

I would like to know how to remove these parameters from my integration or if this is something that can be adjusted in a future update of the Facebook for WooCommerce plugin.

Thank you for your assistance.

Best regards,
Ricardo

**Comment by layoutd** [comment]
Hi @ricardoaraujo330,

Usually the best way to get answers to these questions is to search and/or open a thread on the plugin support forum. In another thread with a similar topic, it was confirmed that "Neither WooCommerce nor Facebook for WooCommerce would add those query parameters to any GET requests":
https://wordpress.org/support/topic/potentially-violating-personal-data-sent-to-facebook-2/

The Facebook for WooCommerce extension is only passing a referrer URL to FB, which may contain the data indicated in the warning. Neither WooCommerce nor the extension add these additional parameters to the URL. WooCommerce only adds the "key" param and, in some cases  `utm_nooverride`. The only other explanation would be that these parameters are added to the IPN URL provided to a payment processor, so you may also find the cause if you inspect any third-party payment processors.

I will mark this issue as closed. However, feel free to start a thread in the support forum if you continue to receive similar warnings from Meta.
