### ISSUE TITLE
Inconsistent use of get_title vs. get_name on product objects

### ISSUE THREAD

**Issue by Dekadinious** [woocommerce/facebook-for-woocommerce#2774]
You sometimes use `$product->get_title()` for content_name and sometimes use `$product->get_name()`.

This creates inconsistencies between events and the catalog.

**Comment by brezocordero** [comment]
`$product->get_title()` is used on [this event](https://github.com/woocommerce/facebook-for-woocommerce/blob/b15db2b481e040f9a0618356b955dcd121f1f8c8/facebook-commerce-events-tracker.php#L520), the other events use `$product->get_name()`. Should be consisten.

**Comment by rawdreeg** [comment]
Thanks, @brezocordero, for looking into this. I will add a quick PR to fix this
