### ISSUE TITLE
Fatal error: Uncaught Error: Undefined constant WooCommerce\Facebook\Lifecycle::SETTING_ENABLE_DEBUG_MODE

### ISSUE THREAD

**Issue by rawdreeg** [woocommerce/facebook-for-woocommerce#2778]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
When updating from 1.x.x to the latest version, we see the following errors.

Fatal error: Uncaught Error: Undefined constant WooCommerce\Facebook\Lifecycle::SETTING_ENABLE_DEBUG_MODE in /code/wp-content/plugins/facebook-for-woocommerce/includes/Lifecycle.php:227

## 🚶‍♀️ Steps to reproduce

When updating from 1.x.x to the latest version, we see the following errors. The error is on the upgrade_to_2_0_0.

**Comment by ecgan** [comment]
This is fixed in PR https://github.com/woocommerce/facebook-for-woocommerce/pull/2779. Closing this issue.
