### ISSUE TITLE
Linking WooCommerce Integration with Facebook

### ISSUE THREAD

**Issue by nandi-shop** [woocommerce/facebook-for-woocommerce#2805]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Hello, after installing the plugin I made the integration with the advertising account meta. It was successful.

Translated with DeepL.com (free version)
## 🚶‍♀️ Steps to reproduce

1. The first step  Then in the marketing tab , connection tab, I clicked on the manage connection button.
2. The next step…After redirecting to business manager, a message appears 
"Additional features are available for you
3. The next step…Activate the additional features and make the most of this application."
4. The next step…After clicking "view features" a window will appear with the following information:
"Connect to WooCommerce Integration
5. The next step…Connect the WooCommerce Integration platform to Facebook
What permissions do I grant?"
6. The next step…After clicking "continue"
you will be redirected to https://connect.woocommerce.com/app-store-login/facebook/................
7. The next step…After entering the domain of our store, the error message "400 Bad Request
nginx"
 

## ✔️ Expected behavior

The redirection and approval of the Facebook functionality extension should have taken place
## 🗃 Logs

<details>
	
</details>

```[tasklist]
### Tasks
```

**Comment by layoutd** [comment]
Hi @nandi-shop, this issue is also reported and discussed here: https://github.com/woocommerce/facebook-for-woocommerce/issues/2795
