### ISSUE TITLE
Plugin Causing 'White Screen of Death'

### ISSUE THREAD

**Issue by vorthaditya** [woocommerce/facebook-for-woocommerce#2813]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
 It causes white screen of death on wordpress, Front end is all blank while backend is working. It only gets normal after we disable 'Facebook for Woocommerce' plugin.

## 🚶‍♀️ Steps to reproduce

1. Activate the Plugin 'Facebook for Woocommerce'
1. The next step… 

## ✔️ Expected behavior
 It should normally open the webpage which is showing as blank

## 🗃 Logs
 
Wordpress version : 6.6.2
PHP : 7.4.33
WooCommerce 9.1.2 
Facebook for WooCommerce 3.2.10

WordPress has a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, Facebook for WooCommerce.

First, visit your website (https://vorth.in/) and check for any visible issues. Next, visit the page where the error was caught (https://vorth.in/wp-admin/) and check for any visible issues.

<details>
	
</details>

**Comment by layoutd** [comment]
Hello @vorthaditya,

Sorry to hear about the difficulty installing Facebook for WooCommerce.  We've tested the extension with the versions you've provided and have not been able to reproduce the error.

Please open a thread on the extension support forums (https://wordpress.org/support/plugin/facebook-for-woocommerce/) to receive assistance, and provide logs that indicate the error message.

Cheers
