### ISSUE TITLE
Size variants incorrectly ordered in Facebook shop

### ISSUE THREAD

**Issue by Techtonik11** [woocommerce/facebook-for-woocommerce#309]
Hi,
My products are appearing correctly in woocommerce, with the size variants ordered from S (Small) to 2XL(extra large). The products are syncing to my Facebook shop, however the order of the size variant are all mixed up. Does anyone know if this is a bug, or how to fix this?

![screen-shot-2018-03-05-at-2 16 09-pm](https://user-images.githubusercontent.com/37058886/36958898-281ccae4-2093-11e8-8d82-7a4485d05791.jpg)

**Comment by mengyingdu** [comment]
Hi @Techtonik11 ,

We don't sort size. I tried to use the order typed in 'Attribute' tag,  as L, 2XL, XL, M, S to see whether this will sort as you want. However, neither the my test site nor the facebook shop sort them. I think the order will be the order you see in 'variations' tab.
![screen shot 2018-03-05 at 4 15 10 pm](https://user-images.githubusercontent.com/24535640/37007279-69b8a98e-2091-11e8-9b35-8cf524d4df83.png)
![screen shot 2018-03-05 at 4 16 14 pm](https://user-images.githubusercontent.com/24535640/37007282-6e647d8c-2091-11e8-9e26-27ab6fe662fc.png)
![screen shot 2018-03-05 at 4 17 47 pm](https://user-images.githubusercontent.com/24535640/37007298-7a8e9e08-2091-11e8-9d5a-809d2793e4eb.png)

If you really need to sort it as you prefer, you can try to delete the wrong item in the list and then manually add a variation. It's not the ideal way, but we may consider add this feature in the future based on user request. Also, welcome to send us a pull request, we'll be actively support pull request review.

Thanks.

**Comment by Techtonik11** [comment]
Hi @mengyingdu

I have ordered my size attributes ordered correctly in woocommerce (S,M,L,XL,2XL) and they appear this way in my wordpress store. It is only in Facebook (using the plugin) that they're out of order. 

![screen shot 2018-03-06 at 11 55 22 am](https://user-images.githubusercontent.com/37058886/37008277-6e2c2348-2135-11e8-9c9a-3cbb67af4ba3.png)
![screen shot 2018-03-06 at 11 55 58 am](https://user-images.githubusercontent.com/37058886/37008284-725859f0-2135-11e8-855e-cf686203de70.png)

**Comment by Bigben1144** [comment]
I'M having the same issue. Anyone found a solution?

**Comment by dmitridr** [comment]
Unfortunately we don't provide explicit control over ordering, the Facebook infrastructure does not support it right now. I think implicitly the order is as Mengying pointed out, based on which variant is uploaded first.

One more thought : Collections provide more control over how the products are displayed, maybe even the ordering. Have you tried creating separate collections and seeing if you can change the order there?

**Comment by budzanowski** [comment]
This is not something that the plugin itself can fix, this needs to be addressed on the Facebook server side. Closing until something changes and we would have more control over this in the plugin.
